Repository mondaycom/vibe, pull requests merged in 2021-12, with the labels that each got.

#362 Storybook/hadasfa/design fix
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__stories__/checkbox.stories.scss
  src/storybook/components/anchor-list-item/anchor-list-item.scss
  src/storybook/components/component-name/component-name.scss
  src/storybook/components/related-components/related-components.scss
  src/storybook/components/usage-guidelines/usage-guideline.scss
  src/storybook/styles/typography.scss
Labels: PR: Documentation 📖

#359 LeanyLabs/storybook#4
  build-storybook.log
  src/components/ButtonGroup/__stories__/ButtonGroup.stories.mdx
  src/components/ButtonGroup/__stories__/assets/Desktop.js
  src/components/ButtonGroup/__stories__/buttonGroup.stories.js
  src/components/ButtonGroup/__stories__/buttonGroup.stories.scss
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.js.snap
  src/components/ButtonGroup/__tests__/buttonGroup-snapshot-tests.jest.js
  src/components/ButtonGroup/__tests__/buttonGroup-tests.jest.js
  src/components/Chips/__stories__/chips.stories.scss
  src/components/Counter/__stories__/counter.stories.js
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Counter/__stories__/counter.stories.scss
  src/components/Counter/__tests__/__snapshots__/counter-snapshot-tests.jest.js.snap
  src/components/Counter/__tests__/__snapshots__/counter.jest.js.snap
  src/components/Counter/__tests__/counter-snapshot-tests.jest.js
  src/components/Counter/__tests__/counter-tests.jest.js
  src/components/Counter/__tests__/counter.jest.js
  src/components/SplitButton/__stories__/SplitButtonExampleDialog.jsx
  src/components/SplitButton/__stories__/splitButton.stories.js
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.scss
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/SplitButton/__tests__/__snapshots__/splitButton.jest.js.snap
  src/components/SplitButton/__tests__/splitButton-snapshot-tests.jest.js
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/breadcrumbs-description.jsx
  src/storybook/components/related-components/descriptions/button-description.jsx
  src/storybook/components/related-components/descriptions/menu-description.jsx
  src/storybook/components/related-components/descriptions/tab-description.jsx
Labels: PR: Documentation 📖

#367 add MenuButton props to control dialog hide/show trigger ignore class
  src/components/MenuButton/MenuButton.jsx
Labels: PR: New Feature 🕹

#368 Add Text Medium
  package.json
  src/components/Icon/Icons/components/TextBig.js
  src/components/Icon/Icons/components/TextHuge.js
  src/components/Icon/Icons/components/TextMedium.js
  src/components/Icon/Icons/index.js
Labels: PR: Icon 💎

#370 fix package lock
  package-lock.json
Labels: PR: Bugfix 🐛

#369 add MenuButton onClick prop
  src/components/MenuButton/MenuButton.jsx
  src/components/MenuButton/__stories__/menuButton.stories.js
Labels: PR: New Feature 🕹

#373 feat: icons
  package-lock.json
  package.json
  src/components/Icon/Icons/components/CollapseRound.js
  src/components/Icon/Icons/components/ItemHeightTriple.js
  src/components/Icon/Icons/components/LongText.js
  src/components/Icon/Icons/components/Pin.js
  src/components/Icon/Icons/components/ShortText.js
  src/components/Icon/Icons/index.js
Labels: PR: Icon 💎

#375 passing index to getter in virtualized list
  src/components/VirtualizedList/virtualized-list-service.js
Labels: PR: Bugfix 🐛

#374 Fix `<Dropdown>` multi-value bug
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__tests__/driver.js
  src/components/Dropdown/__tests__/dropdown.jest.js
Labels: PR: Bugfix 🐛

#377 add modifiers support to tipseen and tooltip
  src/components/Dropdown/__tests__/dropdown.jest.js
  src/components/Tipseen/Tipseen.jsx
  src/components/Tooltip/Tooltip.jsx
Labels: PR: New Feature 🕹

#376 added indexes for other idGetter usages
  src/components/VirtualizedList/virtualized-list-service.js
Labels: PR: Bugfix 🐛

#378 Fix `<Dropdown>` test driver
  src/components/Dropdown/__tests__/driver.js
  src/components/Dropdown/__tests__/dropdown.jest.js
Labels: PR: Internal 🏠

#372 Leany labs/storybook 5
  .storybook/preview.js
  build-storybook.log
  src/components/Link/Link-test.js
  src/components/Link/__stories__/Link.stories.mdx
  src/components/Link/__stories__/Link.stories.scss
  src/components/Link/__stories__/link-story.scss
  src/components/Link/__stories__/link.stories.js
  src/components/Link/__tests__/__snapshots__/link-snapshot-tests.jest.js.snap
  src/components/Link/__tests__/link-snapshot-tests.jest.js
  src/components/Link/__tests__/link-tests.jest.js
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Search/__stories__/Search.stories.scss
  src/components/Search/__stories__/search.stories.js
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/Search/__tests__/search-snapshot-tests.jest.js
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/TextField/__stories__/TextField.stories.scss
  src/components/TextField/__stories__/textField.stories.js
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/textField-snapshot-tests.jest.js
  src/components/TextField/__tests__/textField-tests.jest.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/combobox-description.jsx
  src/storybook/components/related-components/descriptions/search-description.jsx
  src/storybook/components/related-components/descriptions/text-field-description.jsx
Labels: PR: Documentation 📖

#381 added new icons
  package-lock.json
  package.json
  src/components/Icon/Icons/components/Rotate.js
  src/components/Icon/Icons/index.js
Labels: PR: Icon 💎

#382 changed user batch actions icons svg content - Icon 💎
  package-lock.json
  package.json
  src/components/Icon/Icons/components/AddToTeam.js
  src/components/Icon/Icons/components/Deactivate.js
  src/components/Icon/Icons/components/PersonRound.js
  src/components/Icon/Icons/components/UserDomain.js
  src/components/Icon/Icons/components/UserStatus.js
Labels: PR: Icon 💎

#384 fix accordion item type check
  src/components/Accordion/Accordion/Accordion.jsx
  src/components/Accordion/AccordionItem/AccordionItem.jsx
Labels: PR: Bugfix 🐛

#385 expose colors-utils
  src/components/index.js
  src/published-components.js
Labels: PR: New Feature 🕹

#386 set default color to tabs titles
  src/components/Tabs/Tab/Tab.scss
Labels: PR: Bugfix 🐛

#387 export color utils as default object (for fixing error while trying to create new version)
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/utils/colors-utils.js
Labels: PR: Bugfix 🐛

#388 Fix bug on color utils
  src/published-components.js
Labels: PR: Bugfix 🐛

#390 Fix bugs on allow multiple on click
  src/components/Accordion/Accordion/Accordion.jsx
Labels: PR: Bugfix 🐛

#391 quick fix in the index of color utils
  src/components/index.js
Labels: PR: Bugfix 🐛

#389 added classname to the virtualized list where scrollbars appears
  src/components/VirtualizedList/VirtualizedList.jsx
Labels: PR: Bugfix 🐛

#393 Storybook/hadas/menu reorder
  .storybook/preview.js
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/ButtonGroup.stories.mdx
  src/components/ButtonGroup/__stories__/buttonGroup.stories.js
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/general-stories/Changelog/changelog.stories.mdx
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
Labels: PR: Documentation 📖

#380 Leany labs/storybook 6
  src/components/Steps/__stories__/helpers.js
  src/components/Steps/__stories__/steps.stories.js
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Steps/__stories__/steps.stories.scss
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/steps-snapshot-tests.jest.js
  src/components/Steps/__tests__/steps-tests.jest.js
  src/components/Steps/__tests__/steps.jest.js
  src/components/Tipseen/__stories__/assets/picture.png
  src/components/Tipseen/__stories__/helper.js
  src/components/Tipseen/__stories__/tipseen.stories.js
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.scss
  src/components/Tipseen/__tests__/__snapshots__/tipseen-snapshot-tests.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseenContent.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseenImage.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseenWizard.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-snapshot-tests.jest.js
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
  src/components/Tipseen/__tests__/tipseen.jest.js
  src/components/Tipseen/__tests__/tipseenContent.jest.js
  src/components/Tipseen/__tests__/tipseenImage.jest.js
  src/components/Tipseen/__tests__/tipseenWizard.jest.js
  src/components/Tooltip/__stories__/helper.js
  src/components/Tooltip/__stories__/tooltip-story.scss
  src/components/Tooltip/__stories__/tooltip.stories.js
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.scss
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.js.snap
  src/components/Tooltip/__tests__/tooltip-snapshot-tests.jest.js
  src/components/Tooltip/__tests__/tooltip-tests.jest.js
  src/components/Tooltip/__tests__/tooltip.jest.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/tipseen-description.jsx
  src/storybook/components/related-components/descriptions/wizard-description.jsx
Labels: PR: Documentation 📖

#392 Storybook/hadas/spacing page
  src/general-stories/global-design/SpacingComponent.jsx
  src/general-stories/global-design/SpacingComponent.scss
  src/general-stories/global-design/globalDesign.stories.mdx
  src/storybook/stand-alone-documentaion/spacing/assets/index.js
  src/storybook/stand-alone-documentaion/spacing/assets/menuExample.png
  src/storybook/stand-alone-documentaion/spacing/assets/tipseenExample.png
  src/storybook/stand-alone-documentaion/spacing/assets/toolbarExample.png
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-component/spacing-component.jsx
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-component/spacing-component.scss
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-sizes.jsx
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-sizes.scss
  src/storybook/stand-alone-documentaion/spacing/spacing.stories.mdx
  src/storybook/stand-alone-documentaion/spacing/spacing.stories.scss
Labels: PR: Documentation 📖

#394 Storybook/hadas/shadow
  src/storybook/components/frame/frams.scss
  src/storybook/stand-alone-documentaion/shadow/assets/index.js
  src/storybook/stand-alone-documentaion/shadow/assets/peopleColumn.png
  src/storybook/stand-alone-documentaion/shadow/assets/shadowsSketch.png
  src/storybook/stand-alone-documentaion/shadow/card-shadow-example/card-shadow-example.jsx
  src/storybook/stand-alone-documentaion/shadow/card-shadow-example/card-shadow-example.module.scss
  src/storybook/stand-alone-documentaion/shadow/drag-shadow-example/drag-shadow-example.jsx
  src/storybook/stand-alone-documentaion/shadow/drag-shadow-example/drag-shadow-example.module.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.jsx
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-levels.jsx
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-levels.scss
  src/storybook/stand-alone-documentaion/shadow/shadow.stories.mdx
  src/storybook/stand-alone-documentaion/shadow/shadow.stories.scss
  src/storybook/stand-alone-documentaion/typography/typography.scss
Labels: PR: Documentation 📖

#395 Feat/orr/stories rest
  .storybook/preview.js
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/components/Clickable/__stories__/clickable.stories.js
  src/components/Clickable/__stories__/clickable.stories.scss
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
  src/components/ColorPicker/__stories__/colorPicker.stories.js
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/DialogContentContainer/DialogContentContainer.jsx
  src/components/DialogContentContainer/DialogContentContainer.scss
  src/components/DialogContentContainer/__stories__/DialogContentContainer.stories.mdx
  src/components/DialogContentContainer/__stories__/DialogContentContainerExample.jsx
  src/components/DialogContentContainer/__stories__/DialogContentContainerExample.module.scss
  src/components/DialogContentContainer/__stories__/dialogContentContainer.stories.js
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__stories__/editableHeading.stories.js
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Loader/__stories__/Loader.stories.scss
  src/components/Loader/__stories__/loader.stories.js
Labels: PR: Documentation 📖

#398 Change SASS loader package
  .gitignore
  .stylelintrc.json
  build-storybook.log
  package-lock.json
  package.json
  src/components/Accordion/Accordion/Accordion.scss
  src/components/AlertBanner/AlertBannerText/AlertBannerText.scss
  src/components/AttentionBox/AttentionBox.scss
  src/components/Avatar/Avatar.scss
  src/components/Banner/Banner.scss
  src/components/Counter/Counter.scss
  src/components/Dialog/DialogContent/DialogContent.scss
  src/components/Divider/Divider.scss
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/components/menu/menu.scss
  src/components/EditableHeading/EditableHeading.scss
  src/components/EditableInput/EditableInput.scss
  src/components/ExpandCollapse/ExpandCollapse.scss
  src/components/FieldLabel/FieldLabel.scss
  src/components/Heading/Heading.scss
  src/components/Label/Label.scss
  src/components/Label/__stories__/label.stories.scss
  src/components/Menu/MenuItem/MenuItem.scss
  src/components/Menu/MenuItemButton/MenuItemButton.scss
  src/components/Menu/MenuTitle/MenuTitle.scss
  src/components/MultiStepIndicator/MultiStepIndicator.scss
  src/components/RadioButton/RadioButton.scss
  src/components/SplitButton/SplitButton.scss
  src/components/Steps/Steps.scss
  src/components/TextField/TextField.scss
  src/components/TextField/__tests__/textField-tests.jest.js
  src/components/Tooltip/Tooltip.scss
  src/general-stories/global-design/BoxShadowComponent.scss
  src/general-stories/global-design/GlobalSettingGeneralComponent.scss
  src/general-stories/global-design/RoundedCornerComponent.scss
  src/general-stories/global-design/globalDesign.scss
  src/general.scss
  src/index.js
  src/storybook/stand-alone-documentaion/shadow/card-shadow-example/card-shadow-example.module.scss
  src/styles/global-css-settings.scss
  src/styles/states.scss
  src/styles/theme-mixin.scss
  src/styles/themes.scss
  src/styles/typography.scss
  webpack.config.js
Labels: PR: Breaking Changes 💥

#397 Storybook/hadas/colors function page
  src/general-stories/colors/colors-vars-map.js
  src/storybook/components/colors-description/colors-description.jsx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/typography-description/typography-description.jsx
  src/storybook/components/text-colors/text-colors.jsx
  src/storybook/stand-alone-documentaion/colors/assets/cardColorsExample.png
  src/storybook/stand-alone-documentaion/colors/assets/index.js
  src/storybook/stand-alone-documentaion/colors/assets/menuColorsExample.png
  src/storybook/stand-alone-documentaion/colors/background-colors/background-colors.jsx
  src/storybook/stand-alone-documentaion/colors/border-colors/border-colors.jsx
  src/storybook/stand-alone-documentaion/colors/colors.stories.mdx
  src/storybook/stand-alone-documentaion/colors/colors.stories.module.scss
  src/storybook/stand-alone-documentaion/colors/content-color-cell/content-color-cell.jsx
  src/storybook/stand-alone-documentaion/colors/content-color-cell/content-color-cell.module.scss
  src/storybook/stand-alone-documentaion/colors/content-color-row/content-color-row.jsx
  src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.jsx
  src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.module.scss
  src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
  src/utils/colors-utils.js
Labels: documentation, PR: Documentation 📖

#396 Leany labs/storybook 7
  build-storybook.log
  package-lock.json
  src/components/Accordion/Accordion/__stories__/accordion.stories.js
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/Accordion/Accordion/__stories__/accordion.stories.scss
  src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
  src/components/Accordion/Accordion/__tests__/accordion-snapshot-tests.jest.js
  src/components/Accordion/Accordion/__tests__/accordion.jest.js
  src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
  src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem.jest.js.snap
  src/components/Accordion/AccordionItem/__tests__/accordionItem-snapshot-tests.jest.js
  src/components/Accordion/AccordionItem/__tests__/accordionItem-tests.jest.js
  src/components/Accordion/AccordionItem/__tests__/accordionItem.jest.js
  src/components/ProgressBars/LinearProgressBar/__stories__/assets/Logo.png
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.js
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.scss
  src/components/ProgressBars/LinearProgressBar/__tests__/__snapshots__/linearProgressBar-snapshot-tests.jest.js.snap
  src/components/ProgressBars/LinearProgressBar/__tests__/linearProgressBar-snapshot-tests.jest.js
  src/components/ProgressBars/LinearProgressBar/__tests__/linearProgressBar-tests.jest.js
  src/components/Tabs/Tab/__stories__/tab.stories.js
  src/components/Tabs/Tab/__stories__/tab.stories.mdx
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/components/Tabs/Tab/__tests__/tab-snapshot-tests.jest.js
  src/components/Tabs/Tab/__tests__/tab-tests.jest.js
  src/components/Tabs/Tab/__tests__/tab.jest.js
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/__tests__/tabList-snapshot-tests.jest.js
  src/components/Tabs/TabList/__tests__/tabList.jest.js
  src/components/Tabs/TabPanel/__tests__/__snapshots__/tabPanel-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanel/__tests__/__snapshots__/tabPanel.jest.js.snap
  src/components/Tabs/TabPanel/__tests__/tabPanel-snapshot-tests.jest.js
  src/components/Tabs/TabPanel/__tests__/tabPanel.jest.js
  src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanels/__tests__/tabPanels-snapshot-tests.jest.js
  src/components/Tabs/TabPanels/__tests__/tabPanels.jest.js
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext.jest.js.snap
  src/components/Tabs/TabsContext/__tests__/tabsContext-snapshot-tests.jest.js
  src/components/Tabs/TabsContext/__tests__/tabsContext.jest.js
  src/components/Tabs/__stories__/tabs.overview.jsx
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.scss
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/skeleton-description.jsx
  src/storybook/components/related-components/descriptions/spinner-description.jsx
  src/storybook/components/related-components/descriptions/stepper-description.jsx
Labels: PR: Documentation 📖

#400 WIP: Coming soon & fix tests errors (css and js)
  src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
  src/components/Avatar/__stories__/avatar.stories.scss
  src/components/Banner/Banner.scss
  src/components/Button/Button.scss
  src/components/Checkbox/Checkbox.scss
  src/components/Chips/Chips.scss
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.scss
  src/components/Dropdown/components/menu/menu.scss
  src/components/ExpandCollapse/ExpandCollapse.scss
  src/components/Icon/CustomSvgIcon.jsx
  src/components/Icon/CustomSvgIcon.scss
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/IconButton.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.scss
  src/components/RadioButton/RadioButton.scss
  src/components/Skeleton/Skeleton.scss
  src/components/SplitButton/SplitButton.scss
  src/components/Steps/Steps.scss
  src/components/Tabs/TabList/TabList.scss
  src/components/Tabs/__stories__/tabs.overview.jsx
  src/components/TextField/TextField.scss
  src/components/TextWithHighlight/TextWithHighlight.scss
  src/components/Toggle/Toggle.scss
  src/components/Tooltip/__stories__/TooltipContent.jsx
  src/components/Tooltip/__stories__/TooltipContent.scss
  src/components/storybook-helpers/color-item/color-item.scss
  src/storybook/components/coming-soon/assets/comingSoon.png
  src/storybook/components/coming-soon/assets/index.jsx
  src/storybook/components/coming-soon/coming-soon.jsx
  src/storybook/components/coming-soon/coming-soon.module.scss
  src/storybook/components/component-rule/component-rule.scss
  src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
  src/storybook/stand-alone-documentaion/colors/colors.stories.mdx
  src/storybook/stand-alone-documentaion/motion/motion.stories.mdx
  src/storybook/stand-alone-documentaion/shadow/drag-shadow-example/drag-shadow-example.module.scss
Labels: PR: Documentation 📖

#402 Storybook/hadas/controls infra
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Button/Button.jsx
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/ButtonGroup.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/storybook/components/tip/tip.jsx
  src/storybook/components/usage-guidelines/usage-guidelines.jsx
  src/storybook/functions/create-component-story.js
Labels: PR: Documentation 📖

#403 LeanyLabs/storybook 8
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.js
  src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.mdx
  src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.scss
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem-snapshot-tests.jest.js.snap
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem.jest.js.snap
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/breadcrumbItem-snapshot-tests.jest.js
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/breadcrumbItem-tests.jest.js
  src/components/BreadcrumbsBar/__stories__/assets/person3.png
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.js
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.mdx
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.scss
  src/components/BreadcrumbsBar/__tests__/__snapshots__/breadcrumbsBar-snapshot-tests.jest.js.snap
  src/components/BreadcrumbsBar/__tests__/breadcrumbsBar-snapshot-tests.jest.js
  src/components/BreadcrumbsBar/__tests__/breadcrumbsBar.jest.js
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/ButtonGroup.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/MultiStepIndicator/__stories__/helper.js
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.js
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.scss
  src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator-snapshot-tests.jest.js.snap
  src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator.jest.js.snap
  src/components/MultiStepIndicator/__tests__/multiStepIndicator-snapshot-tests.jest.js
  src/components/MultiStepIndicator/__tests__/multiStepIndicator-tests.jest.js
  src/components/MultiStepIndicator/__tests__/multiStepIndicator.jest.js
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Skeleton/__stories__/assets/person.png
  src/components/Skeleton/__stories__/skeleton.stories.js
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.scss
  src/components/Skeleton/__tests__/__snapshots__/skeleton-snapshot-tests.jest.js.snap
  src/components/Skeleton/__tests__/skeleton-snapshot-tests.jest.js
  src/components/Skeleton/__tests__/skeleton.jest.js
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/avatar-description.jsx
  src/storybook/components/related-components/descriptions/icons-description.jsx
  src/storybook/components/related-components/descriptions/progress-bar-description.jsx
Labels: PR: Documentation 📖

#406 Add `useAfterFirstRender` story
  src/hooks/__stories__/useClickOutside.stories.mdx
  src/hooks/__stories__/useEventListener.stories.mdx
  src/hooks/__stories__/useTimeout.stories.mdx
  src/hooks/useAfterFirstRender/__stories__/useAfterFirstRender.stories.mdx
  src/hooks/useAfterFirstRender/index.js
Labels: PR: Documentation 📖

#405 menu & shadow description and more
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__stories__/Menu.stories.module.scss
  src/components/Menu/Menu/__stories__/menu.stories.js
  src/components/Menu/MenuDivider/MenuDivider.jsx
  src/components/Menu/MenuDivider/__stories__/MenuDivider.stories.mdx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
  src/components/Menu/MenuItem/__stories__/menuItem.stories.js
  src/components/Menu/MenuItem/__tests__/menuItem-snapshots.jest.js
  src/components/Menu/MenuItemButton/MenuItemButton.jsx
  src/components/Menu/MenuItemButton/__stories__/MenuItemButton.stories.mdx
  src/components/Menu/MenuItemButton/__stories__/menuItemButton.stories.js
  src/components/Menu/MenuTitle/MenuTitle.jsx
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.js
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.mdx
  src/components/Menu/MenuTitle/__stories__/menuTitle.stories.js
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/storybook-helpers/color-item/color-item.scss
  src/storybook/components/component-description/component-description.jsx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/shadow-description/shadow-description.jsx
  src/storybook/components/related-components/descriptions/shadow-description/shadow-description.module.scss
  src/storybook/components/related-components/related-components.jsx
  src/storybook/stand-alone-documentaion/colors/colors.stories.mdx
  src/storybook/stand-alone-documentaion/shadow/shadow.stories.mdx
  src/storybook/stand-alone-documentaion/spacing/spacing.stories.mdx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
Labels: PR: Documentation 📖

#409 WIP: divider, list and more
  src/components/AttentionBox/AttentionBox.jsx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.mdx
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.mdx
  src/components/ButtonGroup/__stories__/ButtonGroup.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/ColorPicker/ColorPicker.jsx
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/DialogContentContainer/__stories__/DialogContentContainer.stories.mdx
  src/components/Divider/Divider.jsx
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/Divider/__stories__/Divider.stories.module.scss
  src/components/Divider/__stories__/divider.stories.js
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/List/__stories__/List.stories.mdx
  src/components/List/__stories__/List.stories.module.scss
  src/components/List/__stories__/list.stories.js
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/ListItem/__stories__/ListItem.stories.scss
  src/components/ListItem/__stories__/listItem.stories.js
  src/components/ListItemIcon/ListItemIcon.jsx
  src/components/ListItemIcon/__stories__/ListItemIcon.stories.mdx
  src/components/ListItemIcon/__stories__/ListItemIcon.stories.scss
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.jsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.js
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toggle/Toggle.jsx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/general-stories/colors/colors-vars-map.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/heading-description.jsx
  src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.jsx
  src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.module.scss
  src/storybook/stand-alone-documentaion/welcome/assets/Nick.png
  src/storybook/stand-alone-documentaion/welcome/assets/NickBackground.png
  src/storybook/stand-alone-documentaion/welcome/assets/index.js
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.scss
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
Labels: PR: Documentation 📖

#410 Add `useDebounceEvent` stories
  .storybook/preview.js
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/hooks/useDebounceEvent/__stories__/useDebounceEvent.stories.mdx
  src/hooks/useDebounceEvent/index.js
  src/storybook/components/function-arguments/README.md
  src/storybook/components/function-arguments/index.jsx
  src/storybook/components/function-arguments/index.module.scss
  src/storybook/components/index.jsx
Labels: PR: Documentation 📖

#408 Heading and spacing description
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/Heading/Heading.jsx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Heading/__stories__/Heading.stories.module.scss
  src/components/Heading/__stories__/assets/emptyStateExample.svg
  src/components/Heading/__stories__/assets/index.js
  src/components/Heading/__stories__/heading.stories.js
  src/storybook/components/coming-soon/coming-soon.jsx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/editable-heading-description.jsx
  src/storybook/components/related-components/descriptions/spacing-description/spacing-description.jsx
  src/storybook/components/related-components/descriptions/spacing-description/spacing-description.module.scss
  src/storybook/stand-alone-documentaion/colors/colors.stories.mdx
  src/storybook/stand-alone-documentaion/colors/colors.stories.module.scss
  src/storybook/stand-alone-documentaion/shadow/shadow.stories.mdx
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
Labels: PR: Documentation 📖

#407 Move existing hooks stories next to them
  src/hooks/__stories__/useTimeout.stories.mdx
  src/hooks/useAfterFirstRender/__stories__/useAfterFirstRender.stories.mdx
  src/hooks/useClickOutside/__stories__/useClickOutside.stories.mdx
  src/hooks/useClickOutside/index.js
  src/hooks/useEventListener/__stories__/DummyComponent.jsx
  src/hooks/useEventListener/__stories__/useEventListener.stories.mdx
  src/hooks/useEventListener/index.js
  src/hooks/useTimeout/__stories__/useTimeout.stories.mdx
  src/hooks/useTimeout/index.js
  src/hooksDummyComponents/UseClickOutSide.jsx
  src/hooksDummyComponents/UseTimeout.jsx
  src/published-components.js
  src/storybook/components/function-arguments/index.jsx
  src/storybook/components/function-arguments/index.module.scss
Labels: PR: Documentation 📖

#411 Storybook/hadas/final tweeks
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/Avatar/Avatar.jsx
  src/components/Checkbox/Checkbox.scss
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/Divider/__stories__/Divider.stories.module.scss
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/ListItem/__stories__/ListItem.stories.scss
  src/components/ListItemIcon/__stories__/ListItemIcon.stories.mdx
  src/components/ListItemIcon/__stories__/ListItemIcon.stories.scss
  src/components/ListItemIcon/__stories__/listItemIcon.stories.js
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/general-stories/colors/ColorItem.scss
  src/general-stories/colors/colors-helper.js
  src/general-stories/colors/colors-vars-map.js
  src/general-stories/colors/colors.stories.js
  src/general-stories/focus/focus.scss
  src/general-stories/focus/focus.stories.js
  src/general-stories/foundations-stories.js
  src/general-stories/global-design/BoxShadowComponent.jsx
  src/general-stories/global-design/BoxShadowComponent.scss
  src/general-stories/global-design/RoundedCornerComponent.jsx
  src/general-stories/global-design/globalDesign.scss
  src/general-stories/global-design/globalDesign.stories.mdx
  src/storybook/functions/create-component-story.js
  src/storybook/stand-alone-documentaion/change-log/changelog.stories.mdx
  src/storybook/stand-alone-documentaion/round-corners/corners-settings/corner-settings.jsx
  src/storybook/stand-alone-documentaion/round-corners/corners-settings/corner-settings.scss
  src/storybook/stand-alone-documentaion/round-corners/round-corners.stories.mdx
  src/storybook/stand-alone-documentaion/round-corners/round-corners.stories.module.scss
  src/storybook/stand-alone-documentaion/round-corners/rounded-corner/rounded-corner.jsx
  src/storybook/stand-alone-documentaion/round-corners/rounded-corner/rounded-corner.module.scss
  src/storybook/stand-alone-documentaion/shadow/shadow.stories.mdx
Labels: PR: Documentation 📖

#412 Stories/orr/icons responsivelist virtualized list
  .gitignore
  .storybook/addons.js
  .storybook/manager-head.html
  .storybook/preview-head.html
  __mocks__/fileMock.js
  __mocks__/svgMock.js
  jest.config.js
  jest.init.js
  package-lock.json
  package.json
  src/components/AttentionBox/AttentionBox.jsx
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/AvatarBadge.jsx
  src/components/Avatar/AvatarContent.jsx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Icon/CustomSvgIcon.jsx
  src/components/Icon/__stories__/Icon.stories.mdx
  src/components/Icon/__stories__/Icon.stories.scss
  src/components/Icon/__stories__/icon.stories.helperComponents.jsx
  src/components/Icon/__stories__/icon.stories.js
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/List/List.jsx
  src/components/List/__stories__/List.stories.mdx
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/ListItemIcon/__stories__/ListItemIcon.stories.mdx
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
  src/components/MenuButton/__stories__/menuButton.stories.js
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.scss
  src/components/ResponsiveList/__stories__/ResponsiveList.stories.mdx
  src/components/ResponsiveList/__stories__/ResponsiveList.stories.scss
  src/components/ResponsiveList/__stories__/responsiveList.stories.js
  src/components/ResponsiveList/__stories__/responsiveListStoriesComponents.jsx
  src/components/ResponsiveList/__stories__/responsiveListStory.scss
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/components/Tipseen/TipseenImage.jsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/VirtualizedList/VirtualizedList.jsx
  src/components/VirtualizedList/__stories__/VirtualizedList.stories.mdx
  src/components/VirtualizedList/__stories__/virtualizedList.components.js
  src/components/VirtualizedList/__stories__/virtualizedList.stories.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/icon-button-description.jsx
  src/storybook/components/related-components/descriptions/menu-button-description.jsx
  src/storybook/stand-alone-documentaion/welcome/welcome-header/welcome-header.jsx
Labels: documentation, PR: Documentation 📖

#415 Fix documentation welcome page links and fix content mistakes
  src/components/Button/__stories__/button.stories.mdx
  src/components/Icon/__stories__/Icon.stories.mdx
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.jsx
  src/storybook/stand-alone-documentaion/welcome/welcome.stories.mdx
Labels: PR: Documentation 📖

#416 Tree-shake the library
  package.json
Labels: PR: Bugfix 🐛

#418 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: PR: Documentation 📖

#417 change className props to consist naming
  package-lock.json
  src/components/ButtonGroup/ButtonGroup.jsx
  src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.js
  src/components/Link/Link.jsx
  src/components/Link/__tests__/__snapshots__/link-snapshot-tests.jest.js.snap
  src/components/Link/__tests__/link-snapshot-tests.jest.js
  src/components/RadioButton/RadioButton.jsx
  src/components/Toggle/__tests__/toggle-snapshot-tests.jest.js
Labels: PR: Bugfix 🐛

#404 added support for date and date time for input
  src/components/TextField/TextField.jsx
  src/components/TextField/TextFieldConstants.js
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/textField-snapshot-tests.jest.js
Labels: PR: Bugfix 🐛

#420 Fix virtualized list scrollbar visible issue
  src/components/VirtualizedList/VirtualizedList.jsx
  src/components/VirtualizedList/virtualized-list-service.js
Labels: PR: Bugfix 🐛
