Repository mondaycom/vibe, pull requests merged in 2021-11, with the labels that each got.

#314 amitha/feature/combobox-no-results
  src/components/Combobox/Combobox.jsx
Labels: PR: New Feature 🕹

#315 add autoFocus to dropdown
  src/components/Dropdown/Dropdown.jsx
Labels: PR: New Feature 🕹

#313 Added onClick callback support for AccordionItem
  src/components/Accordion/Accordion/Accordion.jsx
  src/components/Accordion/Accordion/Accordion.scss
  src/components/Accordion/AccordionItem/AccordionItem.jsx
  src/components/Accordion/AccordionItem/__stories__/accordionItem.stories.js
  src/components/ExpandCollapse/ExpandCollapse.scss
Labels: PR: Bugfix 🐛

#318 Combobox sticky categories and search width
  babel.config.js
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/Combobox.scss
  src/components/Combobox/__stories__/combobox.stories.js
  src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
Labels: PR: Bugfix 🐛

#317 Plop/hadas/tests
  plop/component/component-test-jest.txt
  plop/component/index.js
  plop/general/component-snapshot-tests-jest.txt
  plop/general/component-tests-jest.txt
  plop/tests/index.js
  plopfile.js
Labels: PR: Documentation 📖

#319 Fix typo
  src/components/DialogContentContainer/DialogContentContainer.scss
  src/styles/themes.scss
Labels: PR: Bugfix 🐛

#322 amitha/feature/dialog-is-reference-hidden
  src/components/Dialog/Dialog.jsx
  src/components/Dialog/DialogContent/DialogContent.jsx
  src/components/Dialog/DialogContent/DialogContent.scss
  src/components/Tipseen/__tests__/__snapshots__/tipseen.jest.js.snap
Labels: PR: Bugfix 🐛

#323 Add support in tipseen component for: submitButtonText & submitButtonOnClick & dismissButtonText & dismissButtonOnClick & hideWhenReferenceHidden
  src/components/Tipseen/Tipseen.jsx
  src/components/Tipseen/TipseenContent.jsx
  src/components/Tipseen/__stories__/tipseen.stories.js
  src/components/Tipseen/__tests__/__snapshots__/tipseenContent.jest.js.snap
  src/components/Tipseen/__tests__/tipseenContent.jest.js
  src/components/Tooltip/Tooltip.jsx
  src/helpers/backwardCompatibilityForProperties.js
Labels: PR: New Feature 🕹

#321 Adding tooltip content option to combobox item
  src/components/Combobox/__stories__/combobox.stories.js
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
Labels: PR: New Feature 🕹

#327 editable input focus in animation frame
  src/components/EditableInput/EditableInput.jsx
Labels: PR: Bugfix 🐛

#330 Fix button initial loading state
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/Button/__stories__/button.stories.js
Labels: PR: Bugfix 🐛

#331 successIconSize property to determine function success icon size
  src/components/Button/Button.jsx
Labels: PR: Bugfix 🐛

#332 Combobox: fix the space between the search box to the first option
  src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
Labels: PR: Bugfix 🐛

#333 amitha/fix/text-field-focus-animation-in-dialog
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
  src/components/TextField/TextField.jsx
Labels: PR: Bugfix 🐛

#335 Tooltip add show/hide events
  src/components/Tooltip/Tooltip.jsx
  src/components/Tooltip/__tests__/tooltip.jest.js
Labels: PR: New Feature 🕹

#309 change fixed eslint to error
  .eslintrc.json
Labels: PR: Internal 🏠

#328 Add support on className to Checkbox&AttentionBox instead of componentClassName
  src/components/AttentionBox/AttentionBox.jsx
  src/components/AttentionBox/__stories__/attentionBox.stories.js
  src/components/AttentionBox/__tests__/attentionBox.jest.js
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__stories__/checkbox.stories.js
  src/components/Checkbox/__tests__/checkbox.jest.js
Labels: PR: Bugfix 🐛

#310 stylelint rules
  .github/workflows/test-workflow.yml
  .stylelintrc.json
  package-lock.json
  package.json
  src/components/Dropdown/components/singleValue/singleValue.scss
  src/components/FormattedNumber/FormattedNumber.scss
  src/components/Tabs/TabsContext/TabsContext.scss
  src/components/TextField/TextField.scss
  src/components/Toggle/__stories__/toggle.stories.scss
  src/general-stories/global-design/GlobalSettingGeneralComponent.scss
Labels: PR: Internal 🏠

#334 add links support to stories
  .storybook/preview.js
  src/storybook/components/component-rule/component-rule.jsx
  src/storybook/components/component-rules/component-rules.jsx
  src/storybook/components/index.jsx
  src/storybook/components/link/link.jsx
  src/storybook/components/link/link.scss
  src/storybook/components/styles/typography.scss
  src/storybook/components/usage-guidelines/usage-guidelines.jsx
Labels: PR: New Feature 🕹

#329 Leany labs/storybook 1 (#1)
  src/components/Avatar/__stories__/assets/femaleIcon.png
  src/components/Avatar/__stories__/assets/guest.svg
  src/components/Avatar/__stories__/assets/home.svg
  src/components/Avatar/__stories__/assets/index.js
  src/components/Avatar/__stories__/assets/maleIcon.png
  src/components/Avatar/__stories__/assets/minus.svg
  src/components/Avatar/__stories__/assets/owner.svg
  src/components/Avatar/__stories__/assets/person1.png
  src/components/Avatar/__stories__/assets/person2.png
  src/components/Avatar/__stories__/assets/person3.png
  src/components/Avatar/__stories__/avatar.stories.js
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.scss
  src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.js.snap
  src/components/Avatar/__tests__/__snapshots__/avatar.jest.js.snap
  src/components/Avatar/__tests__/avatar-snapshot-tests.jest.js
  src/components/Avatar/__tests__/avatar.jest.js
  src/components/Button/__stories__/button.stories.mdx
  src/components/Chips/Chips.jsx
  src/components/Chips/__stories__/assets/person1.png
  src/components/Chips/__stories__/chips.stories.js
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__stories__/chips.stories.scss
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/Chips/__tests__/__snapshots__/chips.jest.js.snap
  src/components/Chips/__tests__/chips-snapshot-tests.jest.js
  src/components/Chips/__tests__/chips-tests.jest.js
  src/components/Chips/__tests__/chips.jest.js
  src/components/Toggle/__stories__/toggle.stories.js
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.scss
  src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
  src/components/Toggle/__tests__/toggle-snapshot-tests.jest.js
  src/components/Toggle/__tests__/toggle-tests.jest.js
  src/components/Toggle/__tests__/toggle.jest.js
  src/components/Tooltip/__stories__/TooltipContent.jsx
  src/general-stories/colors/colors-vars-map.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/button-group-description.jsx
  src/storybook/components/related-components/descriptions/checkbox-description.jsx
  src/storybook/components/related-components/descriptions/chips-description.jsx
  src/storybook/components/related-components/descriptions/counter-description.jsx
  src/storybook/components/related-components/descriptions/label-description.jsx
  src/storybook/components/related-components/descriptions/radio-button-description.jsx
  src/storybook/components/related-components/descriptions/tooltip-description.jsx
Labels: PR: Documentation 📖

#326 Chromatic (storybook 6.4)
  .github/workflows/chromatic.yml
  .storybook/preview-head.html
  .storybook/preview.js
  package-lock.json
  package.json
  plop/hooks/dummy-component.txt
  plop/hooks/hook-story.txt
  plop/hooks/index.js
  plopfile.js
  src/components/Button/Button.scss
  src/components/Button/__stories__/button.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown.jest.js.snap
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/IconButton.scss
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.scss
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
  src/components/IconButton/__tests__/__snapshots__/iconButton.jest.js.snap
  src/components/IconButton/__tests__/iconButton-snapshot-tests.jest.js
  src/components/IconButton/__tests__/iconButton-tests.jest.js
  src/components/IconButton/__tests__/iconButton.jest.js
  src/components/IconButton/services/IconButton-helpers.js
  src/constants/sizes.js
  src/general-stories/Changelog/changelog.stories.mdx
  src/general-stories/global-design/globalDesign.stories.mdx
  src/general-stories/typography/typography.stories.mdx
  src/hooks/__stories__/general-hooks-stories.scss
  src/hooks/__stories__/useClickOutside.stories.mdx
  src/hooks/__stories__/useEventListener.stories.mdx
  src/hooks/__stories__/useTimeout.stories.mdx
  src/hooks/useTimeout.js
  src/hooksDummyComponents/UseClickOutSide.jsx
  src/hooksDummyComponents/UseEventListener.jsx
  src/hooksDummyComponents/UseTimeout.jsx
  src/storybook/components/doc-footer/doc-footer.scss
  src/storybook/components/link-component/link-component.jsx
  src/storybook/components/tip/tip.jsx
  src/storybook/components/usage-guidelines/usage-guideline.scss
  src/storybook/components/usage-guidelines/usage-guidelines.jsx
  src/styles/global-css-settings.scss
Labels: PR: New Feature 🕹

#338 fix spacing in links
  src/storybook/components/link/link.jsx
  src/storybook/components/link/link.scss
Labels: PR: Bugfix 🐛

#339 amitha/fix/combobox-disable-active-scroll-without-categories
  src/components/Combobox/Combobox.jsx
Labels: PR: Bugfix 🐛

#337 Storybook/hadas/welcome
  src/storybook/components/anchor-list-item/anchor-list-item.scss
  src/storybook/components/component-name/component-name.jsx
  src/storybook/components/component-name/component-name.scss
  src/storybook/components/component-rule/component-rule.scss
  src/storybook/components/component-rules/component-rules.scss
  src/storybook/components/doc-footer/doc-footer.scss
  src/storybook/components/information-box/information-box.jsx
  src/storybook/components/information-box/information-box.scss
  src/storybook/components/link/link.jsx
  src/storybook/components/link/link.scss
  src/storybook/components/related-component/related-component.jsx
  src/storybook/components/related-component/related-component.scss
  src/storybook/components/related-components/related-components.scss
  src/storybook/components/section-name/section-name.scss
  src/storybook/components/tip/tip.scss
  src/storybook/components/title/title.scss
  src/storybook/components/usage-guidelines/usage-guideline.scss
  src/storybook/stand-alone-documentaion/other-contributors-list/other-contributors-list.jsx
  src/storybook/stand-alone-documentaion/other-contributors-list/other-contributors-list.scss
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.jsx
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
  src/storybook/stand-alone-documentaion/welcome/ability-description/ability-description.jsx
  src/storybook/stand-alone-documentaion/welcome/ability-description/ability-description.scss
  src/storybook/stand-alone-documentaion/welcome/assets/Evgeniy.png
  src/storybook/stand-alone-documentaion/welcome/assets/Hadas.png
  src/storybook/stand-alone-documentaion/welcome/assets/Moshe.png
  src/storybook/stand-alone-documentaion/welcome/assets/Orr.png
  src/storybook/stand-alone-documentaion/welcome/assets/Rotem.png
  src/storybook/stand-alone-documentaion/welcome/assets/Sahar.png
  src/storybook/stand-alone-documentaion/welcome/assets/clarity.png
  src/storybook/stand-alone-documentaion/welcome/assets/components.png
  src/storybook/stand-alone-documentaion/welcome/assets/delight.png
  src/storybook/stand-alone-documentaion/welcome/assets/foundations.png
  src/storybook/stand-alone-documentaion/welcome/assets/getting-started.png
  src/storybook/stand-alone-documentaion/welcome/assets/header-banner.png
  src/storybook/stand-alone-documentaion/welcome/assets/index.js
  src/storybook/stand-alone-documentaion/welcome/assets/path.png
  src/storybook/stand-alone-documentaion/welcome/assets/speed.png
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.jsx
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.scss
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
  src/storybook/stand-alone-documentaion/welcome/intro/intro.jsx
  src/storybook/stand-alone-documentaion/welcome/intro/intro.scss
  src/storybook/stand-alone-documentaion/welcome/principle/principle.jsx
  src/storybook/stand-alone-documentaion/welcome/principle/principle.scss
  src/storybook/stand-alone-documentaion/welcome/principles/principles.jsx
  src/storybook/stand-alone-documentaion/welcome/principles/principles.scss
  src/storybook/stand-alone-documentaion/welcome/welcome-header/welcome-header.jsx
  src/storybook/stand-alone-documentaion/welcome/welcome-header/welcome-header.scss
  src/storybook/stand-alone-documentaion/welcome/welcome.stories.mdx
  src/storybook/styles/content-spacing.scss
  src/storybook/styles/typography.scss
Labels: PR: Documentation 📖

#341 fix: callback on mount when should show on mount
  src/components/Dialog/Dialog.jsx
Labels: PR: Bugfix 🐛

#344 fix: safari useReszieObserver
  src/hooks/useResizeObserver.js
Labels: PR: Bugfix 🐛

#345 Fix typo in useForceUpdate
  src/hooks/useForceUpdate.js
Labels: PR: Documentation 📖

#343 Fix fonts and spacing according to rotem notes
  .storybook/preview.js
  src/storybook/components/component-rules/component-rules.scss
  src/storybook/components/doc-footer/doc-footer.scss
  src/storybook/components/index.jsx
  src/storybook/components/information-box/information-box.scss
  src/storybook/components/link/link.scss
  src/storybook/components/paragraph/paragraph.jsx
  src/storybook/components/paragraph/paragraph.scss
  src/storybook/components/related-component/related-component.scss
  src/storybook/components/related-components/descriptions/tooltip-description.jsx
  src/storybook/components/related-components/related-components.scss
  src/storybook/components/section-name/section-name.scss
  src/storybook/components/title/title.scss
  src/storybook/components/usage-guidelines/usage-guideline.scss
  src/storybook/stand-alone-documentaion/other-contributors-list/other-contributors-list.jsx
  src/storybook/stand-alone-documentaion/other-contributors-list/other-contributors-list.scss
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
  src/storybook/stand-alone-documentaion/welcome/ability-description/ability-description.scss
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.scss
  src/storybook/stand-alone-documentaion/welcome/principle/principle.scss
  src/storybook/stand-alone-documentaion/welcome/welcome-header/welcome-header.scss
  src/storybook/styles/content-spacing.scss
  src/storybook/styles/typography.scss
Labels: PR: Documentation 📖

#346 Rename ButtonContstants file to ButtonConstants file
  src/components/Button/Button.jsx
  src/components/Button/ButtonConstants.js
Labels: PR: Bugfix 🐛

#349 Prevent editable heading from being empty
  src/components/EditableHeading/EditableHeading.jsx
Labels: PR: Bugfix 🐛

#350 Fix heading ellipsis issue with 1 line
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/Heading/Heading.jsx
  src/components/Heading/Heading.scss
  src/components/Heading/__tests__/__snapshots__/heading.jest.js.snap
  src/styles/typography.scss
Labels: PR: Bugfix 🐛

#348 add aria label support for checkbox
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__tests__/__snapshots__/checkbox.jest.js.snap
  src/components/Checkbox/__tests__/checkbox.jest.js
Labels: PR: Bugfix 🐛

#325 docs : improve documentation for extra styles in <dropdown>
  src/components/Dropdown/Dropdown.jsx
Labels: PR: Documentation 📖

#342 LeanyLabs: storybooks & tests (Label, Checkbox, Radio button)
  build-storybook.log
  package-lock.json
  src/components/Button/__stories__/button.stories.js
  src/components/Button/__stories__/button.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.js
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.renderCheckboxes.js
  src/components/Checkbox/__stories__/checkbox.stories.scss
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.js.snap
  src/components/Checkbox/__tests__/__snapshots__/checkbox.jest.js.snap
  src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.js
  src/components/Checkbox/__tests__/checkbox-tests.jest.js
  src/components/Checkbox/__tests__/checkbox.jest.js
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__tests__/chips-tests.jest.js
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.js
  src/components/Label/__stories__/label.stories.mdx
  src/components/Label/__stories__/label.stories.scss
  src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.js.snap
  src/components/Label/__tests__/label-snapshot-tests.jest.js
  src/components/RadioButton/__stories__/RadioButtonStoryLine.jsx
  src/components/RadioButton/__stories__/radioButton.stories.js
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.scss
  src/components/RadioButton/__tests__/__snapshots__/radioButton-snapshot-tests.jest.js.snap
  src/components/RadioButton/__tests__/__snapshots__/radioButton.jest.js.snap
  src/components/RadioButton/__tests__/radioButton-snapshot-tests.jest.js
  src/components/RadioButton/__tests__/radioButton-tests.jest.js
  src/components/RadioButton/__tests__/radioButton.jest.js
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Toggle/__tests__/toggle-snapshot-tests.jest.js
  src/components/Toggle/__tests__/toggle-tests.jest.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/dropdown-description.jsx
  src/storybook/components/related-components/descriptions/toggle-description.jsx
Labels: PR: Documentation 📖

#358 fix: export Icon component
  src/components/index.js
Labels: PR: Bugfix 🐛

#361 support onclick without navigation
  src/components/Link/Link.jsx
  src/components/Link/__stories__/link-story.scss
  src/components/Link/__stories__/link.stories.js
Labels: PR: New Feature 🕹

#366 pass event to onclick
  src/components/Link/Link.jsx
Labels: PR: Bugfix 🐛
