Repository mondaycom/vibe, pull requests merged in 2022-07, with the labels that each got.

#732 adding leftIcon and leftAvatar to dropdown chips
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
Labels: PR: New Feature 🕹

#723 Add css module support for chips component
  src/components/Chips/Chips.jsx
  src/components/Chips/Chips.module.scss
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#733 AvatarGroup component export
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  webpack/published-components.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#706 Feature/sergeyro/avatar group a11y
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.scss
  src/components/AvatarGroup/AvatarGroup.jsx
  src/components/AvatarGroup/AvatarGroup.module.scss
  src/components/AvatarGroup/AvatarGroupCounter.jsx
  src/components/AvatarGroup/AvatarGroupCounter.module.scss
  src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.jsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContent.jsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContent.module.scss
  src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.jsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.module.scss
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.js
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.module.scss
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/components/Clickable/ClickableWrapper.jsx
  src/components/Menu/MenuItem/AvatarMenuItem.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
  src/hooks/useKeyEvent/index.js
  src/styles/states.scss
Labels: PR: New Feature 🕹

#735 IconButton: added wrapperClassName prop
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/IconButton.modules.scss
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#737 Feature/yonatanari/wellcome page responsive without media
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
  src/storybook/stand-alone-documentaion/welcome/principles/principles.scss
  src/storybook/stand-alone-documentaion/welcome/welcome-header/welcome-header.scss
  src/styles/global-css-settings.scss
Labels: PR: New Feature 🕹

#743 Feat: Add prop set the tabindex for RadioButton.jsx rendered children
  src/components/RadioButton/RadioButton.jsx
Labels: accessibility

#744 Icon button fix and link alignment
  src/components/IconButton/IconButton.jsx
  src/components/Link/Link.jsx
  src/components/Link/Link.scss
  src/components/Link/__stories__/Link.stories.mdx
  src/components/TextWithHighlight/TextWithHighlight.jsx
Labels: PR: New Feature 🕹

#748 Clickable: ariaExpanded prop added
  src/components/Clickable/Clickable.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#749 Support set use active descendant list visual focus from outside
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
  src/hooks/useActiveDescendantListFocus/index.js
Labels: PR: New Feature 🕹

#752 Feature/yonatan ari/storybook repsoinsive tweaks
  src/storybook/components/component-rule/component-rule.scss
  src/storybook/components/component-rules/component-rules.scss
  src/storybook/components/related-components/related-components.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-levels.scss
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-component/spacing-component.scss
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-sizes.scss
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
  src/storybook/stand-alone-documentaion/welcome/principles/principles.scss
  src/styles/global-css-settings.scss
Labels: PR: New Feature 🕹

#687 Feature/yonatanari/box component
  package-lock.json
  package.json
  src/components/Box/Box.jsx
  src/components/Box/Box.module.scss
  src/components/Box/BoxConstants.js
  src/components/Box/__stories__/Box.stories.mdx
  src/components/Box/__stories__/Box.stories.module.scss
  src/components/Box/__tests__/__snapshots__/box-snapshot-tests.jest.js.snap
  src/components/Box/__tests__/box-snapshot-tests.jest.js
  src/components/index.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/dialog-content-container.jsx
  src/storybook/components/related-components/descriptions/divider.jsx
  src/storybook/components/related-components/descriptions/flex.jsx
  src/styles/utilities/_utilities-settings.scss
Labels: PR: New Feature 🕹

#712 Feature/yonatanari/motion page
  src/storybook/components/component-rule/component-rule.scss
  src/storybook/components/information-box/information-box.jsx
  src/storybook/components/token-table/token-table-head-item.jsx
  src/storybook/components/token-table/token-table-row.jsx
  src/storybook/components/token-table/token-table.jsx
  src/storybook/components/token-table/token-table.module.scss
  src/storybook/stand-alone-documentaion/motion/animation-information-box/animation-information-box.jsx
  src/storybook/stand-alone-documentaion/motion/animation-information-box/animation-information-box.module.scss
  src/storybook/stand-alone-documentaion/motion/animation-overviews/animation-overviews.jsx
  src/storybook/stand-alone-documentaion/motion/animation-overviews/animation-overviews.module.scss
  src/storybook/stand-alone-documentaion/motion/animation-types/animation-types.jsx
  src/storybook/stand-alone-documentaion/motion/animation-types/animation-types.module.scss
  src/storybook/stand-alone-documentaion/motion/assets/consistency-do.mp4
  src/storybook/stand-alone-documentaion/motion/assets/consistency-dont.mp4
  src/storybook/stand-alone-documentaion/motion/assets/delight.mp4
  src/storybook/stand-alone-documentaion/motion/assets/dont-delay-user-do.mp4
  src/storybook/stand-alone-documentaion/motion/assets/dont-delay-user-dont.mp4
  src/storybook/stand-alone-documentaion/motion/assets/duration-expressive-long.mp4
  src/storybook/stand-alone-documentaion/motion/assets/duration-expressive-short.mp4
  src/storybook/stand-alone-documentaion/motion/assets/duration-productive-long.mp4
  src/storybook/stand-alone-documentaion/motion/assets/duration-productive-medium.mp4
  src/storybook/stand-alone-documentaion/motion/assets/duration-productive-short.mp4
  src/storybook/stand-alone-documentaion/motion/assets/easing-do.mp4
  src/storybook/stand-alone-documentaion/motion/assets/easing-dont.mp4
  src/storybook/stand-alone-documentaion/motion/assets/emphesize-elastic-easing.mp4
  src/storybook/stand-alone-documentaion/motion/assets/enter-decelerated-easing.mp4
  src/storybook/stand-alone-documentaion/motion/assets/exit-accelerated-easing.mp4
  src/storybook/stand-alone-documentaion/motion/assets/feedback.mp4
  src/storybook/stand-alone-documentaion/motion/assets/focus.mp4
  src/storybook/stand-alone-documentaion/motion/assets/index.js
  src/storybook/stand-alone-documentaion/motion/assets/orientation.mp4
  src/storybook/stand-alone-documentaion/motion/assets/simplicity-do.mp4
  src/storybook/stand-alone-documentaion/motion/assets/simplicity-dont.mp4
  src/storybook/stand-alone-documentaion/motion/assets/transition-standard-easing.mp4
  src/storybook/stand-alone-documentaion/motion/assets/type-css.mp4
  src/storybook/stand-alone-documentaion/motion/assets/type-empty.mp4
  src/storybook/stand-alone-documentaion/motion/assets/type-like.mp4
  src/storybook/stand-alone-documentaion/motion/assets/type-status.mp4
  src/storybook/stand-alone-documentaion/motion/duration-expressive-tokens/duaration-expressive-tokens.module.scss
  src/storybook/stand-alone-documentaion/motion/duration-expressive-tokens/duration-expressive-tokens.jsx
  src/storybook/stand-alone-documentaion/motion/duration-productive-tokens/duaration-productive-tokens.module.scss
  src/storybook/stand-alone-documentaion/motion/duration-productive-tokens/duration-productive-tokens.jsx
  src/storybook/stand-alone-documentaion/motion/duration-token-table/duration-token-table.jsx
  src/storybook/stand-alone-documentaion/motion/easing-overview/easing-overview.jsx
  src/storybook/stand-alone-documentaion/motion/easing-overview/easing-overview.module.scss
  src/storybook/stand-alone-documentaion/motion/easing-overviews/easing-overviews.jsx
  src/storybook/stand-alone-documentaion/motion/easing-overviews/easing-overviews.module.scss
  src/storybook/stand-alone-documentaion/motion/easing-token-table/easing-token-table.jsx
  src/storybook/stand-alone-documentaion/motion/motion.stories.mdx
  src/storybook/stand-alone-documentaion/motion/token-Information-box/token-information-box.jsx
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
  src/styles/global-css-settings.scss
Labels: documentation, PR: Documentation 📖

#753 Navigate in list with keyboard.
  src/components/List/List.jsx
  src/components/List/__tests__/__snapshots__/list.jest.js.snap
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/__tests__/__snapshots__/listItem.jest.js.snap
  src/components/ListTitle/ListTitle.jsx
  src/constants/KeyCodes.js
Labels: PR: New Feature 🕹

#758 Add Poppins font-family to h1 heading
  .storybook/preview-head.html
  src/components/Heading/Heading.jsx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/styles/typography.scss
Labels: PR: New Feature 🕹

#767 Box: added to published-components
  webpack/published-components.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#765 Enable brandFont prop for heading within editable heading.
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/Heading/Heading.jsx
Labels: PR: New Feature 🕹

#750 Feature/yonatanari/change logo href
  .storybook/addons.js
Labels: enhancement, PR: New Feature 🕹

#770 Manually update monday-ui-style version to 0.1.132
  package-lock.json
  package.json
Labels: PR: unreviewed, PR: New Feature 🕹

#775 Fix button group css specificity
  src/components/ButtonGroup/ButtonGroup.scss
Labels: PR: Bugfix 🐛

#777 Bug/hadas/attention box close
  src/components/AttentionBox/AttentionBox.scss
Labels: PR: Bugfix 🐛

#759 Allow defaultVisualFocusItemIndex on use useActiveDescendantListFocus and combobox
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
  src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.jest.js
  src/hooks/useActiveDescendantListFocus/index.js
  src/hooks/useActiveDescendantListFocus/useActiveDescendantListFocusHelpers.js
  src/hooks/useActiveDescendantListFocus/useActiveDescendantListFocusHooks.js
  src/hooks/useListenFocusTriggers/index.js
Labels: PR: New Feature 🕹

#787 add validation
  src/components/List/List.jsx
Labels: PR: Bugfix 🐛

#736 scroll combobox fix
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.module.scss
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
Labels: PR: Bugfix 🐛

#776 add exports to package.json + build icons esm file
  package.json
  scripts/build-esm.js
Labels: PR: Internal 🏠

#791 removed hooks alias usage
  src/hooks/useActiveDescendantListFocus/index.js
  src/hooks/useActiveDescendantListFocus/useActiveDescendantListFocusHooks.js
Labels: PR: Bugfix 🐛

#771 Tipseen: css modules
  src/components/Tipseen/Tipseen.jsx
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tipseen/TipseenBasicContent.jsx
  src/components/Tipseen/TipseenBasicContent.module.scss
  src/components/Tipseen/TipseenContent.jsx
  src/components/Tipseen/TipseenContent.module.scss
  src/components/Tipseen/TipseenImage.jsx
  src/components/Tipseen/TipseenImage.module.scss
  src/components/Tipseen/TipseenTitle.jsx
  src/components/Tipseen/TipseenTitle.module.scss
  src/components/Tipseen/TipseenWizard.jsx
  src/components/Tipseen/TipseenWizard.module.scss
  src/components/Tipseen/TipseenWizard.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#793 Tipseen: fix styleint errors
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tipseen/TipseenBasicContent.module.scss
  src/components/Tipseen/TipseenContent.module.scss
  src/components/Tipseen/TipseenImage.module.scss
  src/components/Tipseen/TipseenTitle.module.scss
  src/components/Tipseen/TipseenWizard.module.scss
Labels: PR: Internal 🏠
