Repository mondaycom/vibe, pull requests merged in 2022-09, with the labels that each got.

#839 Feature/sergeyro/accordion collapse icon not clickable
  src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
  src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
  src/components/ExpandCollapse/ExpandCollapse.jsx
  src/components/ExpandCollapse/__tests__/__snapshots__/expandCollapse.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#845 Feature/sergeyro/disable styleint rule for global pseudo class
  .stylelintrc.json
  src/components/Chips/Chips.module.scss
Labels: PR: unreviewed, PR: Internal 🏠

#852 Add Horizontal virtualized list
  src/components/VirtualizedGrid/VirtualizedGrid.jsx
  src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.js
  src/components/VirtualizedList/VirtualizedList.jsx
  src/components/VirtualizedList/__stories__/VirtualizedList.stories.mdx
  src/components/VirtualizedList/__stories__/virtualizedList.components.js
  src/services/virtualized-service.js
Labels: PR: New Feature 🕹

#854 add support for menus inside a container which using transform function
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/components/menu/menu.jsx
  src/components/Dropdown/components/menu/menu.scss
Labels: PR: Bugfix 🐛

#794 Convert button component to typescript & project configurations
  jest.config.js
  package-lock.json
  package.json
  scripts/build-esm.js
  scripts/build-exports.js
  scripts/build-ts-index.js
  scripts/build-utils.js
  src/components/AlertBanner/AlertBannerButton/AlertBannerButton.tsx
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AlertBanner/__tests__/AlertBanner-snapshots.jest.js
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.js.snap
  src/components/Button/Button.tsx
  src/components/Button/ButtonConstants.js
  src/components/Button/ButtonConstants.ts
  src/components/Button/__stories__/button.stories.mdx
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/Button/__tests__/button-snapshot-tests.jest.js
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.js.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Icon/__tests__/all-icons-tests.jest.js
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/Slider/__tests__/slider-non-ranged-tests.jest.js
  src/components/Slider/__tests__/slider-ranged-tests.jest.js
  src/components/Slider/__tests__/slider-snapshot-tests.jest.js
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Toast/ToastButton/ToastButton.jsx
  src/components/Toast/ToastButton/ToastButton.tsx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/constants/sizes.js
  src/constants/sizes.ts
  src/storybook/functions/create-component-story.js
  src/utils/icon-utils.js
  src/utils/jest-utils.js
  tsconfig.json
  webpack.config.js
  webpack/published-components.js
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#856 feat(checkbox): add ability to render component without label
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.js.snap
  src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.js
Labels: PR: New Feature 🕹

#861 Fix menu button ref
  src/components/MenuButton/MenuButton.jsx
Labels: PR: New Feature 🕹

#859 Feature/sergeyro/menu button icon size unify
  src/components/MenuButton/MenuButton.jsx
  src/components/MenuButton/__tests__/__snapshots__/menuButton.jest.js.snap
  src/components/ResponsiveList/__tests__/__snapshots__/responsiveList.jest.js.snap
  src/constants/sizes.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#864 Chip colors in dropdown with multi support
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/Dropdown/dropdown-constants.js
Labels: PR: New Feature 🕹

#866 Fixing Chips import by changing to relative import
  src/components/Dropdown/dropdown-constants.js
Labels: PR: Bugfix 🐛

#858 Css modules typescript infra via 'typescript-plugin-css-modules' + eslint ts specification
  .eslintrc.js
  package-lock.json
  package.json
  src/components/Button/Button.tsx
  src/components/Switch/index.js
  src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.interactions.js
  src/storybook/functions/memory-stats/memory-stats-lib.js
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
  src/utils/icon-utils.js
  tsconfig.json
  types/styles.d.ts
Labels: PR: unreviewed, PR: Internal 🏠

#857 Convert icon component and related code to js
  .eslintrc.js
  src/StoryBookComponents/StoryLink/StoryLine.jsx
  src/StoryBookComponents/StoryLink/StoryLine.scss
  src/components/Avatar/AvatarBadge.jsx
  src/components/Avatar/__tests__/avatar-snapshot-tests.jest.js
  src/components/Button/Button.tsx
  src/components/Button/__tests__/button-snapshot-tests.jest.js
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
  src/components/Icon/FontIcon/FontIcon.tsx
  src/components/Icon/Icon.jsx
  src/components/Icon/Icon.tsx
  src/components/Icon/IconConstants.js
  src/components/Icon/IconConstants.ts
  src/components/Icon/__stories__/Icon.stories.mdx
  src/components/Icon/__tests__/all-icons-tests.jest.js
  src/components/Icon/__tests__/all-icons-tests.jest.ts
  src/components/Icon/hooks/useIconProps.tsx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/index.js
  src/published-components.js
  src/types/VibeComponent.ts
  src/types/VibeComponentProps.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#870 Feature/sergeyro/ts infra css modules
  .eslintrc.js
  src/helpers/typesciptCssModulesHelper.ts
  tsconfig.json
Labels: PR: unreviewed, PR: Internal 🏠

#874 fix icon types import
  src/components/AttentionBox/AttentionBox.jsx
Labels: PR: Bugfix 🐛

#872 add readme for typescript migration process
  TYPESCRIPT_MIGRATION.md
Labels: PR: Documentation 📖

#873 add on hover to list item
  src/components/ListItem/ListItem.jsx
Labels: PR: New Feature 🕹

#876 Fix for virtualized list items
  src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/__tests__/__snapshots__/listItem.jest.js.snap
  src/components/ListTitle/ListTitle.jsx
Labels: PR: Bugfix 🐛

#880 Fix Virtualized list items
  src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#883 fix externals issue
  TYPESCRIPT_MIGRATION.md
  package-lock.json
  package.json
  src/helpers/screenReaderAccessHelper.ts
  src/hooks/useDebounceEvent/index.ts
  src/hooks/useElementsOverflowingIndex.ts
  src/hooks/useFullKeyboardListeners.ts
  src/hooks/useResizeObserver.ts
  src/hooks/useStyle.ts
  src/hooks/useThrottledCallback.ts
  src/hooks/useTimeout/index.ts
  webpack.config.js
Labels: PR: New Feature 🕹

#882 Feature/refactor components motion keyframes
  src/components/Chips/Chips.module.scss
  src/components/Counter/Counter.scss
  src/components/Label/Label.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/Toast/Toast.scss
  src/components/Toast/__stories__/toast.stories.scss
  src/styles/_keyframes.scss
  src/styles/keyframes/pop/_pop-elastic.scss
  src/styles/keyframes/pop/_pop-in-elastic-bold.scss
  src/styles/keyframes/pop/_pop-in-elastic.scss
  src/styles/keyframes/pop/_pop-in-emphasized.scss
  src/styles/keyframes/pop/_pop-in-from-trigger.scss
  src/styles/keyframes/pop/_pop-in.scss
  src/styles/keyframes/pop/_pop-out-from-trigger.scss
  src/styles/keyframes/slide/_slide-in-elastic.scss
  src/styles/keyframes/slide/_slide-in.scss
  src/styles/keyframes/slide/_slide-out.scss
  src/styles/keyframes/spin/_spin-in-emphasized.scss
Labels: PR: New Feature 🕹

#886 Tooltip: increase specifity of monday-style-arrow-${theme} classes
  src/components/Tooltip/Tooltip.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#887 fix import path from absolute to relative.
  src/styles/_keyframes.scss
Labels: PR: Bugfix 🐛

#696 Modal
  package-lock.json
  package.json
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/__stories__/Modal.stories.scss
  src/components/Modal/__stories__/helpers.js
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/modal-snapshot-tests.jest.js
  src/components/Modal/__tests__/modal-tests.jest.js
  src/components/Modal/a11yDialog.jsx
  src/components/Modal/useAnimationProps.js
  src/components/Modal/useBodyScrollLock.js
  src/components/Modal/useShowHideModal.js
  src/components/ModalContent/ModalContent.jsx
  src/components/ModalContent/ModalContent.module.scss
  src/components/ModalContent/__tests__/__snapshots__/modalContent-snapshot-tests.jest.js.snap
  src/components/ModalContent/__tests__/modalContent-snapshot-tests.jest.js
  src/components/ModalFooter/ModalFooter.jsx
  src/components/ModalFooter/ModalFooter.module.scss
  src/components/ModalFooter/__tests__/__snapshots__/modalFooter-snapshot-tests.jest.js.snap
  src/components/ModalFooter/__tests__/modalFooter-snapshot-tests.jest.js
  src/components/ModalHeader/ModalHeader.jsx
  src/components/ModalHeader/ModalHeader.module.scss
  src/components/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/ModalHeader/__tests__/modalHeader-snapshot-tests.jest.js
  src/components/index.js
  webpack/published-js-components.js
Labels: PR: New Feature 🕹

#890 fix css issue
  src/components/ModalHeader/ModalHeader.module.scss
Labels: PR: Bugfix 🐛
