Repository mondaycom/vibe, pull requests merged in 2022-12, with the labels that each got.

#1010 Feature/sergeyro/dropdown disabled color fix
  src/components/Chips/Chips.tsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#996 RadioButton: add disabled-text-color
  src/components/RadioButton/RadioButton.scss
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1025 Export interactions 2
  plop/component/component-ts.txt
  plop/component/index.js
  src/__tests__/interactions-helper.js
  src/components/Accordion/Accordion/__tests__/accordion.interactions.ts
  src/components/Avatar/__tests__/avatar.jest.tsx
  src/components/Button/Button.tsx
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/chips-tests.jest.tsx
  src/components/Clickable/Clickable.tsx
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/components/Clickable/__tests__/clickable-interactions-tests.js
  src/components/Clickable/__tests__/clickable-tests.jest.tsx
  src/components/ColorPicker/__tests__/ColorPicker.interactions.js
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/combobox-interactions.js
  src/components/DatePicker/DatePicker.tsx
  src/components/Divider/Divider.tsx
  src/components/Dropdown/__tests__/Dropdown.interactions.js
  src/components/GridKeyboardNavigationContext/__tests__/useGridKeyboardNavigationContext.interactions.js
  src/components/Icon/__tests__/all-icons-tests.jest.ts
  src/components/IconButton/IconButton.tsx
  src/components/Loader/Loader.tsx
  src/components/Menu/Menu/__tests__/menu-interactions.js
  src/components/Search/Search.tsx
  src/components/Slider/__tests__/Slider.interactions.js
  src/components/TextField/TextField.tsx
  src/components/VirtualizedList/VirtualizedList.tsx
  src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.interactions.js
  src/tests/constants.ts
  src/tests/interactions-utils.ts
  src/tests/test-ids-utils.ts
  src/types/VibeComponent.ts
  src/types/index.ts
  src/utils/test-utils.js
  webpack.config.js
Labels: PR: New Feature 🕹

#1029 close while scrolling with in dialog/modal mode
  src/components/Dropdown/Dropdown.jsx
Labels: PR: Bugfix 🐛

#1031 Fix interactions-utils imports in RadioButton
  src/components/RadioButton/__stories__/interactions.js
  src/tests/interactions-utils.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1026 Add interactions basic readme file
  src/tests/readme.md
Labels: PR: Documentation 📖

#1033 Test readme markdown fixes
  src/tests/readme.md
Labels: PR: unreviewed, PR: Documentation 📖

#1028 Fix AvatarGroup tooltip keyboard navigation: fix checkWithoutModifierInEvent
  src/hooks/useKeyEvent/index.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1034 MenuButton: allow to specify position of an icon
  src/components/MenuButton/MenuButton.jsx
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
  src/components/MenuButton/__tests__/__snapshots__/menuButton.jest.js.snap
  src/components/MenuButton/__tests__/menuButton.jest.js
Labels: PR: New Feature 🕹

#1036 Accessability story navigation fix
  src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1018 Feature/sergeyro/chips hovered state + clickable
  package-lock.json
  package.json
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/IconButton/IconButton.tsx
  src/hooks/index.js
  src/hooks/useHover.ts
  src/hooks/useIsMouseOver.ts
  src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
  src/utils/colors-vars-map.ts
Labels: PR: unreviewed, PR: New Feature 🕹

#1032 Icon: follow create component best practices.
  src/components/Icon/Icon.tsx
Labels: PR: Internal 🏠

#1039 Import react to prevent cypress tests (in docs team e.g.) from failing
  src/components/Tooltip/Tooltip.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1037 Same behaviour for active button ,active split button and active icon button
  src/components/Button/Button.scss
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/SplitButton/SplitButton.scss
  src/components/SplitButton/SplitButton.tsx
Labels: PR: Bugfix 🐛

#1040 Fix TabList undefined error
  src/components/Tabs/TabList/TabList.tsx
Labels: PR: Bugfix 🐛

#1041 Heading Weights
  src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/EditableHeading.scss
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/Heading/Heading.scss
  src/components/Heading/Heading.tsx
  src/components/Heading/HeadingConstants.ts
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Heading/__tests__/__snapshots__/heading.jest.js.snap
  src/components/TextWithHighlight/TextWithHighlight.tsx
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/styles/typography.scss
Labels: PR: New Feature 🕹

#1043 Revert "Heading Weights"
  src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/EditableHeading.scss
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/Heading/Heading.scss
  src/components/Heading/Heading.tsx
  src/components/Heading/HeadingConstants.ts
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Heading/__tests__/__snapshots__/heading.jest.js.snap
  src/components/TextWithHighlight/TextWithHighlight.tsx
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/styles/typography.scss
Labels: PR: Bugfix 🐛

#995 Dialog, DialogContent, MenuButton: TS-migration
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/components/Dialog/consts/dialog-show-hide-event.js
  src/components/Dialog/consts/dialog-show-hide-event.ts
  src/components/Menu/Menu/hooks/useCloseMenuOnKeyEvent.jsx
  src/components/MenuButton/MenuButton.jsx
  src/components/MenuButton/MenuButton.tsx
  src/components/MenuButton/MenuButtonConstants.ts
  src/components/MenuButton/__tests__/__snapshots__/menuButton.jest.js.snap
  src/components/MenuButton/__tests__/menuButton.jest.js
  src/components/SplitButton/SplitButton.tsx
  src/components/SplitButton/SplitButtonConstants.ts
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Tooltip/Tooltip.tsx
  src/constants/KeyCodes.js
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#1013 Feature/sergeyro/ts migration menu
  src/components/AvatarGroup/AvatarGroupCounter.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Heading/Heading.tsx
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/Menu/MenuConstants.ts
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/Menu/hooks/useAdjacentSelectableMenuIndex.tsx
  src/components/Menu/Menu/hooks/useCloseMenuOnKeyEvent.jsx
  src/components/Menu/Menu/hooks/useCloseMenuOnKeyEvent.tsx
  src/components/Menu/Menu/hooks/useLastNavigationDirection.tsx
  src/components/Menu/Menu/hooks/useMenuKeyboardNavigation.tsx
  src/components/Menu/Menu/hooks/useMouseLeave.tsx
  src/components/Menu/Menu/hooks/useOnCloseMenu.jsx
  src/components/Menu/Menu/hooks/useOnCloseMenu.tsx
  src/components/Menu/Menu/hooks/useSubMenuIndex.tsx
  src/components/Menu/MenuDivider/MenuDivider.tsx
  src/components/Menu/MenuGridItem/MenuGridItem.tsx
  src/components/Menu/MenuGridItem/useFocusGridItemByActiveStatus.tsx
  src/components/Menu/MenuGridItem/useMenuGridItemNavContext.tsx
  src/components/Menu/MenuItem/AvatarMenuItem.tsx
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/MenuItemConstants.ts
  src/components/Menu/MenuItem/hooks/useMenuItemKeyboardEvents.ts
  src/components/Menu/MenuItem/hooks/useMenuItemMouseEvents.ts
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/Menu/MenuTitle/MenuTitleConstants.js
  src/components/Menu/MenuTitle/MenuTitleConstants.ts
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.js
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
  src/components/Tipseen/Tipseen.jsx
  src/constants/KeyCodes.js
  src/constants/index.js
  src/constants/positions.js
  src/constants/sizes.ts
  src/hooks/useFocusWithin.ts
  src/hooks/useFullKeyboardListeners.ts
  src/hooks/useKeyEvent/index.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#1045 Feature/sergeyro/more of dialog container selectors
  src/components/MenuButton/MenuButton.tsx
  src/components/SplitButton/SplitButton.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1047 Increase Tipseen styles specificity to override Tooltip styles
  src/components/Tipseen/Tipseen.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1048 Feature/sergeyro/icon button tooltipProps
  src/components/AlertBanner/AlertBannerText/AlertBannerText.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/ButtonWrapper.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Heading/Heading.tsx
  src/components/IconButton/IconButton.tsx
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/MenuButton/MenuButton.tsx
  src/components/Slider/SliderBase/SliderThumb.tsx
  src/components/SplitButton/SplitButton.tsx
  src/components/TextWithHighlight/TextWithHighlight.tsx
  src/components/Tipseen/Tipseen.jsx
  src/components/Tooltip/Tooltip.tsx
  src/constants/positions.js
  src/constants/positions.ts
  src/helpers/backwardCompatibilityForProperties.ts
Labels: PR: unreviewed, PR: New Feature 🕹
