Repository mondaycom/vibe, pull requests merged in 2022-04, with the labels that each got.

#618 test(accordion): add interaction tests for multi-active mode
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/Accordion/Accordion/__tests__/accordion.interactions.js
Labels: PR: Documentation 📖

#621 Combobox max options without scroll
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/VirtualizedList/VirtualizedList.jsx
Labels: PR: New Feature 🕹

#624 Analytics
  .storybook/main.js
  .storybook/manager-head.html
Labels: PR: Documentation 📖

#627 Scroll into view not exsiting
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/storybook/components/link-component/link-component.jsx
Labels: PR: Bugfix 🐛

#628 Scrollintoview
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/storybook/components/link-component/link-component.jsx
Labels: PR: Bugfix 🐛

#623 # 💄 Change Icon Button Small variant shape size to 24px.
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#629 feat: adding a flag to ColorPicker for showing color name tooltips
  src/components/ColorPicker/ColorPicker.jsx
  src/components/ColorPicker/__tests__/colorPicker.jest.js
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
Labels: PR: New Feature 🕹

#622 Feature/yonatanari/wellcome page updates
  src/storybook/components/information-box-title/information-box-title.jsx
  src/storybook/components/information-box-title/information-box-title.scss
  src/storybook/components/information-box/information-box.jsx
  src/storybook/components/information-box/information-box.scss
  src/storybook/stand-alone-documentaion/welcome/assets/BackgroundPattern1.png
  src/storybook/stand-alone-documentaion/welcome/assets/BackgroundPattern2.png
  src/storybook/stand-alone-documentaion/welcome/assets/BackgroundPattern3.png
  src/storybook/stand-alone-documentaion/welcome/assets/BackgroundPattern4.png
  src/storybook/stand-alone-documentaion/welcome/assets/BackgroundPattern5.png
  src/storybook/stand-alone-documentaion/welcome/assets/NickBackground.png
  src/storybook/stand-alone-documentaion/welcome/assets/Nik.png
  src/storybook/stand-alone-documentaion/welcome/assets/Rotem.png
  src/storybook/stand-alone-documentaion/welcome/assets/Yonatan.png
  src/storybook/stand-alone-documentaion/welcome/assets/index.js
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.jsx
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
Labels: PR: Documentation 📖

#630 fix icon size for small button
  src/components/Button/Button.jsx
Labels: PR: Bugfix 🐛

#625 add support on virtualized list items inside list component
  src/components/ColorPicker/__tests__/colorPicker.jest.js
  src/components/Combobox/Combobox.jsx
  src/components/List/List.jsx
  src/components/List/List.scss
  src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
  src/components/List/VirtualizedListItems/VirtualizedListItems.module.scss
  src/components/List/__stories__/List.stories.mdx
  src/components/ListTitle/ListTitle.scss
  src/components/VirtualizedList/VirtualizedList.jsx
Labels: PR: New Feature 🕹

#632 Support on disabled tabIndex
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.jsx
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.jsx
Labels: PR: Bugfix 🐛

#633 Fix minor craft bugs (button disabled cursor and chip close button appearance) & stories & add data test id prop to chip, button, icon button
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/Button/__stories__/button.stories.mdx
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.js.snap
  src/components/Chips/Chips.jsx
  src/components/Chips/Chips.scss
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/Chips/__tests__/chips-tests.jest.js
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-snapshot-tests.jest.js.snap
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/utils/test-utils.js
Labels: PR: New Feature 🕹

#635 Add flag for undo a null check which cause weird behavior (combobox)
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem-snapshot-tests.jest.js.snap
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.jsx
Labels: PR: Bugfix 🐛

#641 Fix bug: support press shift while click on checkbox on firefox browsers
  src/components/Checkbox/Checkbox.js
Labels: PR: Bugfix 🐛

#643 remove set style hardcoded for icon button (not needed and not used u…
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#648 Undo "component" absolute path because it increase bundle size
  src/components/Chips/Chips.jsx
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
Labels: PR: Bugfix 🐛

#649 fix commit
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
Labels: PR: Bugfix 🐛

#653 Fix usage on useMergedRef in checkbox
  src/components/Checkbox/Checkbox.js
Labels: PR: Bugfix 🐛

#636 A11y/combobox nav refactor and expose list focus and keyboard navigation hook
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.module.scss
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-tests.jest.js
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
  src/components/Search/Search.jsx
  src/constants/KeyCodes.js
  src/hooks/index.js
  src/hooks/useActiveDescendantListFocus/__stories__/hooksDummyComponents/UseActiveDescendantListFocus.jsx
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.module.scss
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
  src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.interactions.js
  src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.jest.js
  src/hooks/useActiveDescendantListFocus/index.js
  src/hooks/useListKeyboardNavigation.js
  src/storybook/components/unstyled-list/unstyled-list.jsx
  webpack/published-components.js
Labels: PR: New Feature 🕹

#654 Fix export of a11y list hook
  webpack/published-components.js
Labels: PR: Bugfix 🐛
