Repository mondaycom/vibe, pull requests merged in 2022-05, with the labels that each got.

#655 Fix combobox with categories focus (css) bug
  src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
Labels: PR: Bugfix 🐛

#656 Update combobox docs
  src/components/Combobox/Combobox.jsx
Labels: PR: Bugfix 🐛

#584 Use media query
  jest.init.js
  jest/jest.setup.js
  src/hooks/index.js
  src/hooks/useMediaQuery/__stories__/useMediaQuery.stories.mdx
  src/hooks/useMediaQuery/index.js
  src/hooks/useVibeMediaQuery/__stories__/useVibeMediaQuery.modules.scss
  src/hooks/useVibeMediaQuery/__stories__/useVibeMediaQuery.stories.mdx
  src/hooks/useVibeMediaQuery/index.js
  src/utils/media-query-utils.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#657 Storybook: usePrevios hook
  src/hooks/usePrevious/__stories__/usePrevious.stories.mdx
  src/hooks/usePrevious/__stories__/usePrevious.stories.module.scss
  src/hooks/usePrevious/index.js
Labels: PR: Documentation 📖

#662 Fix bug: remove "add new" button from not found empty state in combobox as default
  src/components/Combobox/Combobox.jsx
Labels: PR: Bugfix 🐛

#663 fix use previous export
  webpack/published-components.js
Labels: PR: Bugfix 🐛

#668 hide the dialog/tooltip when the reference is hidden
  src/components/MenuButton/MenuButton.jsx
Labels: PR: New Feature 🕹

#669 upgrade patch versions
  package-lock.json
  package.json
Labels: PR: Dependencies 🛠

#676 # Update "monday-ui-style" to "0.1.111"
  package-lock.json
  package.json
  src/storybook/components/visual-description/visual-description.scss
  src/storybook/stand-alone-documentaion/colors/background-colors/background-colors.jsx
  src/utils/colors-vars-map.js
Labels: PR: New Feature 🕹

#659 Storybook/sergey/use set focus hook
  src/hooks/__tests__/useSetFocus.jest.js
  src/hooks/index.js
  src/hooks/useSetFocus.js
  src/hooks/useSetFocus/__stories__/useSetFocus.stories.mdx
  src/hooks/useSetFocus/__stories__/useSetFocus.stories.module.scss
  src/hooks/useSetFocus/__tests__/useSetFocus.jest.js
  src/hooks/useSetFocus/index.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#679 Patch/yonatanari/disabled states correction
  package-lock.json
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.scss
  src/components/Button/Button.scss
  src/components/Combobox/__stories__/combobox.stories.scss
  src/components/ListItem/ListItem.scss
  src/components/MenuButton/MenuButton.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/Slider/SliderBase/SliderBase.scss
  src/components/TextField/TextField.scss
  src/components/Toggle/Toggle.scss
Labels: PR: Bugfix 🐛

#680 Change attention box default padding
  src/components/AttentionBox/AttentionBox.scss
Labels: PR: Bugfix 🐛

#660 # Update sass to version "sass": "^1.51.0",
  package.json
Labels: PR: Dependencies 🛠

#681 fix: Remove Tip box
  src/components/Search/__stories__/Search.stories.mdx
Labels: PR: Documentation 📖

#683 EditableHeading -Add option to pass argument to onStartEditing, input class name prop,…
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/EditableHeading/__tests__/editableHeading.jest.js
Labels: PR: New Feature 🕹
