Repository mondaycom/vibe, pull requests merged in 2022-10, with the labels that each got.

#884 Feature/sergeyro/font change
  .storybook/preview-head.html
  src/components/AlertBanner/AlertBanner.scss
  src/components/AttentionBox/AttentionBox.scss
  src/components/Banner/Banner.scss
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.scss
  src/components/FieldLabel/FieldLabel.scss
  src/components/ListItem/ListItem.scss
  src/components/Menu/MenuTitle/MenuTitle.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/Slider/Slider.scss
  src/components/Slider/SliderBase/SliderBase.scss
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/TabList/TabList.scss
  src/components/TextField/TextField.scss
  src/components/Toast/Toast.scss
Labels: PR: unreviewed, PR: New Feature 🕹

#897 convert helpers/utils to typescript
  src/helpers/backwardCompatibilityForProperties.ts
  src/helpers/bem-helper.ts
  src/helpers/testid-helper.js
  src/helpers/testid-helper.ts
  src/helpers/textManipulations.ts
  src/utils/colors-utils.ts
  src/utils/colors-vars-map.ts
  src/utils/dom-event-utils.ts
  src/utils/dom-positioning-utils.js
  src/utils/dom-utils.ts
  src/utils/function-utils.ts
  src/utils/media-query-utils.ts
  src/utils/user-agent-utils.ts
Labels: PR: Internal 🏠

#901 upgrade deps
  package-lock.json
  package.json
Labels: PR: Dependencies 🛠

#907 Migrate Counter component to TS.
  package-lock.json
  package.json
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/components/Counter/Counter.tsx
  src/components/Counter/CounterConstants.js
  src/components/Counter/CounterConstants.ts
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Counter/__tests__/__snapshots__/counter-snapshot-tests.jest.tsx.snap
  src/components/Counter/__tests__/counter-snapshot-tests.jest.tsx
  src/components/Counter/__tests__/counter-tests.jest.tsx
Labels: PR: Internal 🏠

#917 refactor(Banner): Migrated from JS to TS
  src/components/Banner/Banner.tsx
  src/components/Banner/BannerConstants.js
  src/components/Banner/BannerConstants.ts
  src/components/Banner/__tests__/__snapshots__/banner.jest.tsx.snap
  src/components/Banner/__tests__/banner.jest.tsx
  src/components/Button/Button.tsx
  src/components/Icon/Icon.tsx
  src/types/events.ts
Labels: PR: Internal 🏠

#916 refactor: migrate Divider in typescript
  src/components/Divider/Divider.tsx
  src/components/Divider/DividerConstants.js
  src/components/Divider/DividerConstants.ts
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/Divider/__tests__/divider.jest.tsx
Labels: PR: Internal 🏠

#913 Convert label to typescript
  src/components/Label/Label.tsx
  src/components/Label/LabelConstants.js
  src/components/Label/Leg.tsx
  src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.tsx.snap
  src/components/Label/__tests__/label-snapshot-tests.jest.tsx
Labels: PR: Internal 🏠

#924 refactor: migrate IconButton to typescript
  src/components/IconButton/IconButton.tsx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/IconButton/__tests__/iconButton-snapshot-tests.jest.tsx
  src/components/IconButton/__tests__/iconButton-tests.jest.tsx
  src/components/IconButton/services/IconButton-helpers.ts
Labels: PR: Internal 🏠

#928 modal css fixes
  src/components/Modal/Modal.module.scss
  src/components/ModalHeader/ModalHeader.module.scss
Labels: PR: Bugfix 🐛

#929 move IconButton to ts components list
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#930 Fixes in chips migration to ts
  src/components/Chips/Chips.tsx
  src/components/Chips/ChipsConstants.ts
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/chips-snapshot-tests.jest.tsx
  src/components/Chips/__tests__/chips-tests.jest.tsx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#925 refactor: migrate AttentionBox to typescript
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/AttentionBoxConstants.js
  src/components/AttentionBox/AttentionBoxConstants.ts
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/AttentionBox/__tests__/attentionBox-snapshot-tests.jest.tsx
  src/components/AttentionBox/__tests__/attentionBox-tests.jest.tsx
Labels: PR: Internal 🏠

#940 added some docs to modal component
  src/components/Modal/Modal.jsx
Labels: PR: Bugfix 🐛

#942 fix attentionBox snapshot
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: Bugfix 🐛

#944 Revert release version
  CHANGELOG.md
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#939 Fix attention box migration to ts
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/AttentionBoxConstants.ts
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/AttentionBox/__tests__/attentionBox-snapshot-tests.jest.tsx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#937 Ts/hadas/tooltip
  src/components/Avatar/Avatar.tsx
  src/components/Dialog/Dialog.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/components/Menu/MenuItemButton/MenuItemButton.jsx
  src/components/Slider/SliderBase/SliderThumb.jsx
  src/components/Tipseen/Tipseen.jsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipConstants.js
  src/components/Tooltip/TooltipConstants.ts
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
  src/components/Tooltip/__tests__/tooltip-snapshot-tests.jest.tsx
  src/components/Tooltip/__tests__/tooltip-tests.jest.tsx
  src/constants/AnimationTypes.js
  src/constants/dialog.ts
  src/constants/index.js
  src/constants/sizes.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#943 fix: onClose can be undefined when hidding the modal
  src/components/Modal/useShowHideModal.js
Labels: PR: Bugfix 🐛

#950 fix button group after migration
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/ButtonGroupConstants.ts
  src/components/ButtonGroup/ButtonWrapper.tsx
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.tsx.snap
  src/components/ButtonGroup/__tests__/buttonGroup-snapshot-tests.jest.tsx
  src/components/ButtonGroup/__tests__/buttonGroup-tests.jest.tsx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#862 Loader Typescript migration
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Loader/Loader.tsx
  src/components/Loader/LoaderConstants.js
  src/components/Loader/LoaderConstants.ts
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/utils/test-utils.js
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#934 Plop Typescript migration
  plop/component/component-js.txt
  plop/component/component-published-component.txt
  plop/component/component-ts.txt
  plop/component/index.js
  plop/general/component-stories-mdx.txt
  plop/hooks/hook.txt
  plop/hooks/index.js
  src/utils/test-utils.js
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#941 AlertBanner: Typescript migration
  src/components/AlertBanner/AlertBanner.tsx
  src/components/AlertBanner/AlertBannerButton/AlertBannerButton.tsx
  src/components/AlertBanner/AlertBannerConstants.jsx
  src/components/AlertBanner/AlertBannerConstants.ts
  src/components/AlertBanner/AlertBannerLink/AlertBannerLink.tsx
  src/components/AlertBanner/AlertBannerText/AlertBannerText.tsx
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#952 For "getElementColor" function return, add missing ')'.
  src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.tsx.snap
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/utils/colors-vars-map.ts
Labels: PR: Bugfix 🐛

#932 Add docs about change publish component files for every ts migration update
  TYPESCRIPT_MIGRATION.md
Labels: PR: Documentation 📖

#933 refactor: migrate DialogContentContainer to typescript
  src/components/DialogContentContainer/DialogContentContainer.jsx
  src/components/DialogContentContainer/DialogContentContainer.tsx
  src/components/DialogContentContainer/DialogContentContainerConstants.ts
  src/components/DialogContentContainer/__tests__/dialogContentContainer.jest.tsx
Labels: PR: Internal 🏠

#955 Toggle: TS-migration
  src/components/Switch/Switch.tsx
  src/components/Switch/hooks/useSwitchChecked.ts
  src/components/Switch/index.js
  src/components/Toggle/MockToggle.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/ToggleConstants.ts
  src/components/Toggle/ToggleText.jsx
  src/components/Toggle/ToggleText.tsx
  src/components/Toggle/__stories__/toggle.stories.mdx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#951 TextField: TS migration
  src/components/FieldLabel/FieldLabel.tsx
  src/components/Search/Search.tsx
  src/components/Search/SearchConstants.ts
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/TextField/TextField.tsx
  src/components/TextField/TextFieldConstants.js
  src/components/TextField/TextFieldConstants.ts
  src/components/TextField/TextFieldHelpers.js
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/TextField/__tests__/TextField.jest.js
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#958 Tab: TS-migration
  src/components/Tabs/Tab/Tab.tsx
  src/components/Tabs/Tab/__stories__/tab.stories.mdx
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/TabList.jsx
  src/components/Tabs/TabList/TabList.tsx
  src/components/Tabs/TabList/__stories__/tab-list.stories.mdx
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanel/TabPanel.tsx
  src/components/Tabs/TabPanel/__stories__/tab-panel.stories.mdx
  src/components/Tabs/TabPanel/__tests__/__snapshots__/tabPanel-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanels/TabPanels.tsx
  src/components/Tabs/TabPanels/TabPanelsConstants.ts
  src/components/Tabs/TabPanels/__stories__/tab-panels.stories.mdx
  src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/TabsContext.tsx
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#875 Neil/date picker
  .stylelintrc.json
  jest.init.js
  package-lock.json
  package.json
  src/components/DatePicker/DateNavigationItem/DateNavigationItem.module.scss
  src/components/DatePicker/DateNavigationItem/DateNavigationItem.tsx
  src/components/DatePicker/DatePicker.module.scss
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/DatePickerHeader/DatePickerHeader.module.scss
  src/components/DatePicker/DatePickerHeader/DatePickerHeader.tsx
  src/components/DatePicker/YearPicker/YearPicker.module.scss
  src/components/DatePicker/YearPicker/YearPicker.tsx
  src/components/DatePicker/YearPicker/YearsList.tsx
  src/components/DatePicker/__stories__/DatePicker.stories.module.scss
  src/components/DatePicker/__stories__/datepicker.stories.mdx
  src/components/DatePicker/__tests__/DatePicker.jest.js
  src/components/DatePicker/constants.ts
  src/components/DatePicker/date-picker-utils.ts
  src/components/DatePicker/types.ts
  src/utils/test-utils.js
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#962 add support for import css files
  .storybook/main.js
  webpack.config.js
Labels: bug, PR: Internal 🏠

#956 TS fixes: add SubIcon and Element types + remove default props
  src/components/AttentionBox/AttentionBox.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/AvatarBadge.tsx
  src/components/Avatar/AvatarConstants.tsx
  src/components/Avatar/AvatarContent.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/__tests__/banner.jest.tsx
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.tsx
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.tsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Chips/Chips.tsx
  src/components/Counter/Counter.tsx
  src/components/HiddenText/HiddenText.tsx
  src/components/Icon/FontIcon/FontIcon.tsx
  src/components/Icon/Icon.tsx
  src/components/IconButton/IconButton.tsx
  src/components/Label/Label.tsx
  src/components/Link/Link.tsx
  src/components/ListItemIcon/ListItemIcon.tsx
  src/components/Search/Search.tsx
  src/components/Tooltip/Tooltip.tsx
  src/types/ElementContent.ts
  src/types/SubIcon.ts
  src/types/index.ts
Labels: PR: Internal 🏠

#965 Accordion: ts-migration - refactoring
  src/components/Accordion/Accordion/Accordion.tsx
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/Accordion/AccordionItem/AccordionItem.tsx
Labels: PR: unreviewed, PR: Internal 🏠

#966 Fix DatePicker tests + refactor
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/__tests__/DatePicker.jest.tsx
Labels: PR: unreviewed, PR: Internal 🏠

#967 Box: ts-migration
  src/components/Box/Box.jsx
  src/components/Box/Box.tsx
  src/components/Box/BoxConstants.ts
  src/components/Box/__stories__/Box.stories.mdx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠
