Repository mondaycom/vibe, pull requests merged in 2022-03, with the labels that each got.

#567 Fix editable heading cursor on disabled
  src/components/Clickable/Clickable.jsx
  src/components/Clickable/Clickable.scss
  src/components/EditableHeading/EditableHeading.jsx
Labels: PR: Bugfix 🐛

#561 Added menuPlacement prop to Dropdown component
  src/components/Dropdown/Dropdown.jsx
Labels: PR: New Feature 🕹

#571 Add all icons tests
  src/components/Icon/Icons/index.js
  src/components/Icon/__tests__/all-icons-tests.jest.js
  webpack/published-components.js
Labels: PR: Bugfix 🐛

#578 Feature/hadas/checkbox ref
  src/components/Checkbox/Checkbox.js
Labels: PR: New Feature 🕹

#562 Add dropdown groups to storybook and change dropdown groups style
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
Labels: PR: Documentation 📖

#580 Clear filter on combobox selection
  src/components/Combobox/Combobox.jsx
Labels: PR: New Feature 🕹

#581 Fix issue with hovering combobox hover
  src/components/Combobox/Combobox.jsx
Labels: PR: Bugfix 🐛

#583 Fix issue with combobox story
  src/components/Combobox/__stories__/combobox.stories.mdx
Labels: PR: Bugfix 🐛

#582 Interaction tests
  .storybook/addons.js
  .storybook/main.js
  package-lock.json
  package.json
  src/__tests__/interactions-helper.js
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__stories__/interactions.js
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__stories__/interactions.js
  src/utils/test-utils.js
Labels: PR: Internal 🏠

#585 Add menu tests
  src/__tests__/interactions-helper.js
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__stories__/interactions.js
  src/components/Menu/Menu/__stories__/menu.stories.js
Labels: PR: Internal 🏠

#574 Add virtualized list support to combobox
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/Combobox.scss
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/components/ComboboxCategory/ComboboxCategory.jsx
  src/components/Combobox/components/ComboboxCategory/ComboboxCategory.scss
  src/components/Combobox/components/ComboboxConstants.js
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/Combobox/components/ComboboxItems/ComboboxItems.modules.scss
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
  src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.jsx
  src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.module.scss
  src/components/Combobox/components/StickyCategoryHeader/StickyCategoryHeader.jsx
  src/components/Combobox/components/StickyCategoryHeader/StickyCategoryHeader.module.scss
  src/components/VirtualizedList/VirtualizedList.jsx
  src/storybook/components/story-description/story-description.jsx
Labels: PR: New Feature 🕹

#589 Fix combobox spacing issues
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/components/ComboboxCategory/ComboboxCategory.scss
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/Combobox/components/ComboboxItems/ComboboxItems.modules.scss
  src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.jsx
Labels: PR: Bugfix 🐛

#586 Fix menu grid item focus after keyboard nav
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
  src/components/GridKeyboardNavigationContext/__tests__/GridKeyboardNavigationContext.jest.js
  src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
  src/components/GridKeyboardNavigationContext/helper.js
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/Menu/hooks/__tests__/useLastNavigationDirection.jest.js
  src/components/Menu/Menu/hooks/useLastNavigationDirection.jsx
  src/components/Menu/MenuGridItem/__tests__/useFocusGridItemByActiveStatus.jest.js
  src/components/Menu/MenuGridItem/useFocusGridItemByActiveStatus.jsx
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
Labels: PR: Bugfix 🐛

#592 Move deps to devDependencies
  package-lock.json
  package.json
Labels: PR: Dependencies 🛠

#588 feature/omri/multi-interaction-tests-per-story
  src/__tests__/interactions-helper.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__stories__/interactions.js
Labels: PR: Documentation 📖

#594 fix dark mode issue, sticky issue and add categories story
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.module.scss
Labels: PR: Bugfix 🐛

#603 storybook initials
  .storybook/addons.js
  .storybook/main.js
  package-lock.json
  package.json
Labels: PR: Documentation 📖

#601 Fix/omri/fix grid keyboard nav story
  src/__tests__/interactions-helper.js
  src/components/Flex/Flex.jsx
  src/components/GridKeyboardNavigationContext/__stories__/interactions.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.mdx
  src/storybook/components/multiple-story-elements-wrapper/multiple-story-elements-wrapper.jsx
  src/storybook/components/multiple-story-elements-wrapper/multiple-story-elements-wrapper.scss
Labels: PR: New Feature 🕹

#602 Increase default width of left panel
  .storybook/manager-head.html
Labels: PR: Documentation 📖

#605 Interaction tests alignments
  .storybook/main.js
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/Combobox.interactions.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/Dropdown.interactions.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.mdx
  src/components/GridKeyboardNavigationContext/__tests__/useGridKeyboardNavigationContext.interactions.js
Labels: PR: Documentation 📖

#606 fix(interaction): minor selector typo issue
  src/__tests__/interactions-helper.js
Labels: PR: Bugfix 🐛

#608 test(Slider): add interaction tests for Slider component
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Slider/__tests__/Slider.interactions.js
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/slider-non-ranged-tests.jest.js
Labels: PR: Documentation 📖

#609 Fix clickable tests (add interaction tests for focus and few behaviour tests)
  src/__tests__/interactions-helper.js
  src/components/Clickable/Clickable.jsx
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/components/Clickable/__stories__/clickable.stories.scss
  src/components/Clickable/__tests__/__snapshots__/clickable-snapshot-tests.jest.js.snap
  src/components/Clickable/__tests__/clickable-interactions-tests.js
  src/components/Clickable/__tests__/clickable-snapshot-tests.jest.js
  src/components/Clickable/__tests__/clickable-tests.jest.js
  src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.js.snap
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator-snapshot-tests.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/utils/test-utils.js
Labels: PR: Bugfix 🐛

#596 # ay11 Foundation page Corrections: Update image sizes, add up next section
  src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
  src/storybook/stand-alone-documentaion/accessibility/assets/color-contrast_image.png
  src/storybook/stand-alone-documentaion/accessibility/assets/color-contrast_text.png
  src/storybook/stand-alone-documentaion/accessibility/assets/hierarchy_order.png
  src/storybook/stand-alone-documentaion/accessibility/assets/imagery_alt.png
  src/storybook/stand-alone-documentaion/accessibility/assets/imagery_decorative.png
  src/storybook/stand-alone-documentaion/accessibility/assets/imagery_descriptive.png
  src/storybook/stand-alone-documentaion/accessibility/assets/navigation_focus-visible.png
  src/storybook/stand-alone-documentaion/accessibility/assets/navigation_tabs.png
Labels: PR: Documentation 📖

#611 test(Slider): add interaction tests for ranged mode
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Slider/__tests__/Slider.interactions.js
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/slider-ranged-tests.jest.js
Labels: PR: Documentation 📖

#607 Color picker interaction tests
  src/__tests__/interactions-helper.js
  src/components/ColorPicker/__stories__/ColorPicker.stories.js
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
  src/components/ColorPicker/__tests__/ColorPicker.interactions.js
  src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.js.snap
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/GridKeyboardNavigationContext/__tests__/useGridKeyboardNavigationContext.interactions.js
Labels: PR: Documentation 📖

#612 menu interaction tests
  src/__tests__/interactions-helper.js
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__stories__/interactions.js
  src/components/Menu/Menu/__tests__/menu-interactions.js
Labels: PR: Documentation 📖

#613 test(slider): add Thumbs drag interaction tests for Ranged Slider
  src/components/Slider/__tests__/Slider.interactions.js
Labels: PR: Documentation 📖

#610 test(slider): add Thumb drag interaction tests
  src/__tests__/interactions-helper.js
  src/components/Slider/__tests__/Slider.interactions.js
Labels: PR: Documentation 📖

#616 Avatar custom background color
  src/components/Avatar/Avatar.jsx
Labels: PR: New Feature 🕹

#614 color picker testids fix
  src/__tests__/interactions-helper.js
  src/components/ColorPicker/__tests__/ColorPicker.interactions.js
  src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.js.snap
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/utils/test-utils.js
Labels: PR: Documentation 📖

#615 Interaction tests for combobox & add data test ids by prop to clickable, search, textfield, combobox
  src/__tests__/interactions-helper.js
  src/components/Clickable/Clickable.jsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/Combobox.interactions.js
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-interactions.js
  src/components/Combobox/__tests__/combobox-tests.jest.js
  src/components/Search/Search.jsx
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/TextField.jsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/VirtualizedList/VirtualizedList.jsx
  src/components/VirtualizedList/__stories__/VirtualizedList.stories.mdx
  src/components/VirtualizedList/__stories__/virtualizedList.components.js
  src/components/VirtualizedList/__stories__/virtualizedList.module.scss
  src/components/VirtualizedList/__tests__/__snapshots__/virtualized-list-snapshot-tests.jest.js.snap
  src/components/VirtualizedList/__tests__/virtualized-list-snapshot-tests.jest.js
  src/utils/test-utils.js
Labels: PR: Bugfix 🐛
