Repository mondaycom/vibe, pull requests merged in 2022-11, with the labels that each got.

#968 Fix bug: scroll inside dropdown in overflow mode
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/DropdownConstants.js
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#969 fix accordion publish
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#970 tipseen tip prop
  src/components/Tipseen/Tipseen.jsx
  src/components/Tooltip/Tooltip.tsx
Labels: PR: New Feature 🕹

#975 Fix storybook box overview code
  src/components/Box/__stories__/Box.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#976 add source maps
  webpack.config.js
Labels: PR: Internal 🏠

#982 Fix tooltip-arrow color to adapt to the theme
  src/components/Dialog/Dialog.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#983 dropdown component tooltip
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
  src/components/Dropdown/components/Control/Control.jsx
Labels: PR: New Feature 🕹

#978 TS-migration: LinearProgressBar, Bar
  src/components/ProgressBars/LinearProgressBar/Bar/Bar.jsx
  src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.js
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.ts
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.js
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#961 Toast: TS-migration
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastButton/ToastButton.tsx
  src/components/Toast/ToastConstants.js
  src/components/Toast/ToastConstants.ts
  src/components/Toast/ToastHelpers.tsx
  src/components/Toast/ToastLink/ToastLink.tsx
  src/components/Toast/__stories__/toast.stories.mdx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#947 SplitButton: Typescript migration
  src/components/SplitButton/SplitButton.tsx
  src/components/SplitButton/SplitButtonConstants.ts
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#980 TS-migration: VirtualizedGrid
  package-lock.json
  package.json
  src/components/VirtualizedGrid/VirtualizedGrid.tsx
  src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.mdx
  src/components/VirtualizedGrid/__tests__/__snapshots__/virtualizedGrid.jest.js.snap
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#959 TS-migration: Steps
  src/components/Steps/Steps.tsx
  src/components/Steps/StepsCommand.tsx
  src/components/Steps/StepsConstants.ts
  src/components/Steps/StepsDot.tsx
  src/components/Steps/StepsGalleryHeader.tsx
  src/components/Steps/StepsHeader.tsx
  src/components/Steps/StepsNumbersHeader.jsx
  src/components/Steps/StepsNumbersHeader.tsx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Tipseen/TipseenWizard.jsx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#985 Check if contributorsJson is an array before filtering
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#988 Rollup
  .eslintrc.js
  .github/workflows/test-workflow.yml
  .github/workflows/update-icons.yml
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  rollup.config.js
  scripts/autobump_major.js
  scripts/autobump_minor.js
  scripts/autobump_patch.js
  scripts/build-exports.js
  scripts/build-ts-index.js
  scripts/build-utils.js
  scripts/bump-version.js
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/AvatarGroup/AvatarGroupCounter.module.scss
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.jsx
  src/components/Checkbox/Checkbox.jsx
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/components/Combobox/helpers.ts
  src/components/Icon/__stories__/Icon.stories.mdx
  src/components/Menu/Menu/MenuConstants.js
  src/components/components-stories.js
  src/hooks/useSetFocus/index.ts
  tsconfig.esm.json
  tsconfig.json
  webpack/published-js-components.js
Labels: PR: Internal 🏠

#989 Install `style-inject` explicitly
  package-lock.json
  package.json
Labels: PR: Internal 🏠

#981 TS-migration: VirtualizedList
  src/components/VirtualizedList/VirtualizedList.tsx
  src/components/VirtualizedList/__stories__/VirtualizedList.stories.mdx
  src/components/VirtualizedList/__tests__/__snapshots__/virtualized-list-snapshot-tests.jest.js.snap
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#964 ExpandCollapse: TS-migration
  src/components/Accordion/AccordionItem/AccordionItem.tsx
  src/components/ExpandCollapse/ExpandCollapse.tsx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#984 TS-migration: EditableInput
  package-lock.json
  package.json
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableInput/EditableInput.tsx
  src/components/EditableInput/EditableInputConstants.ts
  src/components/Heading/Heading.tsx
  src/hooks/useStyle.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#931 AvatarGroup Typescript migration
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/AvatarBadge.tsx
  src/components/AvatarGroup/AvatarGroup.jsx
  src/components/AvatarGroup/AvatarGroup.tsx
  src/components/AvatarGroup/AvatarGroupCounter.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContent.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.jsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx
  src/components/AvatarGroup/AvatarGroupHelper.ts
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/components/Counter/Counter.tsx
  src/components/Menu/MenuItem/AvatarMenuItem.jsx
  src/components/Menu/MenuItem/AvatarMenuItem.tsx
  src/components/VirtualizedList/VirtualizedList.tsx
  src/hooks/useListenFocusTriggers/index.ts
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#990 Bump monday-ui-styles version to "0.1.144": team icon
  package-lock.json
  package.json
Labels: PR: Icon 💎

#993 support tab index for text field
  src/components/TextField/TextField.tsx
Labels: PR: New Feature 🕹

#994 Display avatar/icon in single value and in options for multi and single
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/dropdown-tests.jest.js
  src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
  src/components/Dropdown/components/ChildrenContent/ChildrenContent.module.scss
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
  src/components/Dropdown/components/option/option.jsx
  src/components/Dropdown/components/singleValue/singleValue.jsx
  src/components/Dropdown/components/singleValue/singleValue.module.scss
Labels: PR: Bugfix 🐛

#1000 SplitButton temp fix - secondary button no click event
  src/components/SplitButton/SplitButton.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1001 Fix: Revert splitButton default props to old-fashioned defaultProps
  src/components/SplitButton/SplitButton.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1005 Feature/sergeyro/split button improve tests
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/SplitButton/__tests__/splitButton-snapshot-tests.jest.js
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
Labels: PR: unreviewed, PR: Internal 🏠

#1006 TS-migration: Flex
  src/components/AvatarGroup/AvatarGroupCounterTooltipContent.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Flex/Flex.jsx
  src/components/Flex/Flex.tsx
  src/components/Flex/FlexConstants.js
  src/components/Flex/FlexConstants.ts
  src/components/Flex/__stories__/Flex.stories.mdx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Internal 🏠

#1003 align usages
  .storybook/preview-head.html
  src/components/AttentionBox/AttentionBox.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableInput/EditableInput.tsx
  src/components/Heading/Heading.scss
  src/components/Heading/Heading.tsx
  src/storybook/styles/typography.scss
  src/styles/typography.scss
Labels: PR: Bugfix 🐛

#1008 Fix attention box icon bug
  src/components/AttentionBox/AttentionBox.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: Bugfix 🐛

#1009 Fix editable heading bug
  src/components/EditableInput/EditableInput.scss
  src/components/Heading/Heading.scss
Labels: PR: Bugfix 🐛

#1012 Heading font
  src/components/Heading/Heading.scss
Labels: PR: Bugfix 🐛

#1014 fix letter spacing in non h1 headers
  src/components/Heading/Heading.scss
Labels: PR: Bugfix 🐛

#999 Support all edge cases for multi select drop with counter (hidden chips in dropdown with defined width edge case)
  src/components/Chips/Chips.module.scss
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
  src/components/Dropdown/hooks/useHiddenOptionsData.js
Labels: PR: Bugfix 🐛

#986 TS-Migration: Reduced amount of ts-ignore
  src/components/Button/Button.tsx
  src/components/Icon/__tests__/all-icons-tests.jest.ts
  src/components/Slider/SelectionIndicator.tsx
  src/components/TextField/TextField.tsx
  src/helpers/key-of.ts
  src/types/ArrayLastElement.ts
  src/types/SplitString.ts
  src/utils/user-agent-utils.ts
  types/window.d.ts
Labels: PR: Internal 🏠

#1007 Fix ability to display dropdown menu inside dialog or modal
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/components/menu/menu.jsx
Labels: PR: Bugfix 🐛

#1016 Hot fix after external PR
  src/components/Button/Button.tsx
  src/components/Icon/__tests__/all-icons-tests.jest.ts
  src/components/Slider/SelectionIndicator.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1020 remove not needed packages
  babel.config.js
  package-lock.json
  package.json
Labels: PR: Dependencies 🛠

#1021 revert changes
  babel.config.js
  package.json
Labels: PR: Bugfix 🐛

#1022 Revert "Interactions tests exports (#1004)"
  plop/component/component-ts.txt
  plop/component/index.js
  src/__tests__/interactions-helper.js
  src/components/Accordion/Accordion/__tests__/accordion.interactions.ts
  src/components/Avatar/__tests__/avatar.jest.tsx
  src/components/Button/Button.tsx
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/chips-tests.jest.tsx
  src/components/Clickable/Clickable.tsx
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/components/Clickable/__tests__/clickable-interactions-tests.js
  src/components/Clickable/__tests__/clickable-tests.jest.tsx
  src/components/ColorPicker/__tests__/ColorPicker.interactions.js
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/combobox-interactions.js
  src/components/DatePicker/DatePicker.tsx
  src/components/Divider/Divider.tsx
  src/components/Dropdown/__tests__/Dropdown.interactions.js
  src/components/GridKeyboardNavigationContext/__tests__/useGridKeyboardNavigationContext.interactions.js
  src/components/Icon/Icons/components/Person.tsx
  src/components/Icon/__tests__/all-icons-tests.jest.ts
  src/components/IconButton/IconButton.tsx
  src/components/Loader/Loader.tsx
  src/components/Menu/Menu/__tests__/menu-interactions.js
  src/components/Search/Search.tsx
  src/components/Slider/__tests__/Slider.interactions.js
  src/components/TextField/TextField.tsx
  src/components/VirtualizedList/VirtualizedList.tsx
  src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.interactions.js
  src/tests/base-tests-utils.ts
  src/tests/constants.ts
  src/tests/index.ts
  src/tests/interactions-utils.ts
  src/types/VibeComponent.ts
  src/types/index.ts
  src/utils/test-utils.js
  webpack.config.js
Labels: PR: New Feature 🕹

#1023 remove docgen on production build
  babel.config.js
  package.json
Labels: PR: Dependencies 🛠
