Repository mondaycom/vibe, pull requests merged in 2022-01, with the labels that each got.

#423 Add support on consistent API for all the library components for class name and disabled props
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.jsx
  src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.mdx
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/breadcrumbItem-snapshot-tests.jest.js
  src/components/Counter/Counter.jsx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Counter/__tests__/__snapshots__/counter-snapshot-tests.jest.js.snap
  src/components/Label/Label.jsx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.js.snap
  src/components/Loader/Loader.jsx
  src/components/Loader/__tests__/loader-snapshots.jest.js
  src/components/Toggle/Toggle.jsx
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Toggle/__tests__/toggle-snapshot-tests.jest.js
  src/components/Toggle/__tests__/toggle-tests.jest.js
Labels: PR: Bugfix 🐛

#428 Fix combobox and dropdown docs
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/combobox-tests.jest.js
Labels: PR: Documentation 📖

#426 Bugfix : scroll menu if needed
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
Labels: PR: Bugfix 🐛

#432 Enhance use key event
  src/hooks/__tests__/useKeyEvent.jest.js
  src/hooks/useKeyEvent/index.js
Labels: PR: New Feature 🕹

#425 New components docs (tabs sub components and hidden text component)
  src/components/Banner/__stories__/banner.stories.js
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/components/HiddenText/__stories__/HiddenText.stories.mdx
  src/components/Tabs/TabList/__stories__/tab-list.stories.mdx
  src/components/Tabs/TabList/__stories__/tab-list.stories.module.scss
  src/components/Tabs/TabList/__stories__/tabList.stories.js
  src/components/Tabs/TabPanel/__stories__/tab-panel.stories.mdx
  src/components/Tabs/TabPanels/__stories__/tab-panels.stories.mdx
  src/components/Tabs/TabPanels/__stories__/tab-panels.stories.module.scss
  src/components/Tabs/TabPanels/__stories__/tabPanels.stories.js
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/clickable-description/clickable-description.jsx
  src/storybook/components/related-components/descriptions/clickable-description/clickable-description.stories.module.scss
  src/storybook/components/related-components/descriptions/hidden-text-description.jsx
Labels: PR: Documentation 📖

#430 Create an ESM entry
  package.json
  scripts/build-esm.js
  src/published-components.js
  webpack.config.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#431 Infra/orr/update deps
  .eslintrc.json
  .github/workflows/publish-storybook.yml
  .github/workflows/release.yml
  .github/workflows/test-workflow.yml
  .github/workflows/update-icons.yml
  .nvmrc
  .storybook/.babelrc
  .storybook/main.js
  .storybook/preview.js
  __mocks__/fileMock.js
  babel.config.js
  jest.init.js
  package-lock.json
  package.json
  src/components/Accordion/AccordionItem/__stories__/accordionItem.stories.js
  src/components/Combobox/__tests__/combobox-tests.jest.js
  src/components/Dialog/__stories__/dialog.stories-temp
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__tests__/driver.js
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/EditableHeading/EditableHeading.jsx
  src/components/ExpandCollapse/ExpandCollapse.jsx
  src/components/ExpandCollapse/__stories__/expandCollapse.stories.js
  src/components/FormattedNumber/__stories__/formattedNumber.stories.temp
  src/components/HiddenText/__stories__/hiddenText.stories.js
  src/components/List/List.jsx
  src/components/ListTitle/__stories__/listTitle.stories.js
  src/components/Menu/Menu/Menu.jsx
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.jsx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Steps/StepsGalleryHeader.js
  src/components/Tabs/TabsContext/__stories__/tabsContext.stories.js
  src/components/TextWithHighlight/__stories__/textWithHighlight.stories.js
  src/components/Toast/Toast.jsx
  src/components/VirtualizedList/__stories__/virtualizedList.components.js
  src/components/VirtualizedList/virtualized-list-service.js
  src/components/storybook-helpers/index.js
  src/components/storybook-helpers/story-select-icons/story-select-icons.js
  src/helpers/backwardCompatibilityForProperties.js
  src/index.stories.js
  src/storybook/components/section-name/section-name.jsx
  src/storybook/stand-alone-documentaion/change-log/changelog.stories.mdx
  webpack.config.js
Labels: PR: Dependencies 🛠

#434 feat: LearnMore icon
  package-lock.json
  package.json
  src/components/Icon/Icons/components/LearnMore.js
  src/components/Icon/Icons/index.js
Labels: PR: Icon 💎

#436 check that element is there
  src/components/Menu/MenuItem/MenuItem.jsx
Labels: bug, PR: Bugfix 🐛

#437 random story fixes
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.scss
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/Divider/__stories__/Divider.stories.module.scss
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Menu/MenuDivider/__stories__/MenuDivider.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/SplitButton/__stories__/SplitButtonExampleDialog.jsx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.scss
  src/storybook/components/related-components/descriptions/button-group-description.jsx
  src/storybook/components/related-components/descriptions/menu-description.jsx
Labels: PR: Documentation 📖

#438 fix links story controls, add leanylabs as contributors and add few description to props
  src/components/Button/__stories__/button.stories.mdx
  src/components/Link/Link.jsx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/Steps/Steps.jsx
  src/components/Toast/__stories__/toast.stories.mdx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
Labels: PR: Documentation 📖

#439 Fixed code example of 'Menu with 2-depth sub menu'
  src/components/Menu/Menu/__stories__/menu.stories.js
Labels: PR: Documentation 📖

#442 fix: Props passing bug in tabs panel
  src/components/Tabs/TabPanel/__tests__/__snapshots__/tabPanel-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanels/TabPanels.jsx
  src/components/Tabs/TabPanels/TabPanels.scss
  src/components/Tabs/TabPanels/__stories__/tab-panels.stories.mdx
  src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanels/__tests__/tabPanels-snapshot-tests.jest.js
Labels: PR: Bugfix 🐛

#440 Fix stories errors and typos
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/RadioButton/RadioButton.jsx
  src/components/Tipseen/__stories__/tipseen.stories.jsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/storybook/functions/create-component-story.js
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.jsx
Labels: PR: Documentation 📖

#444 use button to clickable
  src/components/EditableHeading/EditableHeading.jsx
Labels: PR: Bugfix 🐛

#445 Storybook actions
  .storybook/main.js
  src/components/Button/__stories__/button.stories.mdx
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
  src/storybook/functions/create-component-story.js
Labels: PR: Documentation 📖

#448 icon button export
  src/components/index.js
Labels: PR: Bugfix 🐛

#452 Fix dialog hideTriggerIgnoreClass prop type to accept array
  src/components/Dialog/Dialog.jsx
Labels: PR: Bugfix 🐛

#453 Fix icon button export
  webpack/published-components.js
Labels: PR: Bugfix 🐛

#443 Adding VirtualizedGrid component
  src/components/VirtualizedGrid/VirtualizedGrid.jsx
  src/components/VirtualizedGrid/VirtualizedGrid.scss
  src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.js
  src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.mdx
  src/components/VirtualizedGrid/__tests__/__snapshots__/virtualizedGrid.jest.js.snap
  src/components/VirtualizedGrid/__tests__/virtualizedGrid.jest.js
  src/components/VirtualizedList/VirtualizedList.jsx
  src/components/VirtualizedList/__stories__/VirtualizedList.stories.mdx
  src/components/index.js
  src/services/virtualized-service.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#457 fix: Loader issues
  src/components/Loader/Loader.jsx
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Loader/__stories__/Loader.stories.scss
  src/storybook/stand-alone-documentaion/welcome/assets/Omri.png
  src/storybook/stand-alone-documentaion/welcome/assets/index.js
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
Labels: PR: Bugfix 🐛

#460 Fix tabs rendering non active tabs
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/TabList/TabList.jsx
  src/components/Tabs/TabPanel/TabPanel.jsx
  src/components/Tabs/TabPanels/TabPanels.jsx
  src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#458 Added optional mapping from action to input props
  plop/general/component-stories-mdx.txt
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.mdx
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.mdx
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/ButtonGroup.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/DialogContentContainer/__stories__/DialogContentContainer.stories.mdx
  src/components/Divider/__stories__/Divider.stories.mdx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Icon/__stories__/Icon.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
  src/components/Menu/MenuItemButton/__stories__/MenuItemButton.stories.mdx
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.mdx
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Tabs/TabPanels/__stories__/tab-panels.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/storybook/functions/create-component-story.js
Labels: PR: Documentation 📖

#456 Feature/hadas/flex
  .storybook/preview.js
  src/components/Flex/Flex.jsx
  src/components/Flex/Flex.module.scss
  src/components/Flex/FlexConstants.js
  src/components/Flex/__stories__/Flex.stories.mdx
  src/components/Flex/__stories__/Flex.stories.module.scss
  src/components/Flex/__tests__/__snapshots__/flex-snapshot-tests.jest.js.snap
  src/components/Flex/__tests__/flex-snapshot-tests.jest.js
  src/components/index.js
  src/constants/positions.js
  src/constants/sizes.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/list.jsx
  src/storybook/components/story-description/story-description.jsx
  src/storybook/components/story-description/story-description.module.scss
Labels: PR: New Feature 🕹

#463 AttentionBox with icon on compact mode support & Docs fixes in attention box and typography
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/AttentionBox/AttentionBox.jsx
  src/components/AttentionBox/AttentionBox.scss
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.js.snap
  src/storybook/components/related-components/descriptions/toast-description.jsx
  src/storybook/stand-alone-documentaion/typography/assets/typographyExample1.png
  src/storybook/stand-alone-documentaion/typography/assets/typographyExample2.png
Labels: PR: Bugfix 🐛

#465 feat: export and align hooks exposure
  scripts/build-esm.js
  src/hooks/index.js
  src/index.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#466 Call resetAfterIndices instead of resetAfterIndex
  src/components/VirtualizedGrid/VirtualizedGrid.jsx
Labels: PR: Bugfix 🐛

#424 feat(slider): create new component - Slider
  jest.config.js
  jest/jest.setup.js
  jest/utils.js
  package-lock.json
  package.json
  src/components/Slider/SelectionIndicator.jsx
  src/components/Slider/Slider.jsx
  src/components/Slider/Slider.scss
  src/components/Slider/SliderBase/SliderBase.jsx
  src/components/Slider/SliderBase/SliderBase.scss
  src/components/Slider/SliderBase/SliderFilledTrack.jsx
  src/components/Slider/SliderBase/SliderRail.jsx
  src/components/Slider/SliderBase/SliderThumb.jsx
  src/components/Slider/SliderBase/SliderTrack.jsx
  src/components/Slider/SliderConstants.js
  src/components/Slider/SliderContext.js
  src/components/Slider/SliderHelpers.js
  src/components/Slider/SliderHooks.js
  src/components/Slider/SliderInfix.jsx
  src/components/Slider/SliderInfixHooks.jsx
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Slider/__stories__/Slider.stories.scss
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-snapshot-tests.jest.js.snap
  src/components/Slider/__tests__/slider-helpers-tests.jest.js
  src/components/Slider/__tests__/slider-non-ranged-tests.jest.js
  src/components/Slider/__tests__/slider-ranged-tests.jest.js
  src/components/Slider/__tests__/slider-snapshot-tests.jest.js
  src/components/Slider/__tests__/slider-tests.utils.js
  src/components/index.js
  src/constants/general.js
  src/constants/index.js
  src/helpers/testid-helper.js
  src/published-components.js
  src/storybook/decorators/vertical-stories.jsx
  src/storybook/index.js
  src/utils/dom-event-utils.js
Labels: PR: New Feature 🕹

#461 Added useGridKeyboardNavigation
  plop/stories/index.js
  src/hooks/index.js
  src/hooks/useFullKeyboardListeners.js
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.scss
  src/hooks/useGridKeyboardNavigation/__tests__/gridKeyboardNavigationHelper.jest.js
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/gridKeyboardNavigationHelper.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
Labels: PR: New Feature 🕹

#462 Added GridKeyboardNavigationContext
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.mdx
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.scss
  src/components/GridKeyboardNavigationContext/__tests__/GridKeyboardNavigationContext.jest.js
  src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
  src/components/GridKeyboardNavigationContext/helper.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#468 Feature/ornu/virtualizedgrid/Fix rows and columns calculations
  src/components/VirtualizedGrid/VirtualizedGrid.jsx
  src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.js
Labels: PR: Bugfix 🐛

#469 Focus on editing editable header
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/EditableHeading/__tests__/editableHeading.jest.js
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
Labels: PR: Bugfix 🐛

#470 feat: added 'onInputChange' property to Dropdown
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
Labels: PR: New Feature 🕹

#471 feat: fix lint and absolute paths
  .eslintrc.js
  package-lock.json
  src/components/Avatar/__tests__/avatar-snapshot-tests.jest.js
  src/components/BreadcrumbsBar/BreadcrumbsBar.jsx
  src/components/Counter/__tests__/counter-tests.jest.js
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/EditableHeading/__tests__/editableHeading.jest.js
  src/components/EditableInput/EditableInput.jsx
  src/components/ExpandCollapse/__stories__/expandCollapse.stories.js
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
  src/components/GridKeyboardNavigationContext/__tests__/GridKeyboardNavigationContext.jest.js
  src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
  src/components/Heading/Heading.jsx
  src/components/Label/__tests__/label-snapshot-tests.jest.js
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/components/MultiStepIndicator/__tests__/multiStepIndicator-snapshot-tests.jest.js
  src/components/ProgressBars/LinearProgressBar/__tests__/linearProgressBar-snapshot-tests.jest.js
  src/components/RadioButton/__tests__/radioButton-tests.jest.js
  src/components/Slider/Slider.jsx
  src/components/Slider/SliderInfix.jsx
  src/components/SplitButton/__tests__/splitButton-snapshot-tests.jest.js
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
  src/components/Tabs/Tab/__tests__/tab-snapshot-tests.jest.js
  src/components/Tabs/TabList/__tests__/tabList-snapshot-tests.jest.js
  src/components/Tabs/TabPanel/__stories__/tabPanel.stories.js
  src/components/Tabs/TabPanel/__tests__/tabPanel-snapshot-tests.jest.js
  src/components/Tabs/TabPanels/__tests__/tabPanels-snapshot-tests.jest.js
  src/components/Tabs/TabsContext/__stories__/tabsContext.stories.js
  src/components/Tabs/TabsContext/__tests__/tabsContext-snapshot-tests.jest.js
  src/components/TextField/__tests__/textField-snapshot-tests.jest.js
  src/components/Tipseen/__stories__/tipseen.stories.jsx
  src/components/Tipseen/__tests__/tipseen-snapshot-tests.jest.js
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
  src/components/Toast/Toast.jsx
  src/components/Toast/__tests__/toast-snapshot-tests.jest.js
  src/components/Tooltip/__tests__/tooltip-snapshot-tests.jest.js
  src/components/Tooltip/__tests__/tooltip-tests.jest.js
  src/hooks/__tests__/useDebounceEvent.jest.js
  src/hooks/__tests__/useEventListener.jest.js
  src/hooks/__tests__/useKeyEvent.jest.js
  src/hooks/__tests__/useMergeRefs.jest.js
  src/hooks/__tests__/useSetFocus.jest.js
  src/hooks/useGridKeyboardNavigation/__tests__/gridKeyboardNavigationHelper.jest.js
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/gridKeyboardNavigationHelper.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
  src/services/virtualized-service.js
  webpack.config.js
Labels: PR: Internal 🏠

#473 Use resetAfterIndices
  src/components/VirtualizedGrid/VirtualizedGrid.jsx
Labels: PR: Bugfix 🐛

#475 Fix/orr/menu item css fix
  src/components/Menu/MenuItem/MenuItem.scss
  webpack.config.js
Labels: PR: Bugfix 🐛

#467 support keep open mode for dropdown
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
Labels: PR: Bugfix 🐛

#476 Minor fixes in split button story
  src/components/SplitButton/SplitButton.jsx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
Labels: PR: Documentation 📖

#464 Keyboard nav for ColorPicker
  src/components/ColorPicker/ColorPicker.jsx
  src/components/ColorPicker/ColorPickerConstants.js
  src/components/ColorPicker/__stories__/ColorPicker.stories.js
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
  src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.js.snap
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerClearButton.jsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.scss
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.scss
Labels: PR: New Feature 🕹

#472 add option renderer to combobox
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
Labels: PR: New Feature 🕹

#477 Keyboard nav context improvements
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
  src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
  src/components/GridKeyboardNavigationContext/helper.js
Labels: PR: Bugfix 🐛

#480 Added focusItemIndexOnMount to useGridKeyboardNavigation
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
  src/hooks/useFullKeyboardListeners.js
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
Labels: PR: New Feature 🕹

#479 support ref passing for dropdown
  src/components/Dropdown/Dropdown.jsx
Labels: PR: New Feature 🕹

#489 Story for ColorPicker shape prop
  src/components/ColorPicker/__stories__/ColorPicker.stories.js
  src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
Labels: PR: Documentation 📖

#487 fix(slider): change broken padding for slider prefix
  src/components/Slider/Slider.scss
Labels: PR: Bugfix 🐛

#488 Skipping disabled components while navigating
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.mdx
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.scss
  src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
  src/components/GridKeyboardNavigationContext/helper.js
Labels: PR: New Feature 🕹

#493 Disabled indexes for keyboard nav
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
  src/hooks/useGridKeyboardNavigation/__tests__/gridKeyboardNavigationHelper.jest.js
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/gridKeyboardNavigationHelper.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
Labels: PR: New Feature 🕹

#492 Menu item small refactor
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/Menu/hooks/useMenuKeyboardNavigation.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
Labels: PR: Internal 🏠

#496 feature/yarden/dropdown-max-height
  src/components/Dropdown/Dropdown.jsx
Labels: PR: Bugfix 🐛

#495 fix close when click outside in drop down and display correct options when delete
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
Labels: PR: Bugfix 🐛

#500 Fixed menu item hover
  src/components/Menu/MenuItem/MenuItem.jsx
Labels: PR: Bugfix 🐛

#499 Support placeholder in drop down with multi state
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/Dropdown/components/ValueContainer/ValueContainer.module.scss
Labels: PR: Bugfix 🐛

#503 Fix drop down counter in multi state with single line
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/Dropdown/hooks/useHiddenOptionsData.js
Labels: PR: Bugfix 🐛
