Repository mondaycom/vibe, pull requests merged in 2022-06, with the labels that each got.

#689 Feature/sergeyro/hooks plop improve
  plop/hooks/dummy-component.txt
  plop/hooks/hook-story-style.txt
  plop/hooks/hook-story.txt
  plop/hooks/hook.txt
  plop/hooks/index.js
  webpack/published-components.js
Labels: PR: reviewed-approved, PR: Internal 🏠

#692 update version of storybook
  .storybook/preview.js
  package-lock.json
  package.json
Labels: PR: Internal 🏠

#690 feat/Chris/ make Avatar initials text styling customisable
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/AvatarContent.jsx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.scss
Labels: PR: New Feature 🕹

#697 * Update version "monday-ui-style": "0.1.118",
  package-lock.json
  package.json
Labels: PR: New Feature 🕹

#698 Feature/yonatanari/add shadow xs example
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.jsx
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-levels.jsx
  src/styles/global-css-settings.scss
  src/styles/theme-mixin.scss
Labels: PR: New Feature 🕹

#699 Fix: Add prop to preserve radio button on select behaviour with children
  src/components/RadioButton/RadioButton.jsx
Labels: PR: Bugfix 🐛

#705 fix button tooltip hidden when stop hovering + tipseen useless wrapper
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.js.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Tipseen/Tipseen.jsx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-snapshot-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-snapshot-tests.jest.js
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#708 Feature/sergeyro/plop component fix
  plop/component/component-js.txt
  plop/component/component-scss.txt
  plop/component/index.js
  plop/general/component-snapshot-tests-jest.txt
  plop/general/component-stories-mdx.txt
  plop/general/component-stories-scss.txt
  plop/general/component-tests-jest.txt
Labels: PR: reviewed-approved, PR: Internal 🏠

#709 Avatar custom size by classname
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.scss
  src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.js.snap
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: New Feature 🕹

#713 Jest snapshot css modules
  __mocks__/styleMock.js
  jest.config.js
  package-lock.json
  package.json
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Flex/__tests__/__snapshots__/flex-snapshot-tests.jest.js.snap
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
  src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
Labels: PR: Internal 🏠

#718 feat(storybook): enable storybook performance addon
  .storybook/preview.js
Labels: PR: Internal 🏠

#719 feat(storybook): memory stats for stories
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/storybook/decorators/memory-stats.jsx
  src/storybook/functions/memory-stats/index.js
  src/storybook/functions/memory-stats/memory-stats-lib.js
  src/storybook/index.js
Labels: PR: Internal 🏠

#725 Clickable: ariaHasPopup prop
  src/components/Clickable/Clickable.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#727 Butotn inset focus style
  package-lock.json
  package.json
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#729 add max length as a prop
  src/components/EditableHeading/EditableHeading.jsx
Labels: PR: Bugfix 🐛

#730 dropdown with mandatory default values
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/driver.js
  src/components/Dropdown/__tests__/dropdown-tests.jest.js
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
Labels: PR: New Feature 🕹

#731 fix clickable PropType and inset focus for heading compoennt
  src/components/Clickable/Clickable.jsx
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/EditableHeading.scss
Labels: PR: Bugfix 🐛
