Repository mondaycom/vibe, pull requests merged in 2022-08, with the labels that each got.

#799 allow disable label animation on radio button
  src/components/RadioButton/RadioButton.jsx
  src/components/RadioButton/RadioButton.scss
  src/components/RadioButton/__tests__/__snapshots__/radioButton-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#772 New disabled-text-color tokens, component disabled update.
  package-lock.json
  package.json
  src/components/Chips/__stories__/chips.stories.scss
Labels: PR: New Feature 🕹

#778 Use motion tokens on ExpandCollapse.scss
  src/components/ExpandCollapse/ExpandCollapse.scss
Labels: PR: New Feature 🕹

#781 Use motion tokens on Checkbox.scss
  src/components/Checkbox/Checkbox.scss
Labels: PR: New Feature 🕹

#785 Use motion tokens on Dropdown.scss and dropdown/menu.scss
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/components/menu/menu.scss
Labels: PR: New Feature 🕹

#784 Feature/yonatanari/motion tokens counter
  src/components/Counter/Counter.scss
Labels: PR: New Feature 🕹

#789 Use motion tokens on StepIndicator.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
Labels: PR: New Feature 🕹

#782 Use motion tokens on Chips.module.scss
  src/components/Chips/Chips.module.scss
Labels: PR: New Feature 🕹

#800 Fix h1 style gaps in Editable heading edit mode.
  src/components/EditableInput/EditableInput.jsx
  src/components/Heading/Heading.jsx
Labels: PR: Bugfix 🐛

#806 Use motion tokens on Skeleton.scss
  src/components/Skeleton/Skeleton.scss
Labels: PR: New Feature 🕹

#790 Use motion tokens on LinearProgressBar.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
Labels: PR: New Feature 🕹

#795 Use motion tokens on RadioButton.scss
  src/components/RadioButton/RadioButton.scss
Labels: PR: New Feature 🕹

#801 Use motion tokens on Tab.scss
  src/components/Tabs/Tab/Tab.scss
Labels: PR: New Feature 🕹

#786 Use motion tokens on Label.scss
  src/components/Label/Label.scss
Labels: PR: New Feature 🕹

#805 Use motion tokens on TabPanels.scss
  src/components/Tabs/TabPanels/TabPanels.scss
Labels: PR: New Feature 🕹

#803 Use motion tokens on Toggle.scss
  src/components/Toggle/Toggle.scss
Labels: PR: New Feature 🕹

#802 Use motion tokens on TextField.scss
  src/components/TextField/TextField.scss
Labels: PR: New Feature 🕹

#798 Use motion tokens on Steps.scss
  src/components/Steps/Steps.scss
Labels: PR: New Feature 🕹

#797 Use motion tokens on SplitButton.scss
  src/components/SplitButton/SplitButton.scss
Labels: PR: New Feature 🕹

#796 Use motion tokens on SliderBase.scss
  src/components/Slider/SliderBase/SliderBase.scss
Labels: PR: New Feature 🕹

#810 remove console.log
  src/hooks/useActiveDescendantListFocus/index.js
Labels: PR: Bugfix 🐛

#813 fix focus indicator to inset
  src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
Labels: PR: Bugfix 🐛

#814 Fix useKeyEvent imports
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.js
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.jsx
Labels: PR: unreviewed, PR: Internal 🏠

#815 Avatar: prevent default (scroll) on click via space
  src/components/Avatar/Avatar.jsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#816 Add Cursor not-allowed to disabled checkbox
  src/components/Checkbox/Checkbox.scss
Labels: PR: New Feature 🕹

#818 Fix icon button size
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/Button/ButtonConstants.js
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#811 Update easing tokens
  src/components/Button/Button.scss
  src/components/Checkbox/Checkbox.scss
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/components/menu/menu.scss
  src/components/ExpandCollapse/ExpandCollapse.scss
  src/components/MenuButton/MenuButton.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/RadioButton/RadioButton.scss
  src/components/Skeleton/Skeleton.scss
  src/components/Slider/SliderBase/SliderBase.scss
  src/components/SplitButton/SplitButton.scss
  src/components/Steps/Steps.scss
  src/components/TextField/TextField.scss
  src/components/Toggle/Toggle.scss
Labels: PR: New Feature 🕹

#817 Add missing prop bind: marginBottom in Box story
  src/components/Box/__stories__/Box.stories.mdx
Labels: PR: Bugfix 🐛

#821 Test-utils ELEMENT_TYPES extended
  src/utils/test-utils.js
Labels: PR: unreviewed, PR: Internal 🏠

#827 Update h1 example to Poppins
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
Labels: documentation, PR: Bugfix 🐛

#833 add support on pass class name to reference in tooltip
  src/components/Tooltip/Tooltip.jsx
Labels: PR: Bugfix 🐛

#831 IconButton: add showTooltip prop
  src/components/IconButton/IconButton.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#835 Feature/sergeyro/loader a11y attributes
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Loader/Loader.jsx
  src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: New Feature 🕹

#829 Feature/sergeyro/dropdown item tooltip
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/option/option.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#836 BreadcrumbContent: link and button roles are added
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#828 AttentionBox - close icon button instead of icon
  src/components/AttentionBox/AttentionBox.jsx
  src/components/AttentionBox/AttentionBox.scss
  src/components/AttentionBox/AttentionBoxConstants.js
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: New Feature 🕹

#840 Fix avatar group dependencies without effect behivour
  src/components/AvatarGroup/AvatarGroupCounter.jsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.jsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.js
Labels: PR: Bugfix 🐛

#847 Export content color
  src/utils/colors-utils.js
Labels: PR: New Feature 🕹

#848 Support new dropdown state for displaying menu inside scrollable dialog
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/Control/Control.jsx
  src/components/Dropdown/components/menu/menu.jsx
  src/components/Dropdown/components/menu/menu.scss
Labels: PR: New Feature 🕹

#849 Fix close on scroll in inside scroll state
  src/components/Dropdown/Dropdown.jsx
Labels: PR: Bugfix 🐛
