Repository mondaycom/vibe, pull requests merged in 2022-02, with the labels that each got.

#502 Menu enhancements
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/Menu/hooks/__tests__/useLastNavigationDirection.jest.js
  src/components/Menu/Menu/hooks/useLastNavigationDirection.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
  src/components/Menu/MenuItem/MenuItem.scss
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/hooks/useFullKeyboardListeners.js
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
  src/hooks/useListKeyboardNavigation.js
Labels: PR: New Feature 🕹

#510 Dropdown with multi - placeholder show condition fix
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
  src/components/Dropdown/components/ValueContainer/ValueContainer.module.scss
Labels: PR: Bugfix 🐛

#505 Fix combobox docs
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__stories__/OptionRenderer.jsx
  src/components/Combobox/__stories__/assets/person1.png
  src/components/Combobox/__stories__/assets/person2.png
  src/components/Combobox/__stories__/assets/person3.png
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.scss
Labels: PR: Documentation 📖

#511 fix/yarden/dropdown-multi-lint-and-tests-fixes
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
Labels: PR: Internal 🏠

#509 ColorPicker - white selected icon, even not on multi selection
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.scss
Labels: PR: New Feature 🕹

#512 Disabling activeIndex after a non-keyboard interaction
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
Labels: PR: New Feature 🕹

#516 feat: move dependencies to correct area
  .storybook/addons.js
  .storybook/main.js
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#514 fix support on checkbox click while shift is pressed on firefox browser
  package-lock.json
  package.json
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.js.snap
  src/components/Checkbox/__tests__/__snapshots__/checkbox.jest.js.snap
  src/components/Checkbox/__tests__/checkbox-tests.jest.js
  src/components/Checkbox/__tests__/checkbox.jest.js
  src/utils/user-agent-utils.js
Labels: PR: Bugfix 🐛

#482 Add typography variables
  src/components/AttentionBox/AttentionBox.scss
  src/components/Avatar/AvatarContent.scss
  src/components/Button/Button.scss
  src/components/FieldLabel/FieldLabel.scss
  src/components/FormattedNumber/FormattedNumber.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/TextField/TextField.scss
  src/components/storybook-helpers/description-label/description-label.scss
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
  src/storybook/styles/typography.scss
  src/styles/typography.scss
Labels: PR: Internal 🏠

#517 Tabs focus issue
  src/components/Tabs/Tab/Tab.jsx
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/styles/states.scss
  webpack/published-components.js
Labels: PR: Bugfix 🐛

#518 When click on checkbox with shift pressed, shift key is not true in the manual all checkbox events (even if it was true in the original event)
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/__tests__/checkbox-tests.jest.js
  src/components/Checkbox/hooks/useSupportFirefoxLabelClick.jsx
Labels: PR: Bugfix 🐛

#520 Revert " Add typography variables"
  src/components/AttentionBox/AttentionBox.scss
  src/components/Avatar/AvatarContent.scss
  src/components/Button/Button.scss
  src/components/FieldLabel/FieldLabel.scss
  src/components/FormattedNumber/FormattedNumber.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/TextField/TextField.scss
  src/components/storybook-helpers/description-label/description-label.scss
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
  src/storybook/styles/typography.scss
  src/styles/typography.scss
Labels: PR: Bugfix 🐛

#521 Replace typography source to monday-ui-style font variables
  src/components/AttentionBox/AttentionBox.scss
  src/components/Avatar/AvatarContent.scss
  src/components/Button/Button.scss
  src/components/FieldLabel/FieldLabel.scss
  src/components/FormattedNumber/FormattedNumber.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/TextField/TextField.scss
  src/components/storybook-helpers/description-label/description-label.scss
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
  src/storybook/styles/typography.scss
  src/styles/typography.scss
Labels: PR: New Feature 🕹

#523 Fix icon button and drop down stories
  src/components/Button/__stories__/button.stories.mdx
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Flex/Flex.jsx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__stories__/assets/person1.png
  src/components/IconButton/__stories__/iconButton.stories.module.scss
Labels: PR: Bugfix 🐛

#529 Add virtualized list ref
  src/components/VirtualizedList/VirtualizedList.jsx
  src/services/virtualized-service.js
Labels: PR: New Feature 🕹

#528 add divider to combo box categories
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
Labels: PR: New Feature 🕹

#533 Add chips colors story
  src/components/Chips/Chips.jsx
  src/components/Chips/Chips.scss
  src/components/Chips/__stories__/chips.stories.mdx
Labels: PR: New Feature 🕹

#532 Dropdown - add isOptionSelected prop
  src/components/Dropdown/Dropdown.jsx
Labels: PR: New Feature 🕹

#534 Add chips colors story fixes
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Flex/Flex.jsx
  src/components/Flex/Flex.module.scss
  src/constants/positions.js
Labels: PR: Bugfix 🐛

#506 Menu grid item
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.scss
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__stories__/Menu.stories.module.scss
  src/components/Menu/Menu/__stories__/menu.stories.js
  src/components/Menu/Menu/hooks/__tests__/useAdjacentSelectableMenuIndex.jest.js
  src/components/Menu/Menu/hooks/__tests__/useLastNavigationDirection.jest.js
  src/components/Menu/Menu/hooks/useAdjacentSelectableMenuIndex.jsx
  src/components/Menu/Menu/hooks/useLastNavigationDirection.jsx
  src/components/Menu/Menu/hooks/useMenuKeyboardNavigation.jsx
  src/components/Menu/MenuGridItem/MenuGridItem.jsx
  src/components/Menu/MenuGridItem/MenuGridItem.scss
  src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.js
  src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.mdx
  src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.scss
  src/components/Menu/MenuGridItem/__tests__/__snapshots__/menuGridItem-snapshot-tests.jest.js.snap
  src/components/Menu/MenuGridItem/__tests__/menuGridItem-snapshot-tests.jest.js
  src/components/Menu/MenuGridItem/__tests__/menuGridItem-tests.jest.js
  src/components/Menu/MenuGridItem/__tests__/useFocusGridItemByActiveStatus.jest.js
  src/components/Menu/MenuGridItem/__tests__/useMenuGridItemNavContext.jest.js
  src/components/Menu/MenuGridItem/useFocusGridItemByActiveStatus.jsx
  src/components/Menu/MenuGridItem/useMenuGridItemNavContext.jsx
  src/components/Menu/MenuItem/hooks/useMenuItemMouseEvents.js
  src/components/Menu/MenuItemButton/__stories__/MenuItemButton.stories.mdx
  src/components/index.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#530 tooltip: removing border from tooltip arrow + adding themes to storybook
  src/components/Tooltip/Tooltip.scss
  src/components/Tooltip/__stories__/tooltip.stories.mdx
Labels: PR: Bugfix 🐛

#535 Fix combobox drawer width
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/Combobox.scss
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#538 Element type issues
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Flex/Flex.jsx
  src/components/Flex/__tests__/__snapshots__/flex-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#539 Flex types
  src/components/Flex/Flex.jsx
Labels: PR: Bugfix 🐛

#540 Fix font load
  .storybook/preview-head.html
Labels: PR: Bugfix 🐛

#541 Set version
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#542 remove react button
  package-lock.json
  package.json
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/TextField.jsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#543 remove react aria dependecies
  package-lock.json
  package.json
  src/components/Menu/Menu/Menu.jsx
  src/components/Menu/MenuGridItem/MenuGridItem.jsx
  src/components/Switch/Switch.js
  src/components/Switch/Switch.module.scss
  src/components/Switch/index.js
  src/components/Tabs/TabList/TabList.jsx
  src/components/Toggle/MockToggle.jsx
  src/components/Toggle/Toggle.jsx
  src/components/Toggle/Toggle.scss
  src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
  src/components/Toggle/__tests__/toggle-tests.jest.js
  src/hooks/createEventHandler.js
  src/hooks/useFocusWithin.js
  src/hooks/useKeyboard.js
  src/hooks/useToggle.js
Labels: PR: Bugfix 🐛

#546 Displaying focus properly in toggle component
  src/components/Switch/Switch.js
  src/components/Switch/hooks/useSwitchChecked.jsx
  src/components/Toggle/Toggle.scss
Labels: PR: Bugfix 🐛

#545 Better support for useDocumentEventListeners on Menu components
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
  src/components/GridKeyboardNavigationContext/__tests__/GridKeyboardNavigationContext.jest.js
  src/components/Menu/Menu/__stories__/menu.stories.js
  src/components/Menu/MenuGridItem/MenuGridItem.jsx
  src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.mdx
  src/components/Menu/MenuGridItem/__tests__/useFocusGridItemByActiveStatus.jest.js
  src/components/Menu/MenuGridItem/useFocusGridItemByActiveStatus.jsx
  src/components/Menu/MenuItem/MenuItem.jsx
Labels: PR: Bugfix 🐛

#548 Fix toggle on change params
  src/components/Switch/hooks/useSwitchChecked.jsx
  src/components/Toggle/__tests__/toggle-tests.jest.js
Labels: PR: Bugfix 🐛

#536 combobox disable no result on loading
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/__tests__/combobox-tests.jest.js
Labels: PR: Bugfix 🐛

#551 support passing tooltip content without disabled mode
  src/components/Menu/MenuItem/MenuItem.jsx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
Labels: PR: New Feature 🕹

#554 Add support on avatar in chip component
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.scss
  src/components/Avatar/AvatarBadge.scss
  src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.js.snap
  src/components/Chips/Chips.jsx
  src/components/Chips/Chips.scss
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
  src/components/Chips/__tests__/chips-snapshot-tests.jest.js
Labels: PR: New Feature 🕹

#556 Expose use is overflowing hook
  src/hooks/index.js
  webpack/published-components.js
Labels: PR: New Feature 🕹

#555 Fix stories
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/ButtonGroup/ButtonGroup.jsx
  src/components/ButtonGroup/__stories__/buttonGroup.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.scss
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/SplitButton/SplitButton.jsx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Steps/Steps.scss
  src/components/Steps/__stories__/steps.stories.mdx
  src/storybook/components/story-description/story-description.jsx
  src/storybook/functions/create-component-story.js
Labels: documentation, PR: Documentation 📖

#557 Support Heading highlight text
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/Heading/Heading.jsx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/TextWithHighlight/TextWithHighlight.jsx
  src/components/TextWithHighlight/TextWithHighlight.scss
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/components/TextWithHighlight/__tests__/__snapshots__/textWithHighlight.jest.js.snap
Labels: PR: New Feature 🕹

#537 Fix tabs list bug - visible focus displayed when clicking out side and then clicking on one tab
  src/components/Tabs/Tab/Tab.jsx
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/TabList.jsx
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
Labels: PR: Bugfix 🐛

#563 Add color prop to Heading and Editable Heading
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableInput/EditableInput.jsx
  src/components/Heading/Heading.jsx
  src/hooks/useStyle.js
Labels: PR: New Feature 🕹

#565 Editable heading callback on blur ignore
  src/components/EditableHeading/EditableHeading.jsx
  src/components/EditableInput/EditableInput.jsx
Labels: PR: Bugfix 🐛
