Repository mondaycom/vibe, pull requests merged in 2023-02, with the labels that each got.

#1082 Add support for "without margin" prop in Divider component
  src/components/Divider/Divider.scss
  src/components/Divider/Divider.tsx
  src/components/Divider/__stories__/Divider.stories.module.scss
Labels: PR: New Feature 🕹

#1090 update Figtree and Poppins
  .storybook/preview-head.html
  README.md
  package-lock.json
  package.json
  src/components/Heading/Heading.scss
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
  src/storybook/styles/typography.scss
Labels: PR: New Feature 🕹

#1091 Fix docs
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
Labels: PR: Documentation 📖

#1093 feat(ListItemIcon): export icon size
  src/components/ListItemIcon/ListItemIcon.tsx
  src/components/ListItemIcon/ListItemIconConstants.ts
Labels: PR: Bugfix 🐛

#1094 Modal: Add zIndex prop
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1092 Add support for combobox optionClassName & combobox dark mode fixes
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/Combobox.scss
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.scss
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
Labels: PR: New Feature 🕹

#1095 fix: Search component onChange callback type
  src/components/Search/Search.tsx
Labels: PR: reviewed-approved, PR: Bugfix 🐛

#1087 Counter: counterClassName added
  src/components/Counter/Counter.scss
  src/components/Counter/Counter.tsx
  src/components/Counter/__tests__/__snapshots__/counter-snapshot-tests.jest.tsx.snap
  src/components/Counter/__tests__/counter-snapshot-tests.jest.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1096 Feature/sergeyro/fix modal z index prop
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#1098 Fix modal title font family
  src/components/ModalHeader/ModalHeader.module.scss
Labels: PR: Bugfix 🐛

#1097 Add founding designers to welcome page
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/contributors.tsx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.scss
Labels: documentation, PR: Documentation 📖

#1100 Fix modal zIndex breaking change
  src/components/Modal/Modal.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1099 Feature/sergeyro/remove storybook styles overrides
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.scss
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.scss
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.scss
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__stories__/chips.stories.scss
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.scss
  src/components/RadioButton/__stories__/radioButton.stories.js
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.scss
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.scss
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Steps/__stories__/steps.stories.scss
  src/components/Tipseen/__stories__/tipseen.stories.jsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.scss
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toast/__stories__/toast.stories.scss
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.scss
Labels: PR: unreviewed, PR: Documentation 📖

#1103 Tooltip.hideShowTriggers - static property
  src/components/Avatar/Avatar.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
  src/components/Dropdown/components/Control/Control.jsx
  src/components/MenuButton/MenuButton.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1105 Set chips clickable behavior as default instead of extra prop for backward support and clearer API
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/chips-tests.jest.tsx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
Labels: PR: Bugfix 🐛

#1113 Fix responsive dos and dont's by change min width and fix tipseen story
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.scss
  src/storybook/components/component-rules/component-rules.jsx
  src/storybook/components/component-rules/component-rules.scss
  src/styles/global-css-settings.scss
Labels: PR: Documentation 📖

#1086 Add disabled param to editable input component
  src/components/EditableInput/EditableInput.tsx
  src/components/EditableInput/__tests__/__snapshots__/editableInput.jest.js.snap
Labels: PR: New Feature 🕹

#1106 Feature/sergeyro/steps story clickable example
  src/components/Steps/Steps.scss
  src/components/Steps/StepsCommand.tsx
  src/components/Steps/__stories__/helpers.js
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Steps/__stories__/steps.stories.scss
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Tipseen/TipseenWizard.tsx
Labels: PR: unreviewed, PR: Documentation 📖

#1118 Fix modal components exposion
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#1115 Feature/sergeyro/modal fix rerendering issues
  src/components/Modal/Modal.tsx
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/useShowHideModal.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1110 useHover - hook story
  src/components/Chips/Chips.tsx
  src/hooks/index.js
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
  src/hooks/useHover/__stories__/useHover.stories.mdx
  src/hooks/useHover/__stories__/useHover.stories.module.scss
  src/hooks/useHover/useHover.ts
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Documentation 📖

#1112 useClickableProps - hook story
  src/components/Chips/Chips.tsx
  src/components/Clickable/Clickable.tsx
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/hooks/index.js
  src/hooks/useClickableProps/__stories__/useClickableProps.stories.mdx
  src/hooks/useClickableProps/__stories__/useClickableProps.stories.scss
  src/hooks/useClickableProps/useClickableProps.ts
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Documentation 📖

#1102 EditableHeading and Checkbox typescript migration
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.tsx.snap
  src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.tsx
  src/components/Checkbox/__tests__/checkbox-tests.jest.tsx
  src/components/EditableHeading/EditableHeading.tsx
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.tsx.snap
  src/components/EditableHeading/__tests__/editableHeading.jest.tsx
  src/components/EditableInput/EditableInput.tsx
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#1123 Support links for related components in storybook
  src/storybook/components/information-box-title/information-box-title.jsx
  src/storybook/components/information-box-title/information-box-title.scss
  src/storybook/components/information-box/information-box.jsx
  src/storybook/components/related-component/related-component.jsx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/alert-banner-description.jsx
  src/storybook/components/related-components/descriptions/attention-box-description.jsx
  src/storybook/components/related-components/descriptions/avatar-description.jsx
  src/storybook/components/related-components/descriptions/avatar-group-description.jsx
  src/storybook/components/related-components/descriptions/breadcrumbs-description.jsx
  src/storybook/components/related-components/descriptions/button-description.jsx
  src/storybook/components/related-components/descriptions/button-group-description.jsx
  src/storybook/components/related-components/descriptions/checkbox-description.jsx
  src/storybook/components/related-components/descriptions/chips-description.jsx
  src/storybook/components/related-components/descriptions/combobox-description.jsx
  src/storybook/components/related-components/descriptions/counter-description.jsx
  src/storybook/components/related-components/descriptions/dialog-content-container.jsx
  src/storybook/components/related-components/descriptions/divider.jsx
  src/storybook/components/related-components/descriptions/dropdown-description.jsx
  src/storybook/components/related-components/descriptions/editable-heading-description.jsx
  src/storybook/components/related-components/descriptions/flex-description.jsx
  src/storybook/components/related-components/descriptions/heading-description.jsx
  src/storybook/components/related-components/descriptions/hidden-text-description.jsx
  src/storybook/components/related-components/descriptions/icon-button-description.jsx
  src/storybook/components/related-components/descriptions/label-description.jsx
  src/storybook/components/related-components/descriptions/list-description.jsx
  src/storybook/components/related-components/descriptions/menu-button-description.jsx
  src/storybook/components/related-components/descriptions/menu-description.jsx
  src/storybook/components/related-components/descriptions/progress-bar-description.jsx
  src/storybook/components/related-components/descriptions/radio-button-description.jsx
  src/storybook/components/related-components/descriptions/search-description.jsx
  src/storybook/components/related-components/descriptions/skeleton-description.jsx
  src/storybook/components/related-components/descriptions/spinner-description.jsx
  src/storybook/components/related-components/descriptions/split-button-description.jsx
  src/storybook/components/related-components/descriptions/stepper-description.jsx
  src/storybook/components/related-components/descriptions/tab-description.jsx
  src/storybook/components/related-components/descriptions/text-field-description.jsx
  src/storybook/components/related-components/descriptions/tipseen-description.jsx
  src/storybook/components/related-components/descriptions/toast-description.jsx
  src/storybook/components/related-components/descriptions/toggle-description.jsx
  src/storybook/components/related-components/descriptions/tooltip-description.jsx
  src/storybook/components/related-components/descriptions/wizard-description.jsx
Labels: PR: Documentation 📖

#1114 Hook story - useListenFocusTriggers
  src/hooks/index.js
  src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.mdx
  src/hooks/useListenFocusTriggers/index.ts
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Documentation 📖

#1119 Feature/sergeyro/item list with avatar
  src/components/List/__stories__/List.stories.mdx
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/ListItemAvatar/ListItemAvatar.module.scss
  src/components/ListItemAvatar/ListItemAvatar.tsx
  src/components/ListItemAvatar/__tests__/__snapshots__/listItemAvatar.jest.js.snap
  src/components/ListItemAvatar/__tests__/listItemAvatar.jest.js
  src/components/ListItemIcon/ListItemIcon.tsx
  src/components/ListItemIcon/__stories__/ListItemIcon.stories.mdx
  src/components/ListItemIcon/__tests__/__snapshots__/listItemIcon.jest.js.snap
  src/components/ListItemIcon/__tests__/listItemIcon.jest.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1126 Button on color disabled
  src/components/Button/Button.scss
  src/components/Button/__stories__/button.stories.mdx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.tsx
  src/components/Checkbox/__tests__/checkbox-tests.jest.tsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/storybook/components/related-components/descriptions/checkbox-description.jsx
Labels: PR: Bugfix 🐛

#1131 Dialog/Tooltip showOnDialogEnter prop description
  src/components/Dialog/Dialog.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: PR: unreviewed, PR: Documentation 📖

#1136 feature: added isLoading and loadingMessage props into Dropdown
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
Labels: PR: New Feature 🕹

#1137 Radio Button Docs
  src/components/RadioButton/RadioButton.tsx
Labels: PR: New Feature 🕹

#1138 add more docs
  src/components/RadioButton/RadioButton.tsx
Labels: PR: New Feature 🕹

#1139 Fix exported function
  src/hooks/useListenFocusTriggers/index.ts
Labels: PR: Bugfix 🐛

#1140 Fix storybook build
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx
  src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.mdx
Labels: PR: Bugfix 🐛

#1141 Fix invalid hook referemce
  src/hooks/useActiveDescendantListFocus/useActiveDescendantListFocusHooks.ts
Labels: PR: Bugfix 🐛

#1142 Use .nvmrc and npm ci in CI
  .github/workflows/publish-storybook.yml
  .github/workflows/release.yml
  .github/workflows/test-workflow.yml
Labels: PR: Internal 🏠
