Repository mondaycom/vibe, pull requests merged in 2023-08, with the labels that each got.

#1441 chore: expose types for vite and next-based projects
  package.json
Labels: PR: Internal 🏠

#1446 chore: fix internal triggers for deployment
  scripts/release.js
Labels: PR: Internal 🏠

#1449 Fix/hadas/log fix
  src/components/Modal/Modal.tsx
Labels: PR: Bugfix 🐛

#1450 chore: prevent from style injection to explode in server side rendering
  rollup/styleInject.ejs
Labels: PR: Internal 🏠

#1453 Fix letter spacing in legacy heading (temp until we will able to fix in monday ui style)
  src/components/Heading/Heading.module.scss
Labels: PR: Bugfix 🐛

#1455 Update vibe version number manually
  src/components/Heading/Heading.tsx
Labels: PR: New Feature 🕹

#1456 Change vibe version number manually
  src/components/Chips/Chips.tsx
Labels: PR: Bugfix 🐛

#1454 docs: fix Shadows page usage and examples
  src/storybook/stand-alone-documentaion/shadow/shadow.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1457 last manually change for update vibe version?
  src/components/Chips/Chips.tsx
Labels: PR: New Feature 🕹

#1458 package.json fix types exports for icons and root
  package.json
Labels: PR: unreviewed, PR: Bugfix 🐛

#1452 feat(Modal): css changes, add new footer layout
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalContent/ModalContent.module.scss
  src/components/Modal/ModalFooter/ModalFooter.module.scss
  src/components/Modal/ModalFooter/ModalFooterButtons/ModalFooterButtons.tsx
  src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/__snapshots__/modalFooterButtons-snapshot-tests.jest.tsx.snap
  src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/modalFooterButtons-snapshot-tests.jest.tsx
  src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/modalFooterButtons-tests.jest.tsx
  src/components/Modal/ModalHeader/ModalHeader.module.scss
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/ModalHeader/__tests__/modalHeader-snapshot-tests.jest.js
  src/components/Modal/ModalHelper.ts
  src/components/Modal/__stories__/Modal.stories.module.scss
  src/components/Modal/__stories__/Modal.stories.scss
  src/components/Modal/__stories__/helpers.js
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/modal-snapshot-tests.jest.js
  src/components/index.js
  src/tests/constants.ts
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1459 fix: storybookComponents export - include styles
  scripts/build-utils.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#1434 fix(AttentionBox): general improvements + allow ellipsis for overflowin attention box
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.scss
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#1463 Add version to class
  rollup.config.js
  rollup/styleInject.ejs
Labels: PR: Bugfix 🐛

#1464 fix version number as css selector
  rollup.config.js
Labels: PR: Bugfix 🐛

#1466 chore(storybook): upgrade storybook to 6.5.10+ to enable interaction testing on Chromatic
  package-lock.json
  package.json
Labels: PR: unreviewed, PR: Documentation 📖

#1432 feat(Indicator): add new Indicator component to component library
  src/components/Badge/Badge.module.scss
  src/components/Badge/Badge.tsx
  src/components/Badge/BadgeConstants.ts
  src/components/Badge/Indicator/Indicator.module.scss
  src/components/Badge/Indicator/Indicator.tsx
  src/components/Badge/Indicator/IndicatorConstants.ts
  src/components/Badge/Indicator/__tests__/__snapshots__/indicator-snapshot-tests.jest.tsx.snap
  src/components/Badge/Indicator/__tests__/indicator-snapshot-tests.jest.tsx
  src/components/Badge/__stories__/Badge.stories.mdx
  src/components/Badge/__stories__/assets/person.png
  src/components/Badge/__tests__/__snapshots__/badge-snapshot-tests.jest.tsx.snap
  src/components/Badge/__tests__/badge-snapshot-tests.jest.tsx
  src/components/index.js
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/link-description.jsx
  src/tests/constants.ts
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1467 Fix specificity issues in label and in typography in general
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Heading/Heading.module.scss
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__stories__/iconButton.stories.module.scss
  src/components/Label/Label.module.scss
  src/components/Label/Label.tsx
  src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.tsx.snap
  src/components/ListItem/__tests__/__snapshots__/listItem.jest.js.snap
  src/components/ListTitle/__tests__/__snapshots__/listTitle.jest.js.snap
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
  src/components/Modal/ModalContent/__tests__/__snapshots__/modalContent-snapshot-tests.jest.js.snap
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/RadioButton/__tests__/__snapshots__/radioButton-snapshot-tests.jest.tsx.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Text/Text.tsx
  src/components/Text/__tests__/__snapshots__/text-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Title/Title.tsx
  src/components/Title/__tests__/__snapshots__/title-snapshot-tests.jest.js.snap
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/components/Typography/Typography.module.scss
  src/storybook/stand-alone-documentaion/typography-new/text-styles/text-styles.jsx
  src/styles/typography.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1465 feat: <TextField/> add event as a param to onChange callback
  src/components/TextField/TextField.tsx
  src/components/TextField/__tests__/textField-tests.jest.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1468 fix: <TextField> replace icon
  src/components/TextField/TextField.module.scss
  src/components/TextField/assets/Calendar.svg
  src/components/TextField/assets/CalendarInverted.svg
Labels: PR: unreviewed, PR: Bugfix 🐛

#1469 feat(Tipseen): allow tipseen title to have max 2 lines
  src/components/Tipseen/TipseenTitle.tsx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1442 Technical pattern from using dropdown in dialog and modals and support for popupsContainerSelector for displaying dropdown properly in modals
  src/components/Dialog/__stories__/Dialog.stories.mdx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Modal/__stories__/helpers.js
  src/components/Modal/__stories__/modal.stories.mdx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/dialog.jsx
  src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.mdx
Labels: PR: New Feature 🕹

#1439 feat: <List> a11y improvements
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/components/List/List.tsx
  src/components/List/ListConstants.ts
  src/components/List/__tests__/__snapshots__/list.jest.js.snap
  src/components/List/__tests__/list.jest.js
  src/components/List/utils/ListContext.ts
  src/components/List/utils/ListUtils.ts
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/ListItemConstants.ts
  src/components/ListItem/__stories__/ListItem.stories.mdx
  src/components/ListItem/__tests__/__snapshots__/listItem.jest.js.snap
  src/components/ListItem/__tests__/listItem.jest.js
  src/components/ListTitle/ListTitle.tsx
  src/components/ListTitle/__tests__/listTitle.jest.js
  src/constants/keyCodes.js
  src/tests/constants.ts
Labels: PR: unreviewed, PR: New Feature 🕹

#1473 chore: Storybook config cleanup
  .storybook/manager-head.html
  .storybook/preview-head.html
Labels: PR: unreviewed, PR: Internal 🏠

#1444 fix(SplitButton): make menu-opening a11y-compatible
  src/components/Menu/Menu/Menu.tsx
  src/components/SplitButton/SplitButton.tsx
  src/components/SplitButton/SplitButtonMenu/SplitButtonMenu.tsx
  src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/splitButtonMenu-snapshot-tests.jest.tsx.snap
  src/components/SplitButton/SplitButtonMenu/__tests__/splitButtonMenu-snapshot-tests.jest.tsx
  src/components/SplitButton/SplitButtonMenu/__tests__/splitButtonMenu-tests.jest.tsx
  src/components/SplitButton/SplitButtonMenu/__tests__/test-utils.ts
  src/components/SplitButton/__stories__/SplitButtonExampleDialog.jsx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/SplitButton/__tests__/splitButton-snapshot-tests.jest.js
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
  src/components/index.js
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#1472 fix(Menu): `focusIndexOnMount` can focus on an unfocusable item
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/Menu/__tests__/menu.jest.js
  src/components/Menu/Menu/hooks/__tests__/useFocusOnMount.jest.tsx
  src/components/Menu/Menu/hooks/useAdjacentSelectableMenuIndex.tsx
  src/components/Menu/Menu/hooks/useFocusOnMount.tsx
  src/components/Menu/Menu/utils/__tests__/utils.jest.ts
  src/components/Menu/Menu/utils/utils.ts
  src/components/SplitButton/SplitButtonMenu/SplitButtonMenu.tsx
  src/components/SplitButton/SplitButtonMenu/__tests__/splitButtonMenu-snapshot-tests.jest.tsx
  src/components/SplitButton/SplitButtonMenu/__tests__/splitButtonMenu-tests.jest.tsx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/tests/__tests__/test-utils.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1474 chore: Cleanup internal css variables
  src/components/Accordion/Accordion/Accordion.module.scss
  src/components/AlertBanner/AlertBanner.module.scss
  src/components/AlertBanner/AlertBannerButton/AlertBannerButton.module.scss
  src/components/AlertBanner/AlertBannerLink/AlertBannerLink.module.scss
  src/components/AlertBanner/AlertBannerText/AlertBannerText.module.scss
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/Avatar/Avatar.module.scss
  src/components/Button/Button.module.scss
  src/components/Checkbox/Checkbox.module.scss
  src/components/ColorPicker/ColorPicker.module.scss
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerClearButton.module.scss
  src/components/Dialog/DialogContent/DialogContent.module.scss
  src/components/DialogContentContainer/DialogContentContainer.module.scss
  src/components/Dropdown/Dropdown.module.scss
  src/components/EditableHeading/EditableHeading.module.scss
  src/components/EditableInput/EditableInput.module.scss
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.scss
  src/components/Heading/Heading.module.scss
  src/components/Icon/__stories__/Icon.stories.scss
  src/components/Label/Label.module.scss
  src/components/Link/Link.module.scss
  src/components/Menu/MenuDivider/MenuDivider.module.scss
  src/components/Menu/MenuItem/MenuItem.module.scss
  src/components/MenuButton/MenuButton.module.scss
  src/components/Skeleton/Skeleton.module.scss
  src/components/Skeleton/SkeletonVariables.scss
  src/components/Slider/SliderBase/SliderBase.module.scss
  src/components/SplitButton/SplitButton.module.scss
  src/components/SplitButton/__stories__/splitButton.stories.scss
  src/components/Steps/StepsCommand.module.scss
  src/components/TextField/TextField.module.scss
  src/components/Tipseen/__stories__/tipseen.stories.scss
  src/components/Toggle/MockToggle.module.scss
  src/components/Tooltip/Tooltip.module.scss
  src/general.scss
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.scss
  src/index.js
  src/storybook/stand-alone-documentaion/round-corners/corners-settings/corner-settings.scss
  src/storybook/stand-alone-documentaion/round-corners/rounded-corner/rounded-corner.module.scss
  src/storybook/stand-alone-documentaion/shadow/drag-shadow-example/drag-shadow-example.module.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.scss
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-levels.scss
  src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-sizes.scss
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
  src/storybook/stand-alone-documentaion/welcome/ability-description/ability-description.scss
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.scss
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
  src/storybook/stand-alone-documentaion/welcome/principle/principle.scss
  src/storybook/stand-alone-documentaion/welcome/principles/principles.scss
  src/storybook/styles/mixins.scss
  src/styles/global-css-settings.scss
  src/styles/themes.scss
  src/styles/typography.scss
Labels: PR: unreviewed, PR: Internal 🏠

#1477 add null check to List component for support undef children
  src/components/List/utils/ListUtils.ts
Labels: PR: Bugfix 🐛

#1475 Api changes/hadas/next
  package.json
  rollup.config.js
  src/next/next.ts
  src/styles/typography.scss
Labels: PR: New Feature 🕹

#1479 Fix h6 size in legacy heading
  src/components/LegacyHeading/LegacyHeading.module.scss
Labels: PR: Bugfix 🐛

#1482 Upgrade monday-ui-style
  package-lock.json
  package.json
Labels: PR: Dependencies 🛠

#1481 fix: removing unneeded aria-label from TextField's error message
  src/components/TextField/TextField.tsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1484 feat: <ListItemIcon>, <ListItemAvatar> component props
  src/components/ListItemAvatar/ListItemAvatar.tsx
  src/components/ListItemIcon/ListItemIcon.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1485 fix: <List> id generation
  src/components/List/List.tsx
  src/components/List/utils/ListUtils.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1486 feat: add configurable aria-describedby attribute to the link element
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/Link/Link.tsx
  src/components/Link/__tests__/__snapshots__/link-snapshot-tests.jest.tsx.snap
  src/components/Link/__tests__/link-snapshot-tests.jest.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#1490 feat: <Toggle>, <Switch> refForwarding
  src/components/Switch/Switch.tsx
  src/components/Toggle/Toggle.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1488 feat: <Combobox> defaultFilter value
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-tests.jest.js
  src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx
  src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/splitButtonMenu-snapshot-tests.jest.tsx.snap
  src/components/SplitButton/SplitButtonMenu/__tests__/splitButtonMenu-tests.jest.tsx
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
  src/tests/constants.ts
  src/tests/test-ids-utils.ts
Labels: PR: unreviewed, PR: New Feature 🕹

#1491 fix: <TextField> debounce recreation bug
  src/components/TextField/TextField.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1493 docs: Update Pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed, PR: Documentation 📖

#1497 fix: <Dropdown> pass children to the menuRenderer
  src/components/Dropdown/components/menu/menu.jsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1501 update monday-ui-style
  package-lock.json
  package.json
Labels: PR: Dependencies 🛠

#1492 feat: <Menu> id generation
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/Menu/hooks/useMenuId.tsx
  src/components/Menu/Menu/utils/utils.ts
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/splitButtonMenu-snapshot-tests.jest.tsx.snap
  src/components/SplitButton/SplitButtonMenu/__tests__/splitButtonMenu-tests.jest.tsx
  src/components/SplitButton/__tests__/splitButton-tests.jest.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1500 chore: Update stories plop
  plop/general/component-stories-mdx.txt
Labels: PR: unreviewed, PR: Internal 🏠

#1505 fix: <ExpandCollapse> flickering
  src/components/ExpandCollapse/ExpandCollapse.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1506 fix: <List> keyboard focus only on list items
  src/components/List/List.tsx
  src/components/List/utils/ListUtils.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1503 feat: export <Dropdown> components - <DropdownMenu>, <DropdownOption>, <DropdownSingleValue>
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__stories__/dropdown.stories.scss
  src/components/Dropdown/components/menu/menu.jsx
  src/components/Dropdown/components/option/option.jsx
  src/components/Dropdown/components/singleValue/singleValue.jsx
  src/components/index.js
  webpack/published-js-components.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1494 feat: <Table/> - new component
  src/components/Table/Table/Table.module.scss
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/__stories__/helpers.js
  src/components/Table/Table/__stories__/table.stories.mdx
  src/components/Table/Table/__stories__/table.stories.scss
  src/components/Table/Table/__tests__/table.jest.tsx
  src/components/Table/Table/tableHelpers.ts
  src/components/Table/TableBody/TableBody.module.scss
  src/components/Table/TableBody/TableBody.tsx
  src/components/Table/TableCell/TableCell.module.scss
  src/components/Table/TableCell/TableCell.tsx
  src/components/Table/TableHeader/TableHeader.module.scss
  src/components/Table/TableHeader/TableHeader.tsx
  src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
  src/components/Table/TableHeaderCell/TableHeaderCell.tsx
  src/components/Table/TableRow/TableRow.module.scss
  src/components/Table/TableRow/TableRow.tsx
  src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
  src/tests/constants.ts
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#1499 docs: <ExpandCollapse> story
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/ExpandCollapse/ExpandCollapse.tsx
  src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.mdx
  src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.module.scss
  src/components/ExpandCollapse/__stories__/expandCollapse.stories.js
  src/components/ExpandCollapse/__stories__/expandCollapse.stories.scss
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/accordion-description/accordion-description.jsx
  src/storybook/components/related-components/descriptions/accordion-description/accordion-description.module.scss
  src/storybook/components/related-components/descriptions/expand-collapse-description/expand-collapse-description.jsx
  src/storybook/components/related-components/descriptions/expand-collapse-description/expand-collapse-description.module.scss
Labels: PR: unreviewed, PR: Documentation 📖
