Repository mondaycom/vibe, pull requests merged in 2023-10, with the labels that each got.

#1561 fix(Label): apply preventDefault when calling onClick event
  src/components/Label/Label.tsx
  src/components/Label/__tests__/Label-tests.jest.tsx
Labels: PR: Bugfix 🐛

#1564 docs: component-name-decorator- text color = fixed-dark
  src/storybook/components/component-name/component-name-decorator.scss
Labels: PR: unreviewed, PR: Documentation 📖

#1565 Replace Rubik with Noto Sans Hebrew
  .storybook/preview-head.html
  package-lock.json
  package.json
  src/storybook/stand-alone-documentaion/typography-new/typography.stories.mdx
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
Labels: PR: unreviewed, PR: New Feature 🕹

#1563 docs: <Dialog> story improvements - UsageGuidelines, add links
  package-lock.json
  package.json
  src/components/Dialog/__stories__/Dialog.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1551 chore: set browserslist config to specific version to avoid breaking changes, update caniuse browserslist
  package-lock.json
  package.json
Labels: PR: Internal 🏠

#1570 feat(useActiveDescendantListFocus): add option to ignoreDocumentFallback to prevent vibe from adding event listeners
  src/hooks/useActiveDescendantListFocus/index.ts
Labels: PR: New Feature 🕹

#1582 fix: <MenuButton> disabledReason?: boolean change type to string
  src/components/MenuButton/MenuButton.tsx
Labels: PR: reviewed-approved, PR: Bugfix 🐛

#1585 feat: <Chips> - add closeButtonAriaLabel as a prop
  src/components/Chips/Chips.tsx
Labels: PR: New Feature 🕹

#1586 feat: <AttentionBox> closeButton - add hideTooltip and closeButtonAriaLabel prop
  src/components/AttentionBox/AttentionBox.tsx
Labels: PR: New Feature 🕹

#1592 docs: Add space between <Combobox> tips and links
  src/components/Combobox/__stories__/combobox.stories.mdx
Labels: PR: Documentation 📖

#1591 docs: replace legacy links with the new ones
  src/hooks/useClickOutside/__stories__/useClickOutside.stories.mdx
  src/hooks/useClickableProps/__stories__/useClickableProps.stories.mdx
  src/hooks/useEventListener/__stories__/useEventListener.stories.mdx
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
  src/hooks/useHover/__stories__/useHover.stories.mdx
  src/hooks/useIsOverflowing/__stories__/useIsOverflowing.stories.mdx
  src/hooks/useKeyEvent/__stories__/useKeyEvent.stories.mdx
  src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.mdx
  src/hooks/useSetFocus/__stories__/useSetFocus.stories.mdx
Labels: PR: Documentation 📖

#1593 fix text in a few places
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Menu/Menu/__stories__/menu.stories.js
  src/storybook/stand-alone-documentaion/typography-new/typography.stories.mdx
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
Labels: PR: Documentation 📖

#1596 chore: enforce using npm
  .npmrc
  package-lock.json
  package.json
Labels: PR: Internal 🏠

#1594 fix: <Avatar> remove default tabIndex = 0
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/ListItemAvatar/__tests__/__snapshots__/listItemAvatar.jest.js.snap
Labels: PR: Bugfix 🐛

#1604 Revert "chore: enforce using npm"
  .npmrc
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#1603 infra: allow running chromatic workflow on pull_request
  .github/workflows/chromatic.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1595 feat: update label with VibeComponent
  src/components/Label/Label.tsx
Labels: PR: New Feature 🕹

#1608 docs: added a link to Combobox on the Menu page
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
Labels: PR: Documentation 📖

#1610 infra: Fix workflows running twice
  .github/workflows/chromatic.yml
  .github/workflows/test-workflow.yml
Labels: PR: Internal 🏠

#1611 feat: <AttentionBox> - update default icon for Primary type to Info icon
  src/components/AttentionBox/AttentionBox.tsx
Labels: PR: New Feature 🕹

#1613 chore: Update snapshots
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: Internal 🏠

#1599 docs: enable controls for some of the stories
  src/components/Clickable/__stories__/Clickable.stories.mdx
  src/components/DatePicker/__stories__/datepicker.stories.mdx
  src/components/DialogContentContainer/__stories__/DialogContentContainer.stories.mdx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/HiddenText/__stories__/HiddenText.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Menu/MenuDivider/__stories__/MenuDivider.stories.mdx
  src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.mdx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
  src/components/Menu/MenuItemButton/__stories__/MenuItemButton.stories.mdx
  src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.mdx
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/ResponsiveList/__stories__/ResponsiveList.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/Tabs/Tab/__stories__/tab.stories.mdx
  src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
Labels: PR: Documentation 📖

#1616 chore: cleanup in stories controls
  package-lock.json
  package.json
  src/components/Badge/__stories__/Badge.stories.mdx
  src/components/DatePicker/__stories__/DatePicker.stories.jsx
  src/components/DatePicker/__stories__/datepicker.stories.mdx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/HiddenText/__stories__/HiddenText.stories.mdx
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
  src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
Labels: PR: Documentation 📖

#1618 docs: add npm version badge
  README.md
Labels: PR: Documentation 📖

#1612 test: add editable heading interaction test
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__tests__/editable-heading-interactions.tsx
  src/tests/interactions-utils.ts
Labels: PR: Internal 🏠

#1600 docs: fix links
  src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
Labels: PR: Documentation 📖

#1619 fix: <MenuDivider/> - added necessary stylings
  src/components/Menu/MenuDivider/MenuDivider.module.scss
Labels: PR: Bugfix 🐛

#1621 docs: <Checkbox> Usage guidelines - fix font #1577
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.scss
Labels: PR: Documentation 📖

#1626 chore: cleanup, update vibe-storybook-components to ^0.8.0
  package-lock.json
  package.json
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.scss
  src/components/EditableHeading/__tests__/editable-heading-interactions.tsx
Labels: PR: Internal 🏠

#1624 fix: <Counter> use color - text-color-fixed-light
  src/components/Counter/Counter.module.scss
Labels: PR: Bugfix 🐛

#1627 docs: replace all <a/> tags with <Link/> in stories
  .storybook/preview.js
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Text/__stories__/Text.stories.mdx
  src/hooks/useEventListener/__stories__/useEventListener.stories.mdx
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
  src/hooks/useKeyEvent/__stories__/useKeyEvent.stories.mdx
  src/hooks/useSetFocus/__stories__/useSetFocus.stories.mdx
Labels: PR: Documentation 📖

#1634 chore: fix Github actions lint warnings - < AvatarGroup />
  src/components/AvatarGroup/AvatarGroupCounter.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
Labels: PR: Internal 🏠

#1635 chore: fix github actions lint warnings - < Checkbox /> tests
  src/components/Checkbox/__tests__/checkbox-tests.jest.tsx
Labels: PR: Internal 🏠

#1636 chore: fix github actions lint warnings - <AlertBanner />
  src/components/AlertBanner/AlertBanner.tsx
Labels: PR: Internal 🏠

#1639 docs: Text.stories cleanup
  src/components/Text/__stories__/Text.stories.mdx
Labels: PR: Internal 🏠

#1643 chore: fix Github actions lint warnings - < ColorPicker />
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerClearButton.tsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.tsx
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
Labels: PR: Internal 🏠

#1640 chore: fix Github actions lint warnings - < Button />
  src/components/Button/Button.tsx
  src/components/Button/ButtonConstants.ts
Labels: PR: Internal 🏠

#1646 feat: provide props for ariaLabel - < AvatarGroupCounter />, < TableHeaderCell />
  src/components/AvatarGroup/AvatarGroupCounter.tsx
  src/components/Table/TableHeaderCell/TableHeaderCell.tsx
Labels: PR: New Feature 🕹

#1652 Resolved lint warnings - < Slider />, < StepIndicator />, < Bar />, <TabsContext />
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
  src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
  src/components/Slider/SliderHelpers.ts
  src/components/Tabs/TabsContext/TabsContext.tsx
Labels: PR: Internal 🏠

#1628 docs: Replace tip alpha warning deprecated warning with vibe storybook components
  .storybook/preview.js
  package-lock.json
  package.json
  scripts/build-utils.js
  src/components/LegacyHeading/__stories__/LegacyHeading.stories.mdx
  src/storybook/components/alpha-warning/alpha-warning.tsx
  src/storybook/components/deprecated-warning/deprecated-warning.tsx
  src/storybook/components/index.js
  src/storybook/components/tip/README.md
  src/storybook/components/tip/tip.jsx
  src/storybook/components/tip/tip.scss
  src/storybook/stand-alone-documentaion/typography-new/typography.stories.mdx
  webpack/published-components.js
  webpack/published-storybook-components.js
Labels: PR: Internal 🏠

#1623 fix: <Toast> use color - text-color-fixed-light
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Button/ButtonConstants.ts
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/Text/__stories__/Text.stories.mdx
  src/components/Text/__stories__/Text.stories.module.scss
  src/components/Toast/Toast.module.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastButton/ToastButton.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/components/Typography/Typography.module.scss
  src/components/Typography/TypographyConstants.ts
  src/storybook/stand-alone-documentaion/colors/colors-description/colors-description.jsx
  src/storybook/stand-alone-documentaion/colors/text-colors/text-colors.jsx
  src/utils/colors-vars-map.ts
Labels: PR: Bugfix 🐛

#1556 fix: Fix menu item label style
  src/components/Label/__stories__/label.stories.mdx
  src/components/Menu/MenuItem/MenuItem.module.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/Menu/MenuItem/__tests__/menuItem-snapshots.jest.js
Labels: PR: Bugfix 🐛

#1660 docs: fix description of text-color-fixed-light and text-color-fixed-dark
  src/utils/colors-vars-map.ts
Labels: PR: Documentation 📖

#1659 fix: <BreadcrumbsBar> - shouldn't be clickable when type = Indication
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.module.scss
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.tsx
  src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem-snapshot-tests.jest.js.snap
  src/components/BreadcrumbsBar/__tests__/__snapshots__/breadcrumbsBar-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1657 fix: colorpicker indicator is dissapearing when color is selected
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.tsx
Labels: PR: Bugfix 🐛

#1654 feat: provide props for ariaLabel - < Toast />, < AlertBanner />, < Combobox /> Fixes: #1642
  src/components/AlertBanner/AlertBanner.tsx
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/Combobox/Combobox.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/components/Toast/__tests__/toast-tests.jest.js
  src/tests/constants.ts
Labels: PR: New Feature 🕹

#1663 infra: add build-test in test-workflow.yml
  .github/workflows/test-workflow.yml
Labels: PR: Internal 🏠

#1662 feat(AlertBanner): add warning variation
  src/components/AlertBanner/AlertBanner.module.scss
  src/components/AlertBanner/AlertBanner.tsx
  src/components/AlertBanner/AlertBannerConstants.ts
  src/components/AlertBanner/AlertBannerContext.ts
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
Labels: PR: New Feature 🕹

#1637 feat: add Toast warning variation
  src/components/Toast/Toast.module.scss
  src/components/Toast/ToastConstants.ts
  src/components/Toast/__stories__/toast.stories.mdx
Labels: PR: New Feature 🕹

#1666 Bug Fix: Fixes #1661 Fixed the TS error while using size prop for <ProgressBar />
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
Labels: PR: Internal 🏠

#1653 chore: resolve lint warnings - < Menu />
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/Menu/MenuConstants.ts
  src/components/Menu/Menu/utils/utils.ts
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/MenuButton/MenuButton.tsx
Labels: PR: Internal 🏠

#1670 feat(types): export general types
  package.json
  src/types/index.ts
  src/types/positions.ts
Labels: PR: New Feature 🕹

#1671 Update vibe-storybook-components version, @babel/core version
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#1656 chore: < GridKeyboardNavigationContext /> - migrate to TS
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.ts
  src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContextConstants.ts
  src/components/GridKeyboardNavigationContext/helper.ts
  src/components/Menu/MenuGridItem/MenuGridItem.tsx
  src/components/Menu/MenuGridItem/useMenuGridItemNavContext.tsx
Labels: PR: Internal 🏠

#1680 fix(types): fix unknown path '/types'
  package.json
Labels: PR: Bugfix 🐛

#1682 docs(AlertBanner): fix documentation
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
Labels: PR: Internal 🏠

#1683 feat: < Tipseen /> export hideShowTriggers
  src/components/Tipseen/Tipseen.tsx
Labels: PR: New Feature 🕹

#1684 docs: fix contributors list to include all contributors
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
Labels: PR: Documentation 📖

#1687 Add mising data-testid, replace dataTestId (not breaking)
  src/components/AlertBanner/AlertBanner.tsx
  src/components/Button/Button.tsx
  src/components/Chips/Chips.tsx
  src/components/Clickable/Clickable.tsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/EditableHeading/EditableHeading.tsx
  src/components/EditableHeading/__tests__/editableHeading.jest.tsx
  src/components/IconButton/IconButton.tsx
  src/components/Modal/__stories__/helpers.js
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
  src/components/Steps/StepsCommand.tsx
  src/components/TextField/TextField.tsx
  src/components/Toast/ToastButton/ToastButton.tsx
  src/components/Tooltip/__tests__/tooltip-tests.jest.tsx
  src/hooks/useClickableProps/useClickableProps.ts
Labels: PR: New Feature 🕹

#1689 chore: add @deprecated comments where backwardCompatibilityForProperties is being used
  src/components/AttentionBox/AttentionBox.tsx
  src/components/Avatar/Avatar.tsx
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Dialog/Dialog.tsx
  src/components/Divider/Divider.tsx
  src/components/Label/Label.tsx
  src/components/Link/Link.tsx
  src/components/Loader/Loader.tsx
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/MenuDivider/MenuDivider.tsx
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/MenuButton/MenuButton.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/TextField/TextField.tsx
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/TipseenConstants.ts
  src/components/Tipseen/TipseenContent.tsx
  src/components/Toggle/Toggle.tsx
Labels: PR: Documentation 📖

#1678 fix: <Toast /> close button - replace <Button /> and <Icon /> with <IconButton />
  src/components/Toast/Toast.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1692 < Slider /> controlled state fix
  src/components/Slider/Slider.tsx
  src/components/Slider/SliderHooks.ts
Labels: PR: Bugfix 🐛

#1693 chore: fix < Tip /> imports to be from vibe-storybook-components
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Box/__stories__/Box.stories.mdx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/HiddenText/__stories__/HiddenText.stories.mdx
  src/components/List/__stories__/List.stories.mdx
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Text/__stories__/Text.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/VirtualizedList/__stories__/VirtualizedList.stories.mdx
  src/hooks/useClickableProps/__stories__/useClickableProps.stories.mdx
  src/hooks/useIsOverflowing/__stories__/useIsOverflowing.stories.mdx
Labels: PR: Internal 🏠

#1691 feat(EditableInput): expose inputType
  src/components/EditableInput/EditableInput.tsx
Labels: PR: New Feature 🕹

#1694 fix: <Dropdown> controlled multi fix option remove
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
Labels: PR: Bugfix 🐛

#1701 export useElementsOverflowingIndex hook
  src/hooks/index.js
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#1690 feat: < AvatarGroup /> - added new prop to remove padding (#1674)
  src/components/AvatarGroup/AvatarGroup.module.scss
  src/components/AvatarGroup/AvatarGroup.tsx
Labels: PR: New Feature 🕹

#1700 feat: < TextField /> add red asterisks(*) when required=true
  src/components/FieldLabel/FieldLabel.module.scss
  src/components/FieldLabel/FieldLabel.tsx
  src/components/TextField/TextField.tsx
  src/components/TextField/__stories__/TextField.stories.mdx
Labels: PR: New Feature 🕹

#1699 fix: < ComboBox / > - change stickyCategories to not be the default behavior
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.tsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/components/ComboboxItems/ComboboxItems.tsx
Labels: PR: Bugfix 🐛

#1519 docs(Typography): new docs page for Typography
  src/storybook/stand-alone-documentaion/typography-new/assets/index.js
  src/storybook/stand-alone-documentaion/typography-new/assets/typographyExample1.png
  src/storybook/stand-alone-documentaion/typography-new/assets/typographyExample2.png
  src/storybook/stand-alone-documentaion/typography-new/text-styles/text-styles.jsx
  src/storybook/stand-alone-documentaion/typography-new/text-styles/text-styles.module.scss
  src/storybook/stand-alone-documentaion/typography-new/typography.scss
  src/storybook/stand-alone-documentaion/typography-new/typography.stories.mdx
  src/storybook/stand-alone-documentaion/typography/assets/index.js
  src/storybook/stand-alone-documentaion/typography/assets/typographyExample1.png
  src/storybook/stand-alone-documentaion/typography/assets/typographyExample2.png
  src/storybook/stand-alone-documentaion/typography/assets/typographyExample3.png
  src/storybook/stand-alone-documentaion/typography/assets/typographyExample4.png
  src/storybook/stand-alone-documentaion/typography/examples-table/example-table.module.scss
  src/storybook/stand-alone-documentaion/typography/examples-table/examples-table.tsx
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.scss
  src/storybook/stand-alone-documentaion/typography/typography.module.scss
  src/storybook/stand-alone-documentaion/typography/typography.scss
  src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
  src/utils/colors-vars-map.ts
Labels: PR: Documentation 📖

#1702 chore: cleanup demo styles
  src/components/Dropdown/__stories__/dropdown.stories.scss
Labels: PR: Internal 🏠

#1704 fix: <AvatarGroup> rename freshly added padding prop to removePadding
  src/components/AvatarGroup/AvatarGroup.tsx
Labels: PR: Bugfix 🐛

#1703 feat: < Dialog /> should throw console.error if containerSelector is not found
  src/components/Dialog/Dialog.tsx
Labels: PR: New Feature 🕹

#1707 fix(Button): adjust loading state to initial button size
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Button/__stories__/button.stories.mdx
Labels: PR: Bugfix 🐛

#1705 feat: fix for Vite
  package.json
Labels: PR: New Feature 🕹

#1714 fix: <MenuButton> change moveBy <Dialog> and active state text color
  src/components/MenuButton/MenuButton.module.scss
  src/components/MenuButton/MenuButton.tsx
Labels: PR: Bugfix 🐛

#1710 fix: <Dropdown> multi - single line, fix mixed controlled-uncontrolled <Dialog> state management - move to uncontrolled
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
Labels: PR: Bugfix 🐛

#1708 fix: <Dropdown> multi single line - counter options display
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/hooks/useHiddenOptionsData.js
Labels: PR: Bugfix 🐛

#1706 Fixes: #1673 BUG Tooltip not visible when more than one row ellipsis is applied to Text component
  src/components/Heading/Heading.tsx
  src/components/Text/Text.tsx
  src/components/Typography/Typography.tsx
  src/components/Typography/TypographyHooks.tsx
  src/components/Typography/utils/TypographyContext.ts
Labels: PR: Bugfix 🐛

#1717 chore: cleanup - lint issue
  src/components/Text/Text.tsx
Labels: PR: Internal 🏠

#1715 fix(AttentionBox): fix title overflow behavior
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: Bugfix 🐛

#1716 docs: extract AlertBanner template to stories file
  src/components/AlertBanner/__stories__/alertBanner.stories.js
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
Labels: PR: Documentation 📖

#1720 Update vibe-storybook-components to ^0.10.3
  package-lock.json
  package.json
Labels: PR: Documentation 📖

#1651 chore: fix lint warnings
  src/components/Tipseen/Tipseen.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Typography/TypographyHooks.tsx
  src/components/VirtualizedGrid/VirtualizedGrid.tsx
  src/components/VirtualizedList/VirtualizedList.tsx
Labels: PR: Internal 🏠

#1724 chore: cleanup
  src/components/VirtualizedList/VirtualizedList.tsx
Labels: PR: Internal 🏠

#1721 chore: Replace Github contributors list to be from vibe-storybook-components
  package-lock.json
  package.json
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/contributors.tsx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.module.scss
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.scss
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.tsx
  src/storybook/stand-alone-documentaion/welcome/welcome.stories.mdx
Labels: PR: Internal 🏠
