Repository mondaycom/vibe, pull requests merged in 2023-11, with the labels that each got.

#1526 feat: <ThemeProvider>
  .storybook/preview.js
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/ThemeProviderConstants.ts
  src/components/ThemeProvider/ThemeProviderUtils.ts
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.mdx
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.module.scss
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.tsx
  src/components/ThemeProvider/__stories__/colors-eligible-for-theming.jsx
  src/components/ThemeProvider/__stories__/product-themes/index.ts
  src/components/ThemeProvider/__stories__/product-themes/product-theme-1.ts
  src/components/ThemeProvider/__stories__/product-themes/product-theme-2.ts
  src/components/ThemeProvider/__stories__/product-themes/product-theme-3.ts
  src/components/ThemeProvider/__stories__/product-themes/product-theme-4.ts
  src/components/ThemeProvider/__tests__/themeProvider-tests.jest.js
  src/components/index.js
  src/storybook/stand-alone-documentaion/colors/colors-description/colors-description.jsx
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1730 docs: ThemeProvider alpha tag instead of beta
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.mdx
Labels: PR: Documentation 📖

#1731 chore: <Table/> - fix virtualization scroll issue
  src/components/Table/TableRow/TableRow.tsx
Labels: bug

#1734 fix: Modified the styling of the <TextField> icon
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/TextField.module.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/__stories__/TextField.stories.mdx
Labels: PR: Bugfix 🐛

#1736 fix: <TextField> add typograpghy mixin to the textField container to prevent avoid line-height overrides
  src/components/TextField/TextField.module.scss
Labels: PR: Bugfix 🐛

#1733 feat: <Dropdown> add filterOption prop for custom filter
  src/components/Dropdown/Dropdown.jsx
Labels: PR: New Feature 🕹

#1727 feat: create a new EditableHeading component (with new typography styles)
  src/components/EditableHeading/EditableHeading.module.scss
  src/components/EditableHeading/EditableHeading.tsx
  src/components/EditableHeading/HiddenInputPlaceholder.module.scss
  src/components/EditableHeading/HiddenInputPlaceholder.tsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__tests__/EditableHeading-interactions.tsx
  src/components/EditableHeading/__tests__/EditableHeading-tests.jest.js
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/next.ts
  src/next/next.ts
Labels: PR: New Feature 🕹

#1735 docs: improve readme files on how to import css - mention storybook
  DEPRECATED_IMPORTS.md
  README.md
Labels: PR: Documentation 📖

#1726 feat: new EditableHeading with new typography
  src/components/EditableHeading/EditableHeading.module.scss
  src/components/EditableHeading/EditableHeading.tsx
  src/components/EditableHeading/HiddenInputPlaceholder.module.scss
  src/components/EditableHeading/HiddenInputPlaceholder.tsx
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__tests__/EditableHeading-interactions.tsx
  src/components/EditableHeading/__tests__/EditableHeading-tests.jest.js
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.tsx.snap
  src/components/LegacyEditableHeading/LegacyEditableHeading.module.scss
  src/components/LegacyEditableHeading/LegacyEditableHeading.tsx
  src/components/LegacyEditableHeading/__stories__/LegacyEditableHeading.stories.mdx
  src/components/LegacyEditableHeading/__tests__/LegacyEditableHeading-interactions.tsx
  src/components/LegacyEditableHeading/__tests__/LegacyEditableHeading.jest.tsx
  src/components/LegacyEditableHeading/__tests__/__snapshots__/LegacyEditableHeading.jest.tsx.snap
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/index.js
  src/next.ts
  src/next/next.ts
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#1741 docs: remove hacker theme from storybook
  .storybook/preview-head.html
  .storybook/preview.js
Labels: PR: Documentation 📖

#1729 fix(MultiValueContainer): align items vertically
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/Dropdown.interactions.js
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
Labels: PR: Bugfix 🐛

#1740 fix: <ThemeProvider> remove Hacker theme from eligible for overrides
  src/components/ThemeProvider/ThemeProviderConstants.ts
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.mdx
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.tsx
  src/components/ThemeProvider/__tests__/themeProvider-tests.jest.js
Labels: PR: Bugfix 🐛

#1739 fix(Button): differentiate different states of the button with a key
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
Labels: PR: Bugfix 🐛

#1738 fix: <Dropdown> inside <Modal> overflow
  src/components/DialogContentContainer/DialogContentContainer.tsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/DropdownConstants.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/menu/menu.jsx
  src/components/Dropdown/dropdown-constants.js
  src/storybook/components/related-components/descriptions/dropdown-description.jsx
  src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.mdx
Labels: PR: New Feature 🕹

#1746 docs: Related components rename <Steps>, <LinearProgressBar>, PascalCase
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/alert-banner-description.jsx
  src/storybook/components/related-components/descriptions/attention-box-description.jsx
  src/storybook/components/related-components/descriptions/avatar-group-description.jsx
  src/storybook/components/related-components/descriptions/button-group-description.jsx
  src/storybook/components/related-components/descriptions/dialog-content-container.jsx
  src/storybook/components/related-components/descriptions/editable-heading-description.jsx
  src/storybook/components/related-components/descriptions/hidden-text-description.jsx
  src/storybook/components/related-components/descriptions/icon-button-description.jsx
  src/storybook/components/related-components/descriptions/linear-progress-bar-description.jsx
  src/storybook/components/related-components/descriptions/radio-button-description.jsx
  src/storybook/components/related-components/descriptions/split-button-description.jsx
  src/storybook/components/related-components/descriptions/steps-description.jsx
  src/storybook/components/related-components/descriptions/text-field-description.jsx
Labels: PR: Documentation 📖

#1748 docs: rename stories names to be in pascal case
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/buttonGroup.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/storybook/components/related-components/descriptions/button-group-description.jsx
  src/storybook/components/related-components/descriptions/icon-button-description.jsx
  src/storybook/components/related-components/descriptions/split-button-description.jsx
Labels: PR: Documentation 📖

#1752 fix(Button): fix loading behavior when button is type submit in a for…
  src/components/Button/Button.tsx
  src/components/Button/__tests__/button.jest.js
  src/components/Button/helper/useButtonLoading.ts
Labels: PR: Bugfix 🐛

#1753 feat(Checkbox): add a tabIndex prop
  src/components/Checkbox/Checkbox.tsx
Labels: PR: New Feature 🕹

#1747 docs: rename Wizard to <MultiStepIndicator>
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.mdx
  src/components/List/__stories__/List.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/storybook/components/related-components/component-description-map.js
  src/storybook/components/related-components/descriptions/multi-step-indicator-description.jsx
  src/storybook/components/related-components/descriptions/radio-button-description.jsx
Labels: PR: Documentation 📖

#1751 docs: fix typo
  src/components/List/__stories__/List.stories.mdx
Labels: PR: Documentation 📖

#1737 docs: Components catalog
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.mdx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Heading/__stories__/assets/index.js
  src/components/LegacyHeading/__stories__/LegacyHeading.stories.mdx
  src/components/LegacyHeading/__stories__/assets/emptyStateExample.svg
  src/components/LegacyHeading/__stories__/assets/index.js
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/Slider/__stories__/Slider.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/alert-banner-description.jsx
  src/storybook/components/related-components/descriptions/attention-box-description.jsx
  src/storybook/components/related-components/descriptions/avatar-group-description.jsx
  src/storybook/components/related-components/descriptions/dialog-content-container.jsx
  src/storybook/components/related-components/descriptions/editable-heading-description.jsx
  src/storybook/components/related-components/descriptions/hidden-text-description.jsx
  src/storybook/components/related-components/descriptions/icon-button-description.jsx
  src/storybook/components/related-components/descriptions/icons-description.jsx
  src/storybook/components/related-components/descriptions/linear-progress-bar-description.jsx
  src/storybook/components/related-components/descriptions/steps-description.jsx
  src/storybook/components/related-components/descriptions/text-field-description.jsx
  src/storybook/components/related-components/related-components-decorator.jsx
  src/storybook/stand-alone-documentaion/catalog/Catalog/Catalog.stories.module.scss
  src/storybook/stand-alone-documentaion/catalog/Catalog/Catalog.stories.tsx
  src/storybook/stand-alone-documentaion/catalog/EmptyState/Catalog.stories.EmptyState.module.scss
  src/storybook/stand-alone-documentaion/catalog/EmptyState/Catalog.stories.EmptyState.tsx
  src/storybook/stand-alone-documentaion/catalog/catalog.stories.mdx
  src/storybook/stories-common-assets/emptyStateExample.svg
  types/global.d.ts
Labels: PR: Documentation 📖

#1750 docs: related components fix description
  src/components/Steps/__stories__/steps.stories.mdx
  src/storybook/components/related-components/descriptions/combobox-description.jsx
  src/storybook/components/related-components/descriptions/dropdown-description.jsx
  src/storybook/components/related-components/descriptions/icons-description.jsx
  src/storybook/components/related-components/descriptions/steps-description.jsx
Labels: PR: Documentation 📖

#1754 docs: Fix overview links - scroll instead of openning new page
  .storybook/preview.js
  src/components/Text/__stories__/Text.stories.mdx
  src/storybook/stand-alone-documentaion/welcome/contributor/contributor.jsx
Labels: PR: Documentation 📖

#1756 fix: <Dropdown> disabled option - fix keyboard focused style
  src/components/Dropdown/Dropdown.styles.js
Labels: PR: Bugfix 🐛

#1552 feat(TableRow): add highlighted styling for TableRow
  src/components/Table/Table/__stories__/helpers.js
  src/components/Table/Table/__stories__/table.stories.mdx
  src/components/Table/Table/__tests__/table.jest.tsx
  src/components/Table/TableRow/TableRow.module.scss
  src/components/Table/TableRow/TableRow.tsx
Labels: PR: New Feature 🕹

#1757 docs: Typography migration guide
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/LegacyEditableHeading/__stories__/LegacyEditableHeading.stories.mdx
  src/components/LegacyHeading/__stories__/LegacyHeading.stories.mdx
  src/storybook/stand-alone-documentaion/typography/assets/index.js
  src/storybook/stand-alone-documentaion/typography/assets/migrationTable.png
  src/storybook/stand-alone-documentaion/typography/typography-migration-guide.stories.mdx
Labels: PR: Documentation 📖

#1760 fix(Button): include entire content for width placeholder
  src/components/Button/Button.tsx
Labels: PR: Bugfix 🐛

#1762 test(Chromatic): wait for font loading before taking a snapshot
  .storybook/preview.js
Labels: PR: Internal 🏠

#1769 docs(Table): Scroll story should have same length as other stories
  src/components/Table/Table/__stories__/table.stories.mdx
Labels: PR: Documentation 📖

#1768 fix(Toast): description icon should be 20px
  src/components/Toast/ToastHelpers.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1770 chore: supress <Dialog> console.error if container not found, add TODO
  src/components/Dialog/Dialog.tsx
Labels: PR: Internal 🏠

#1759 EditableText/EditableHeading fixed and update docs
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/EditableHeading/__stories__/EditableHeading.stories.module.scss
  src/components/EditableText/EditableText.module.scss
  src/components/EditableText/EditableText.tsx
  src/components/EditableText/__stories__/EditableText.stories.mdx
  src/components/EditableText/__stories__/EditableText.stories.module.scss
  src/components/EditableTypography/EditableTypography.module.scss
Labels: PR: Bugfix 🐛

#1765 <Table/> - Add row size variations
  src/components/Table/Table/Table.module.scss
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/TableConsts.ts
  src/components/Table/Table/__stories__/table.stories.mdx
  src/components/Table/TableCell/TableCell.module.scss
  src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
  src/components/Table/TableRow/TableRow.module.scss
Labels: PR: New Feature 🕹

#1771 fix: typography vertical overflow tolerance
  src/components/Heading/Heading.tsx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Text/Text.tsx
  src/components/Text/__stories__/Text.stories.mdx
  src/components/Typography/Typography.tsx
  src/components/Typography/TypographyHooks.tsx
  src/components/Typography/utils/TypographyContext.ts
  src/hooks/useIsOverflowing/useIsOverflowing.ts
Labels: PR: Bugfix 🐛

#1777 fix(Button): remove aria-pressed
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/Button/Button.tsx
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/__snapshots__/modalFooterButtons-snapshot-tests.jest.tsx.snap
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1772 fix(ModalHeader): extract icon from Heading to allow tooltip to work
  src/components/Heading/Heading.tsx
  src/components/Modal/ModalHeader/ModalHeader.module.scss
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1782 docs: RelatedComponents - add <ColorPicker> component
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/color-picker-description.tsx
Labels: PR: Documentation 📖

#1775 infra: disable cron for update monday-ui-style version workflow
  .github/workflows/update-icons.yml
Labels: PR: Internal 🏠

#1786 docs: RelatedComponents - fix <Dialog> description
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/dialog-description/dialog-description.module.scss
  src/storybook/components/related-components/descriptions/dialog-description/dialog-description.tsx
  src/storybook/components/related-components/descriptions/dialog.jsx
Labels: PR: Documentation 📖

#1785 fix: replace deprecated text-fixed-color tokens with identical color tokens
  package-lock.json
  package.json
  src/components/AlertBanner/AlertBanner.module.scss
  src/components/Button/Button.module.scss
  src/components/Counter/Counter.module.scss
  src/components/Toast/Toast.module.scss
  src/components/Typography/Typography.module.scss
  src/storybook/stand-alone-documentaion/colors/colors-description/colors-description.jsx
  src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
  src/storybook/stand-alone-documentaion/colors/text-colors/text-colors.jsx
  src/utils/colors-vars-map.ts
Labels: PR: Bugfix 🐛

#1784 docs: RelatedComponents - add <VirtualizedList> component description example
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx
  src/storybook/components/related-components/descriptions/virtualized-list-description/virtualizedList.module.scss
Labels: PR: Documentation 📖

#1788 Support className in TableRow
  src/components/Table/TableRow/TableRow.tsx
Labels: PR: New Feature 🕹

#1787 feat(Toggle): add data-testid prop
  src/components/Switch/Switch.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹
