Repository mondaycom/vibe, pull requests merged in 2023-06, with the labels that each got.

#1340 fix: <Dropdown> multi fix <Chips> override with css variables
  src/components/Chips/Chips.module.scss
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1337 fix: <Tipseen> dependencies array
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1335 V1 - feat: <Modal> custom header title
  src/components/Modal/ModalContent/ModalContent.module.scss
  src/components/Modal/ModalHeader/ModalHeader.module.scss
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/__stories__/Modal.stories.scss
  src/components/Modal/__stories__/helpers.js
  src/components/Modal/__stories__/modal.stories.mdx
Labels: PR: unreviewed, PR: New Feature 🕹

#1334 feat: <Modal> custom header title
  src/components/EditableHeading/EditableHeading.tsx
  src/components/Modal/ModalContent/ModalContent.module.scss
  src/components/Modal/ModalHeader/ModalHeader.module.scss
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/__stories__/Modal.stories.scss
  src/components/Modal/__stories__/helpers.js
  src/components/Modal/__stories__/modal.stories.mdx
Labels: PR: unreviewed, PR: New Feature 🕹

#1347 fix: AutoSizer TS issues
  src/components/VirtualizedGrid/VirtualizedGrid.tsx
  src/components/VirtualizedList/VirtualizedList.tsx
Labels: PR: unreviewed, PR: Internal 🏠

#1346 V1 - fix: <Dropdown> multi on option delete callback
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__tests__/dropdown-tests.jest.js
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1349 V1 - fix: <ModalHeader> revert changes to margin-block-start
  src/components/Modal/ModalHeader/ModalHeader.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1345 docs: Vibe 2 migration guide
  VERSION-2-MIGRATION.md
Labels: PR: unreviewed, PR: Documentation 📖

#1351 docs: Rename version 2 migration file
  VERSION_2_MIGRATION.md
Labels: PR: unreviewed, PR: Documentation 📖

#1348 chore: < Dialog > add an example for basic controlled component
  src/components/Dialog/__stories__/Dialog.stories.mdx
Labels: PR: Documentation 📖

#1344 Readme updates for easier contribution
  API_GUIDELINES.MD
  CONTRIBUTING.md
  TESTING_README.md
Labels: PR: Documentation 📖

#1338 feat: <StepIndicator> font-weight redesign + small padding fixes
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.module.scss
Labels: PR: unreviewed, PR: New Feature 🕹

#1339 V1 - feat: <StepIndicator> font-weight redesign + small padding fixes
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
Labels: PR: unreviewed, PR: New Feature 🕹

#1342 Support dialog context menu hide trigger
  src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.tsx.snap
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/components/Dialog/__stories__/Dialog.stories.mdx
  src/components/Dialog/__tests__/Dialog.interactions.ts
  src/components/Dialog/__tests__/Dialog.jest.js
  src/components/Dialog/__tests__/DialogDataTestIds.js
  src/components/Dialog/consts/dialog-show-hide-event.ts
  src/components/DialogContentContainer/DialogContentContainer.tsx
  src/components/DialogContentContainer/__tests__/__snapshots__/dialogContentContainer.jest.tsx.snap
  src/components/DialogContentContainer/__tests__/dialogContentContainer.jest.tsx
  src/components/Flex/Flex.tsx
  src/components/Flex/__tests__/__snapshots__/flex-snapshot-tests.jest.js.snap
  src/components/Flex/__tests__/flex-snapshot-tests.jest.js
  src/constants/dialog.ts
  src/hooks/useClickOutside/__tests__/useClickOutside.jest.ts
  src/hooks/useClickOutside/index.ts
  src/tests/constants.ts
  src/tests/interactions-utils.ts
Labels: PR: New Feature 🕹

#1353 Fix dialog overview story + add come prop comments
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/__stories__/Dialog.stories.mdx
Labels: PR: Documentation 📖

#1323 Add tokens.css in Vibe 2.0
  DEPRECATED_IMPORTS.md
  README.md
  package.json
  webpack.config.js
Labels: PR: unreviewed, PR: Internal 🏠

#1354 TS export components with static props - fix TS2532
  TYPESCRIPT_MIGRATION.md
  src/components/AlertBanner/AlertBanner.tsx
  src/components/AttentionBox/AttentionBox.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Box/Box.tsx
  src/components/BreadcrumbsBar/BreadcrumbsBar.tsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Chips/Chips.tsx
  src/components/Chips/ChipsConstants.ts
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/__tests__/ColorPicker.interactions.js
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx
  src/components/Counter/Counter.tsx
  src/components/DialogContentContainer/DialogContentContainer.tsx
  src/components/Divider/Divider.tsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/dropdown-constants.js
  src/components/EditableHeading/EditableHeading.tsx
  src/components/Flex/Flex.tsx
  src/components/FormattedNumber/FormattedNumber.tsx
  src/components/Heading/Heading.tsx
  src/components/Icon/Icon.tsx
  src/components/IconButton/IconButton.tsx
  src/components/Label/Label.tsx
  src/components/Link/Link.tsx
  src/components/ListItem/ListItem.tsx
  src/components/ListItemIcon/ListItemIcon.tsx
  src/components/Loader/Loader.tsx
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/MenuButton/MenuButton.tsx
  src/components/Modal/Modal.tsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  src/components/Search/Search.tsx
  src/components/Skeleton/Skeleton.tsx
  src/components/Slider/Slider.tsx
  src/components/Slider/SliderInfix.tsx
  src/components/SplitButton/SplitButton.tsx
  src/components/Steps/Steps.tsx
  src/components/Tabs/TabPanels/TabPanels.tsx
  src/components/TextField/TextField.tsx
  src/components/Tipseen/Tipseen.tsx
  src/components/Toast/Toast.tsx
  src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.jsx
  src/types/VibeComponent.ts
  src/types/index.ts
  src/types/withStaticProps.ts
  src/utils/colors-vars-map.ts
Labels: PR: unreviewed, PR: New Feature 🕹

#1362 Fix bug on Tipseen in dark mode
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1360 Add docs best practices to contribution md
  COMPONENTS_DOCUMENTATION_GUIDELINES.md
  CONTRIBUTING.md
  src/components/Loader/__stories__/Loader.stories.mdx
Labels: documentation, PR: Documentation 📖

#1364 Accordion: change declared type to VibeComponent.
  src/components/Accordion/Accordion/Accordion.tsx
Labels: PR: Bugfix 🐛

#1365 fix: < Accordion >: change declared type to VibeComponent
  src/components/Accordion/Accordion/Accordion.tsx
Labels: PR: Bugfix 🐛

#1366 chore: fix accordion docs
  src/components/Accordion/Accordion/Accordion.tsx
Labels: PR: Bugfix 🐛

#1367 Remove redundant tipseen max-width property
  src/components/Tipseen/TipseenTitle.module.scss
Labels: PR: Bugfix 🐛

#1368 fix: <Text> in published-ts-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#1370 fix: <TokenTable> tags styles overrides
  src/storybook/components/token-table/token-table.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1371 V1 - fix: <TokenTable> tags styles overrides
  src/storybook/components/token-table/token-table.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1372 feat: Publish <GridKeyboardNavigationContext>
  src/components/index.js
  webpack/published-js-components.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1369 fix: icons, interactionsTests, testIds types exports
  package.json
  scripts/build-types.js
  scripts/build-utils.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#1376 V1 - fix: icons, interactionsTests, testIds types exports
  package.json
Labels: PR: unreviewed, PR: Bugfix 🐛

#1375 AccordionItem: add support for custom header.
  src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
  src/components/Accordion/Accordion/__tests__/accordion-snapshot-tests.jest.js
  src/components/Accordion/AccordionItem/AccordionItem.tsx
  src/components/ExpandCollapse/ExpandCollapse.tsx
Labels: PR: New Feature 🕹

#1380 docs: Combobox - add example for the creation button
  src/components/Combobox/__stories__/combobox.stories.mdx
Labels: PR: Documentation 📖

#1382 fix: MultiStepIndicator - fix divider to not squeeze bullets
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.module.scss
Labels: PR: Bugfix 🐛
