Repository mondaycom/vibe, pull requests merged in 2023-05, with the labels that each got.

#1244 Dropdown: customOnOptionRemove as a callback, not as a replacement for inner logic
  src/components/Dropdown/Dropdown.jsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1248 chore: expose entry in types for non-ts components
  scripts/build-utils.js
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#1247 Create API_GUIDELINES.MD
  API_GUIDELINES.MD
Labels: PR: Documentation 📖

#1240 Css modules/sergeyro/attention box warning color + icons color + heading style fix
  package-lock.json
  package.json
  src/components/AttentionBox/AttentionBox.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/AttentionBoxConstants.ts
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
  src/styles/theme-mixin.scss
  src/utils/colors-vars-map.ts
Labels: PR: New Feature 🕹

#1251 Publish-storybook on release completed
  .github/workflows/publish-storybook.yml
Labels: PR: unreviewed, PR: New Feature 🕹

#1257 Fix testIds export path
  package.json
Labels: PR: unreviewed, PR: Bugfix 🐛

#1255 chore: <Avatar/>, <AvatarGroup/> - update stories to show absolute urls to files and fix Avatar story to use AvatarGroup
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx
Labels: PR: Documentation 📖

#1256 chore: fix typography docs to map to the exact typography css vars
  src/storybook/components/visual-description/visual-description.jsx
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
Labels: PR: Documentation 📖

#1122 Basic dialog docs (only basic variants and examples)
  src/components/Dialog/Dialog.scss
  src/components/Dialog/__stories__/Dialog.stories.mdx
  src/components/Dialog/__stories__/Dialog.stories.scss
  src/components/Dialog/__stories__/helpers.tsx
  src/components/Tooltip/Tooltip.scss
Labels: PR: Bugfix 🐛

#1263 Passed onKeyPress, onBlur, onFocus props in EditableHeader to EditableInput
  src/components/EditableHeading/EditableHeading.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1265 Docs and craft updates in components
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/FieldLabel/FieldLabel.scss
  src/components/Search/__stories__/Search.stories.scss
  src/components/TextField/TextField.scss
Labels: PR: Bugfix 🐛

#1267 Release deprecated workflow
  .github/workflows/release-deprecated.yml
Labels: PR: Internal 🏠

#1269 npm publish with deprecated tag
  .github/workflows/release-deprecated.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1270 Release v1 workflow
  .github/workflows/release-v1.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1271 Release: breaking changes support
  scripts/release.js
Labels: PR: unreviewed, PR: Internal 🏠

#1262 add wrapper class name to loader
  src/components/Loader/Loader.tsx
  src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
  src/components/Loader/__tests__/loader-snapshots.jest.js
Labels: PR: New Feature 🕹

#1273 docs: Colors foundation - warning colors after negative colors
  src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
Labels: PR: unreviewed, PR: Documentation 📖

#1274 Internal: Publish storybook on workflow_dispatch
  .github/workflows/publish-storybook.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1264 Fix hooks exports
  webpack/published-js-components.js
  webpack/published-ts-components.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#1275 Internal: release process - using package_version variables - test
  .github/workflows/release.yml
Labels: PR: Internal 🏠

#1276 internal: <Counter>, <Link> - remove default props
  src/components/Counter/Counter.tsx
  src/components/Link/Link.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1279 Fix/v1/sergeyro/dummy changes 3
  src/components/Dropdown/Dropdown.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1280 patch: Dummy changes
  src/components/Button/Button.tsx
Labels: PR: Bugfix 🐛

#1281 Dummy change 5
  src/components/Button/Button.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1282 docs: Vibe 2.0 changelog
  CHANGELOG.md
Labels: PR: unreviewed, PR: Documentation 📖

#1292 fix: incorrect display of Checkbox page in docs
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1286 fix: broken anchor with apostrophes
  plop/general/component-stories-mdx.txt
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Box/__stories__/Box.stories.mdx
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.mdx
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/buttonGroup.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Flex/__stories__/Flex.stories.mdx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/List/__stories__/List.stories.mdx
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1297 fix - docs: broken anchor with apostrophes (#1286) Yaron Galperin
  plop/general/component-stories-mdx.txt
  src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
  src/components/AlertBanner/__stories__/alertBanner.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Box/__stories__/Box.stories.mdx
  src/components/BreadcrumbsBar/__stories__/breadcrumbsBar.stories.mdx
  src/components/Button/__stories__/button.stories.mdx
  src/components/ButtonGroup/__stories__/buttonGroup.stories.mdx
  src/components/Checkbox/__stories__/checkbox.stories.mdx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Counter/__stories__/counter.stories.mdx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Flex/__stories__/Flex.stories.mdx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Link/__stories__/Link.stories.mdx
  src/components/List/__stories__/List.stories.mdx
  src/components/Loader/__stories__/Loader.stories.mdx
  src/components/Menu/Menu/__stories__/Menu.stories.mdx
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/RadioButton/__stories__/radioButton.stories.mdx
  src/components/Search/__stories__/Search.stories.mdx
  src/components/Skeleton/__stories__/skeleton.stories.mdx
  src/components/SplitButton/__stories__/splitButton.stories.mdx
  src/components/Steps/__stories__/steps.stories.mdx
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Toast/__stories__/toast.stories.mdx
  src/components/Toggle/__stories__/toggle.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/storybook/components/section-name/section-name.jsx
Labels: PR: Documentation 📖

#1299 Icon: Erase
  package-lock.json
  package.json
  src/components/Icon/Icons/components/Erase.tsx
  src/components/Icon/Icons/index.ts
Labels: PR: Icon 💎

#1295 feat: <ResponsiveList> add menuWrapperClassName prop
  src/components/ResponsiveList/ResponsiveList.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1296 V1 - feat: <ResponsiveList> add menuWrapperClassName prop
  src/components/ResponsiveList/ResponsiveList.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1283 Feature/sergeyro/button brand color
  src/components/Button/Button.module.scss
  src/components/Button/Button.tsx
  src/components/Button/ButtonConstants.ts
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/SplitButton/SplitButton.module.scss
Labels: PR: unreviewed, PR: New Feature 🕹

#1309 docs: <IconButton> fix size in one of the stories
  src/components/IconButton/__stories__/IconButton.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1304 Internal: update-icons workflow - change reviewer, change commit message, PR title
  .github/workflows/update-icons.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1310 [Version 1 support] - Progress bar full width variant
  src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
  src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
  src/components/ProgressBars/LinearProgressBar/__tests__/__snapshots__/linearProgressBar-snapshot-tests.jest.js.snap
Labels: PR: New Feature 🕹

#1302 Internal: run test-workflow on pull_request - for public forks
  .github/workflows/test-workflow.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1312 Version 1: Fix menu button TS bugs
  src/components/MenuButton/MenuButton.tsx
Labels: PR: Bugfix 🐛

#1311 feat: change-skeleton-animation
  src/components/Skeleton/Skeleton.module.scss
Labels: PR: Bugfix 🐛

#1303 Add support on close button theme for tipseen (V2)
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/TipseenConstants.ts
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
Labels: PR: New Feature 🕹

#1322 v1: Feature/hadas/dark theme tipseen
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/TipseenConstants.ts
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
Labels: PR: New Feature 🕹

#1324 fix: <StepsGalleryHeader> - galleryHeaderDot increase specificity
  src/components/Steps/StepsGalleryHeader.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1321 useDisableScroll
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/components/Dialog/__stories__/Dialog.stories.mdx
  src/hooks/useDisableScroll/__stories__/useDisableScroll.stories.mdx
  src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
  src/hooks/useDisableScroll/index.ts
Labels: PR: New Feature 🕹

#1325 Support disable scroll in dialog
  src/components/Dialog/Dialog.tsx
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/hooks/useDisableScroll/__stories__/useDisableScroll.stories.mdx
  src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
  src/hooks/useDisableScroll/index.ts
Labels: PR: New Feature 🕹

#1327 V1: Reverting skeleton animation changes due css classes conflicts and opacity issue
  src/components/Skeleton/Skeleton.scss
Labels: PR: Bugfix 🐛

#1328 Fix chips with background with the same color story
  src/components/Chips/__stories__/chips.stories.mdx
Labels: PR: reviewed-approved, PR: Documentation 📖

#1125 Optimize style injection
  package-lock.json
  package.json
  rollup.config.js
  rollup/styleInject.ejs
  src/components/Accordion/Accordion/Accordion.module.scss
Labels: PR: New Feature 🕹

#1331 Hotfix for not throw an error on dialog when disable scroll is false
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
  src/hooks/useDisableScroll/index.ts
Labels: PR: Bugfix 🐛

#1332 V1: hotfix for use disable scroll
  src/components/Dialog/DialogContent/DialogContent.tsx
  src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
  src/hooks/useDisableScroll/index.ts
Labels: PR: Bugfix 🐛

#1336 fix: <Tipseen/> - override the <Tooltip/> styles by using dedicates CSS variables to prevent CSS order issue
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tooltip/Tooltip.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛
