Repository mondaycom/vibe, pull requests merged in 2023-07, with the labels that each got.

#1384 feat: support ariaExpanded in <IconButton>
  package-lock.json
  src/components/IconButton/IconButton.tsx
Labels: PR: reviewed-approved, PR: New Feature 🕹

#1385 fix: remove Chips.sizes
  src/components/Chips/Chips.tsx
  src/components/Chips/ChipsConstants.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1387 Update browserslist in docs
  README.md
Labels: PR: unreviewed, PR: Documentation 📖

#1388 Refactor modal heading
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#1395 Accordion: fix vibe props are not recognized.
  src/components/Accordion/Accordion/Accordion.tsx
  src/components/Accordion/AccordionItem/AccordionItem.tsx
Labels: PR: Bugfix 🐛

#1390 chore: enable source maps in tsconfig
  tsconfig.json
Labels: PR: unreviewed, PR: Internal 🏠

#1391 refactor: support aria a11y in Tooltip component
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
Labels: PR: unreviewed, accessibility, PR: New Feature 🕹

#1396 Revert "refactor: support aria a11y in Tooltip component"
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
Labels: PR: unreviewed, PR: Internal 🏠

#1402 docs: fix storybook light theme name
  .storybook/preview.js
Labels: PR: unreviewed, PR: Documentation 📖

#1404 Combobox: expose actual type instead a no argument on hover callback.
  src/components/Combobox/Combobox.tsx
Labels: PR: reviewed-approved, PR: Bugfix 🐛

#1406 test(useSwitch): add tests for hook
  src/hooks/useSwitch/__tests__/useSwitch.jest.ts
  src/hooks/useSwitch/index.ts
Labels: PR: Internal 🏠

#1407 docs(useSwitch): add story page for hook
  src/hooks/useSwitch/__stories__/useSwitch.stories.mdx
Labels: PR: Documentation 📖

#1409 fix: InteractionsTest - fix types
  src/components/Dialog/__tests__/Dialog.interactions.ts
  src/tests/interactions-utils.ts
  src/tests/readme.md
Labels: PR: unreviewed, PR: Bugfix 🐛

#1414 docs: change colors descriptions
  src/utils/colors-vars-map.ts
Labels: PR: unreviewed, PR: Documentation 📖

#1416 Bug: Combobox component ts issues
  src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/Combobox/components/ComboboxConstants.ts
  src/components/index.js
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#1408 docs: change usage of Yonatan in stories to Yossi
  src/components/Avatar/__stories__/assets/person3.png
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx
  src/components/AvatarGroup/__stories__/assets/person3.png
  src/storybook/components/related-components/descriptions/avatar-group-description.jsx
Labels: PR: Documentation 📖

#1420 docs(DatePicker): set default selected days for stories
  src/components/DatePicker/__stories__/datepicker.stories.mdx
Labels: PR: Documentation 📖

#1419 improve useState to only called once in useIsOverflowing
  src/hooks/useIsOverflowing/useIsOverflowing.ts
Labels: PR: Bugfix 🐛

#1421 fix(DatePicker): do not set vertical alignment to be baseline (defaults to middle)
  src/components/DatePicker/DatePicker.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1412 Fix vibe typography instances 2
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.module.scss
  src/components/Button/Button.module.scss
  src/components/Checkbox/Checkbox.module.scss
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.tsx.snap
  src/components/Counter/Counter.module.scss
  src/components/FieldLabel/FieldLabel.module.scss
  src/components/Label/Label.module.scss
  src/components/Label/Label.tsx
  src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.tsx.snap
  src/components/Link/Link.module.scss
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/MenuItem/MenuItem.module.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/Menu/MenuItemButton/MenuItemButton.module.scss
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/Menu/MenuTitle/MenuTitle.module.scss
  src/components/Menu/MenuTitle/MenuTitle.tsx
  src/components/Menu/MenuTitle/__tests__/__snapshots__/menuTitle.jest.js.snap
  src/components/MenuButton/MenuButton.module.scss
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.module.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.module.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  src/components/Steps/StepsNumbersHeader.module.scss
  src/components/Steps/StepsNumbersHeader.tsx
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Tabs/Tab/Tab.module.scss
  src/components/TextField/TextField.module.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/styles/typography.scss
Labels: PR: Internal 🏠

#1422 fix(Chips): change border color token, do not limit chip-with-border's height
  src/components/Chips/Chips.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1428 fix heading margin breaking change
  package-lock.json
  package.json
  src/components/Heading/Heading.module.scss
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/Title/Title.module.scss
  src/components/Title/Title.tsx
  src/components/Title/__tests__/__snapshots__/title-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1403 feat(MultiStepIndicator): add ts support
  src/components/MultiStepIndicator/MultiStepConstants.js
  src/components/MultiStepIndicator/MultiStepConstants.ts
  src/components/MultiStepIndicator/MultiStepIndicator.jsx
  src/components/MultiStepIndicator/MultiStepIndicator.tsx
  src/components/MultiStepIndicator/__stories__/helper.ts
  src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
  src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator-snapshot-tests.jest.tsx.snap
  src/components/MultiStepIndicator/__tests__/multiStepIndicator-snapshot-tests.jest.tsx
  src/components/MultiStepIndicator/__tests__/multiStepIndicator-tests.jest.tsx
  src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
Labels: PR: New Feature 🕹

#1425 PR #3 of replacing old token variants with mixins
  src/components/Avatar/AvatarContent.module.scss
  src/components/Avatar/__stories__/avatar.stories.mdx
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Combobox/Combobox.module.scss
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/components/StickyCategoryHeader/StickyCategoryHeader.module.scss
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/FieldLabel/FieldLabel.module.scss
  src/components/FieldLabel/FieldLabel.scss
  src/components/Icon/__stories__/Icon.stories.scss
  src/components/Icon/__stories__/description-label/description-label.scss
  src/components/IconButton/__stories__/IconButton.stories.mdx
  src/components/IconButton/__stories__/iconButton.stories.module.scss
  src/components/ListTitle/ListTitle.module.scss
  src/components/ListTitle/ListTitle.tsx
  src/components/ListTitle/__tests__/__snapshots__/listTitle.jest.js.snap
  src/components/MenuButton/MenuButton.module.scss
  src/components/RadioButton/RadioButton.module.scss
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButton/__tests__/__snapshots__/radioButton-snapshot-tests.jest.tsx.snap
  src/components/Tabs/TabList/TabList.module.scss
  src/components/TextField/TextField.module.scss
  src/components/Tipseen/TipseenTitle.module.scss
  src/components/Tipseen/TipseenTitle.tsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/storybook/stand-alone-documentaion/round-corners/corners-settings/corner-settings.scss
  src/storybook/stand-alone-documentaion/round-corners/rounded-corner/rounded-corner.module.scss
  src/styles/typography.scss
Labels: PR: Internal 🏠

#1431 Chips: Add WARNING color
  src/components/Chips/__stories__/chips.stories.mdx
  src/utils/colors-vars-map.ts
Labels: PR: New Feature 🕹

#1433 docs(API_GUIDELINES): add export instructions for type and interface
  API_GUIDELINES.MD
Labels: PR: unreviewed, PR: Documentation 📖

#1438 fix: <Box/> static props
  src/components/Box/Box.tsx
  src/components/Box/BoxConstants.ts
  src/components/Box/__stories__/Box.stories.mdx
  src/types/ValueOf.ts
  src/types/index.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1443 chore(data-testid): util function does not chain id if it is falsy
  src/tests/test-ids-utils.ts
Labels: PR: Internal 🏠
