Repository mondaycom/vibe, pull requests merged in 2023-01, with the labels that each got.

#1049 Feature/sergeyro/unify icon sizes list menu
  src/components/ListItemIcon/ListItemIcon.tsx
  src/components/ListItemIcon/__tests__/__snapshots__/listItemIcon.jest.js.snap
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/Menu/MenuItem/__tests__/menuItem-snapshots.jest.js
Labels: PR: unreviewed, PR: New Feature 🕹

#1052 Clickable chips redesign story
  src/components/Chips/__stories__/chips.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1053 Revert "Fix storybook menu colors (#1050)"
  .storybook/manager-head.html
Labels: PR: unreviewed, PR: Documentation 📖

#1054 Change welcome page to display current team
  src/storybook/stand-alone-documentaion/welcome/assets/Evgeniy.png
  src/storybook/stand-alone-documentaion/welcome/assets/Meirav.png
  src/storybook/stand-alone-documentaion/welcome/assets/Moshe.png
  src/storybook/stand-alone-documentaion/welcome/assets/Nik.png
  src/storybook/stand-alone-documentaion/welcome/assets/Omri.png
  src/storybook/stand-alone-documentaion/welcome/assets/Sahar.png
  src/storybook/stand-alone-documentaion/welcome/assets/Sergey.png
  src/storybook/stand-alone-documentaion/welcome/assets/Yonatan.png
  src/storybook/stand-alone-documentaion/welcome/assets/index.js
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
  src/storybook/stand-alone-documentaion/welcome/welcome.stories.mdx
Labels: documentation, PR: Documentation 📖

#1057 fix css build issue :(
  .storybook/preview.js
  package-lock.json
  package.json
  rollup.config.js
  src/index.js
  src/style-imports.ts
  src/styles/themes.scss
  webpack.config.js
  webpack/published-components.js
Labels: PR: Bugfix 🐛

#1058 added name prop to textField
  src/components/TextField/TextField.tsx
Labels: PR: New Feature 🕹

#1059 fix mapping
  package.json
Labels: PR: Bugfix 🐛

#1061 Fix all icons
  package.json
Labels: PR: Bugfix 🐛

#1063 Use lodash-es instead of lodash - to align our dependency and better support esm
  .eslintrc.js
  package-lock.json
  package.json
  src/components/Avatar/Avatar.tsx
  src/components/Button/__tests__/button-snapshot-tests.jest.js
  src/components/ButtonGroup/ButtonWrapper.tsx
  src/components/Checkbox/Checkbox.jsx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Clickable/Clickable.tsx
  src/components/ColorPicker/__tests__/colorPicker.jest.js
  src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
  src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
  src/components/Combobox/Combobox.jsx
  src/components/DatePicker/date-picker-utils.ts
  src/components/Dialog/Dialog.tsx
  src/components/Dropdown/Dropdown.jsx
  src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
  src/components/Icon/hooks/useIconProps.tsx
  src/components/IconButton/IconButton.tsx
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
  src/components/Slider/SelectionIndicator.tsx
  src/components/Steps/StepsDot.tsx
  src/components/Steps/StepsGalleryHeader.tsx
  src/components/Switch/index.js
  src/components/Tabs/Tab/Tab.tsx
  src/components/Toggle/Toggle.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
  src/components/VirtualizedList/VirtualizedList.tsx
  src/helpers/screenReaderAccessHelper.ts
  src/hooks/useDebounceEvent/index.ts
  src/hooks/useElementsOverflowingIndex.ts
  src/hooks/useFullKeyboardListeners.ts
  src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
  src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
  src/hooks/useResizeObserver.ts
  src/hooks/useStyle.ts
  src/hooks/useThrottledCallback.ts
  src/hooks/useTimeout/index.ts
  src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.jsx
  src/utils/function-utils.ts
Labels: PR: Dependencies 🛠

#1060 AvatarGroup: teams use case fix
  src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1065 fix inject location
  rollup.config.js
Labels: PR: Bugfix 🐛

#1066 move lodash-es from devDependencies to dependencies
  package-lock.json
  package.json
Labels: PR: Bugfix 🐛

#1064 fix dropdown with modal/dialog state (support scroll inside dropdown)
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/components/menu/menu.jsx
  src/components/Dropdown/dropdown-constants.js
Labels: PR: Bugfix 🐛

#1068 Fix/hadas/center loader
  src/components/Button/Button.scss
Labels: PR: Bugfix 🐛

#1069 fix center loader
  src/components/Button/Button.scss
Labels: PR: Bugfix 🐛

#1067 Checkbox: checkbox and label className props
  src/components/Checkbox/Checkbox.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1071 Expose Vibe components and related TS types
  package.json
  scripts/build-types.js
  scripts/build-utils.js
Labels: PR: New Feature 🕹

#1055 Feature/sergeyro/fix clickable chips breaking changes
  src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Clickable/Clickable.tsx
  src/components/Clickable/ClickableWrapper.tsx
  src/components/Clickable/__tests__/__snapshots__/clickable-snapshot-tests.jest.tsx.snap
  src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.js.snap
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
  src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator-snapshot-tests.jest.js.snap
  src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/hooks/useClickableProps.ts
  src/hooks/useKeyboardButtonPressedFunc.ts
  src/hooks/useSetFocus/index.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1056 Feature/sergeyro/fix chips dropdown alignment
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1072 Fix tipssen hide close button
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/__stories__/tipseen.stories.jsx
Labels: PR: Bugfix 🐛

#1074 Docs/hadas/responsive list docs
  src/components/ResponsiveList/__stories__/ResponsiveList.stories.mdx
  src/components/ResponsiveList/__stories__/responsiveListStoriesComponents.jsx
Labels: PR: Documentation 📖

#1075 Tipseen: snapshot tests & fix bug on onDismiss and onSubmit overrides
  src/components/Tipseen/TipseenContent.tsx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
Labels: PR: Bugfix 🐛

#1076 small tipseen test fix
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
Labels: PR: Internal 🏠

#1077 Feature/sergeyro/avatar classname props
  src/components/Avatar/Avatar.tsx
  src/components/Chips/Chips.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1078 AccordionItem and ExpandAble preparation for css modules transition
  src/components/Accordion/AccordionItem/AccordionItem.tsx
  src/components/ExpandCollapse/ExpandCollapse.scss
  src/components/ExpandCollapse/ExpandCollapse.tsx
  src/components/ExpandCollapse/styles.module.scss
Labels: PR: New Feature 🕹

#1070 add class names to marker and description of radiobutton
  src/components/RadioButton/RadioButton.tsx
Labels: PR: New Feature 🕹

#1079 Update Dropdown.jsx
  src/components/Dropdown/Dropdown.jsx
Labels: PR: Bugfix 🐛

#1080 Skeleton - wrapperClassName and fullWidth props added
  src/components/Skeleton/Skeleton.module.scss
  src/components/Skeleton/Skeleton.scss
  src/components/Skeleton/Skeleton.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1084 Feature/sergeyro/label class name props
  src/components/Label/Label.tsx
Labels: PR: unreviewed, PR: New Feature 🕹
