Repository mondaycom/vibe, pull requests merged in 2023-04, with the labels that each got.

#1197 Fix/sergeyro/sentry errors (EditableInput, VirtualizedList)
  src/components/EditableInput/EditableInput.tsx
  src/components/VirtualizedList/VirtualizedList.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1201 Fix hide border bug in expand collapse
  src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
  src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
  src/components/ExpandCollapse/ExpandCollapse.scss
  src/components/ExpandCollapse/ExpandCollapse.tsx
  src/components/ExpandCollapse/__tests__/__snapshots__/expandCollapse.jest.js.snap
  src/components/ExpandCollapse/styles.module.scss
Labels: PR: Bugfix 🐛

#1202 Support menu button controlled active state
  src/components/MenuButton/MenuButton.tsx
Labels: PR: New Feature 🕹

#1205 fix expand collapse border bug
  src/components/ExpandCollapse/ExpandCollapse.scss
  src/components/ExpandCollapse/styles.module.scss
  src/components/MenuButton/__stories__/MenuButton.stories.mdx
Labels: PR: Bugfix 🐛

#1206 Fix bug on split button loading state
  src/components/SplitButton/SplitButton.tsx
Labels: PR: Bugfix 🐛

#1212 Heading: replace padding changes with useIsOverflowing ignoreHeightOverflow prop
  src/components/Heading/Heading.tsx
  src/hooks/useIsOverflowing/useIsOverflowing.ts
  src/styles/typography.scss
Labels: PR: Bugfix 🐛

#1214 Css modules comment
  src/components/Dialog/DialogContent/DialogContent.tsx
Labels: PR: Internal 🏠

#1217 Add number type and onWheel prop to text field
  src/components/TextField/TextField.tsx
  src/components/TextField/TextFieldConstants.ts
Labels: PR: New Feature 🕹

#1216 Support custom renderer in Chip component
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/chips-snapshot-tests.jest.tsx
Labels: PR: New Feature 🕹

#1219 Support scrollable class name for virtualized grid
  src/components/VirtualizedGrid/VirtualizedGrid.tsx
  src/components/VirtualizedGrid/__tests__/__snapshots__/virtualizedGrid.jest.js.snap
  src/components/VirtualizedGrid/__tests__/virtualizedGrid.jest.js
Labels: PR: New Feature 🕹

#1221 ColorPicker - fix background incorrect setting on hover
  src/components/ColorPicker/ColorPicker.tsx
Labels: PR: Bugfix 🐛

#1226 Internal: Add change log result to log in case of failure in release process
  scripts/release.js
Labels: PR: New Feature 🕹

#1227 change background-color to background in order to allow gradient vari…
  src/components/Button/Button.scss
Labels: PR: New Feature 🕹

#1228 Add icon class name to icon button
  src/components/IconButton/IconButton.tsx
Labels: PR: New Feature 🕹

#1229 Fix margin between link and is related icon
  src/components/Link/Link.scss
  src/components/Link/__stories__/Link.stories.mdx
Labels: PR: Bugfix 🐛

#1235 EditableHeading - add data-testid
  src/components/EditableHeading/EditableHeading.tsx
  src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.tsx.snap
Labels: PR: unreviewed, PR: Internal 🏠

#1220 MenuItem id
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/Menu/__tests__/menu.jest.js
  src/components/Menu/MenuItem/MenuItem.tsx
Labels: PR: Bugfix 🐛
