Repository mondaycom/vibe, pull requests merged in 2023-12, with the labels that each got.

#1798 feat(Chips): allow label to accept custom Element
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/chips.stories.js
  src/components/Chips/__stories__/chips.stories.module.scss
  src/components/Chips/__stories__/chips.stories.scss
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/chips-snapshot-tests.jest.tsx
Labels: PR: New Feature 🕹

#1801 feat(EditableTypography): add onClick event
  src/components/EditableText/__tests__/editableText-tests.jest.tsx
  src/components/EditableTypography/EditableTypography.tsx
Labels: PR: New Feature 🕹

#1802 fix: changed toggle typography
  src/components/Toggle/ToggleText.tsx
  src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1803 docs: fix broken docs links
  PULL_REQUEST_TEMPLATE.md
  src/storybook/components/related-components/descriptions/colors-description/colors-description.jsx
  src/storybook/components/related-components/descriptions/shadow-description/shadow-description.jsx
  src/storybook/components/related-components/descriptions/spacing-description/spacing-description.jsx
  src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.jsx
Labels: PR: Documentation 📖

#1807 docs: useIsOverflowing.stories.js - remove maintenance warning
  src/hooks/useIsOverflowing/__stories__/useIsOverflowing.stories.js
Labels: PR: Documentation 📖

#1808 fix(Table): table does not render empty state if children are empty array
  src/components/Table/Table/__stories__/table.stories.js
  src/components/Table/Table/__tests__/table.jest.tsx
  src/components/Table/TableBody/TableBody.tsx
Labels: PR: Bugfix 🐛

#1809 fix: export Table.sizes enum
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/__stories__/table.stories.js
Labels: PR: Bugfix 🐛

#1789 Yulia/extract add button and menu to mf/split menu item
  src/components/Menu/Menu/Menu.tsx
  src/components/Menu/MenuItem/MenuItem.module.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__stories__/MenuItem.mdx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
  src/components/Menu/MenuItem/hooks/useMenuItemKeyboardEvents.ts
  src/components/Menu/MenuItem/hooks/useMenuItemMouseEvents.ts
Labels: enhancement, PR: New Feature 🕹

#1811 docs(Dropdown): fix menuPosition & menuPlacement props in argsTable controls
  src/components/Dropdown/__stories__/dropdown.stories.js
Labels: PR: Documentation 📖

#1812 chore(MenuItem): fix circular dependency with IconButton's import
  src/components/Menu/MenuItem/MenuItem.tsx
Labels: PR: Internal 🏠

#1813 build(Rollup): fail build if circular dependency detected
  rollup.config.js
Labels: PR: Internal 🏠

#1806 docs(badge): add badge description on catelog page
  src/components/Avatar/__stories__/avatar.mdx
  src/components/AvatarGroup/__stories__/AvatarGroup.mdx
  src/components/Button/__stories__/button.mdx
  src/components/Link/__stories__/Link.mdx
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/badge-description.jsx
Labels: PR: Documentation 📖

#1815 feat: <TipseenImage> add tipseenMediaClassName
  src/components/Tipseen/TipseenImage.tsx
Labels: PR: New Feature 🕹

#1791 style(Tooltip): Explicitly expose zIndex prop in component
  src/components/Tooltip/Tooltip.tsx
Labels: PR: New Feature 🕹

#1818 docs(icon): add icon description on catalog page
  src/components/IconButton/__stories__/IconButton.mdx
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/icon-description.jsx
Labels: PR: Documentation 📖

#1816 feat: Add Toast dark variation
  src/components/Toast/Toast.module.scss
  src/components/Toast/ToastConstants.ts
  src/components/Toast/__stories__/toast.mdx
  src/components/Toast/__stories__/toast.stories.js
Labels: PR: New Feature 🕹

#1820 docs: remove release section from readme
  README.md
Labels: PR: Documentation 📖

#1822 chore: update monday-ui-style
  package-lock.json
  package.json
Labels: PR: Internal 🏠

#1819 docs(slider): add slider description on catalog page
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/slider-description.jsx
Labels: PR: Documentation 📖

#1814 fix(AttentionBox): fix layout and typography
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: Bugfix 🐛

#1825 docs: virtualized-list-description - fix import
  src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx
Labels: PR: Documentation 📖

#1824 docs(Chips): remove colors which we don't want devs to use from docs
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/chips.stories.js
Labels: PR: Documentation 📖

#1821 fix: add background color to form components
  src/components/Checkbox/Checkbox.module.scss
  src/components/Dropdown/Dropdown.styles.js
  src/components/RadioButton/RadioButton.module.scss
  src/components/TextField/TextField.module.scss
Labels: PR: Bugfix 🐛

#1829 fix: update Feedback and DoubleCheck icons after monday-ui-style update
  src/components/Icon/Icons/components/DoubleCheck.tsx
  src/components/Icon/Icons/components/Feedback.tsx
Labels: PR: Bugfix 🐛

#1827 fix: Remove fucos for disabled button
  src/components/Button/Button.tsx
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1834 fix: align <SplitButton> options in Catalog with overview example
  src/storybook/components/related-components/descriptions/split-button-description.jsx
Labels: PR: Documentation 📖

#1835 docs: RelatedComponents - fix icons-description.jsx href
  src/storybook/components/related-components/descriptions/icons-description.jsx
Labels: PR: Documentation 📖

#1836 feat(Box): add a scrollable prop
  src/components/Box/Box.module.scss
  src/components/Box/Box.tsx
Labels: PR: New Feature 🕹

#1838 Split button alignment fix
  src/components/Dialog/Dialog.tsx
  src/components/SplitButton/SplitButton.module.scss
Labels: PR: Bugfix 🐛

#1837 docs: add playground addon for vibe's storybook
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/storybook/stand-alone-documentaion/playground/Playground.stories.ts
Labels: PR: Documentation 📖

#1842 type: change menu children type
  src/components/Menu/Menu/Menu.tsx
Labels: PR: Internal 🏠

#1839 fix: change Box/Menu children types to ElementContent
  src/components/Box/Box.tsx
Labels: PR: Bugfix 🐛

#1840 docs(box): add box description on catalog page
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/box-description.jsx
Labels: PR: Documentation 📖

#1844 infra: monorepo-prerelease.yml workflow
  .github/workflows/monorepo-prerelease.yml
Labels: PR: Internal 🏠

#1845 feat: add warning color LinearProgressBar
  src/components/ProgressBars/LinearProgressBar/Bar/Bar.module.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.ts
Labels: PR: New Feature 🕹

#1848 monorepo-prerelease.yml - fix - run build in monorepo root
  .github/workflows/monorepo-prerelease.yml
Labels: PR: Internal 🏠

#1841 chore(playground-addon): support next components and add an initial code example
  .storybook/preview.tsx
  src/next.ts
  src/storybook/stand-alone-documentaion/playground/Playground.stories.ts
Labels: PR: Bugfix 🐛

#1773 feat(Tooltip): add a max width prop
  src/components/Tooltip/Tooltip.module.scss
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__stories__/tooltip.stories.js
Labels: PR: New Feature 🕹

#1851 docs: Related components: fix < Steps />, < Tipseen /> - make examples clickable
  src/storybook/components/related-components/descriptions/steps-description.jsx
  src/storybook/components/related-components/descriptions/tipseen-description.jsx
Labels: PR: Documentation 📖

#1847 feat: <Dropdown> closeMenuOnScroll prop
  src/components/Dropdown/Dropdown.jsx
Labels: PR: New Feature 🕹

#1856 Fix Dropdown prop duplication
  src/components/Dropdown/Dropdown.jsx
Labels: PR: Internal 🏠

#1853 feat: <Dropdown> leftRenderer prop
  src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
Labels: PR: New Feature 🕹

#1833 fix: trigger scaling for menuButton only while clicking
  src/components/MenuButton/MenuButton.module.scss
Labels: PR: Bugfix 🐛

#1826 feat: add a Finish button to Steps
  src/components/Steps/Steps.tsx
  src/components/Steps/StepsCommand.module.scss
  src/components/Steps/StepsCommand.tsx
  src/components/Steps/StepsConstants.ts
  src/components/Steps/StepsHeader.module.scss
  src/components/Steps/StepsHeader.tsx
  src/components/Steps/__stories__/steps.stories.helpers.js
  src/components/Steps/__stories__/steps.stories.js
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/steps-tests.jest.js
  src/components/Tipseen/TipseenWizard.tsx
  src/components/Tipseen/__stories__/tipseen.mdx
  src/components/Tipseen/__stories__/tipseen.stories.js
Labels: PR: New Feature 🕹

#1858 ci: check-pr-semantic-title.yml workflow
  .github/workflows/check-pr-semantic-title.yml
Labels: PR: Internal 🏠

#1860 test(DatePicker): make tests more deterministic
  src/components/DatePicker/__tests__/DatePicker.jest.tsx
Labels: PR: Internal 🏠

#1859 docs: remove unneeded callbacks
  src/storybook/components/related-components/descriptions/tipseen-description.jsx
Labels: PR: Documentation 📖
