Repository mondaycom/vibe, pull requests merged in 2023-03, with the labels that each got.

#1146 skeleton animation use transform
  src/components/Skeleton/Skeleton.scss
Labels: PR: Bugfix 🐛

#1127 Feature/sergeyro/chips elipsis tooltip
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/chips.stories.scss
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Chips/hooks/useChipOverflowTooltip.ts
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: New Feature 🕹

#1128 Skeleton types + aria pressed + switch
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.tsx
  src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx
  src/components/Button/Button.tsx
  src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
  src/components/ButtonGroup/__tests__/__snapshots__/buttonGroup-snapshot-tests.jest.tsx.snap
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
  src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
  src/components/Modal/ModalHeader/__tests__/__snapshots__/modalHeader-snapshot-tests.jest.js.snap
  src/components/Modal/__stories__/modal.stories.mdx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
  src/components/Skeleton/Skeleton.module.scss
  src/components/Skeleton/Skeleton.scss
  src/components/Skeleton/Skeleton.tsx
  src/components/Skeleton/SkeletonConstants.ts
  src/components/Skeleton/SkeletonVariables.scss
  src/components/SplitButton/__tests__/__snapshots__/splitButton-snapshot-tests.jest.js.snap
  src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
  src/components/Switch/Switch.tsx
  src/components/Switch/hooks/useSwitchChecked.ts
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/hooks/index.js
  src/hooks/useSwitch/index.ts
  src/types/ElementContent.ts
  src/types/events.ts
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#1133 Fix getStyle if no such style
  src/helpers/typesciptCssModulesHelper.ts
Labels: PR: unreviewed, PR: Internal 🏠

#1147 Hadas and Sergey prerelease support final!
  .github/workflows/prerelease.yml
  .nvmrc
  package.json
  scripts/prerelease.js
Labels: PR: Internal 🏠

#1129 set no animation on chip as default
  .nvmrc
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
Labels: PR: Bugfix 🐛

#1151 Feature/sergeyro/tab remove inner css overrides - new prop
  src/components/Tabs/Tab/Tab.tsx
  src/components/Tabs/TabList/TabList.scss
  src/components/Tabs/TabList/TabList.tsx
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/components/Tabs/__stories__/tabs.stories.mdx
Labels: PR: unreviewed, PR: New Feature 🕹

#1152 Rename prerelease flow
  .github/workflows/prerelease.yml
  package.json
Labels: PR: unreviewed, PR: Internal 🏠

#1153 Fix Heading sizes type issue
  src/components/EditableHeading/EditableHeading.tsx
  src/components/Heading/Heading.tsx
  src/constants/sizes.ts
Labels: PR: Bugfix 🐛

#1154 Fix back prerelease flow
  .github/workflows/prerelease.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1130 Feature/sergeyro/dropdown readonly
  src/components/Chips/Chips.module.scss
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.styles.js
  src/components/Dropdown/__stories__/dropdown.stories.mdx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
  src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
  src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
  src/components/Dropdown/components/ChildrenContent/ChildrenContent.module.scss
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
  src/components/Dropdown/components/singleValue/singleValue.jsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1155 Fix combobox bug: trigger onclick event with the wrong option when categories and options not sorted
  src/components/Combobox/Combobox.jsx
  src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
  src/components/Combobox/__tests__/combobox-tests.jest.js
  src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
Labels: PR: Bugfix 🐛

#1157 export list item avatar
  src/components/index.js
  webpack/published-ts-components.js
Labels: PR: Bugfix 🐛

#1134 Feature/sergeyro/css modules prerelease 1
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Tabs/Tab/Tab.module.scss
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/Tab/Tab.tsx
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/TabList.module.scss
  src/components/Tabs/TabList/TabList.scss
  src/components/Tabs/TabList/TabList.tsx
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanel/TabPanel.module.scss
  src/components/Tabs/TabPanel/TabPanel.scss
  src/components/Tabs/TabPanel/TabPanel.tsx
  src/components/Tabs/TabPanel/__tests__/__snapshots__/tabPanel-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanels/TabPanels.module.scss
  src/components/Tabs/TabPanels/TabPanels.scss
  src/components/Tabs/TabPanels/TabPanels.tsx
  src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/TabsContext.tsx
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/TextWithHighlight/TextWithHighlight.module.scss
  src/components/TextWithHighlight/TextWithHighlight.scss
  src/components/TextWithHighlight/TextWithHighlight.tsx
  src/components/TextWithHighlight/__tests__/__snapshots__/textWithHighlight.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Toast/Toast.module.scss
  src/components/Toast/Toast.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastLink/ToastLink.module.scss
  src/components/Toast/ToastLink/ToastLink.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/components/Tooltip/Tooltip.module.scss
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
  src/components/VirtualizedGrid/VirtualizedGrid.module.scss
  src/components/VirtualizedGrid/VirtualizedGrid.tsx
  src/components/VirtualizedGrid/__tests__/__snapshots__/virtualizedGrid.jest.js.snap
  src/components/VirtualizedList/VirtualizedList.module.scss
  src/components/VirtualizedList/VirtualizedList.tsx
  src/components/VirtualizedList/__tests__/__snapshots__/virtualized-list-snapshot-tests.jest.js.snap
  src/tests/constants.ts
Labels: PR: unreviewed, PR: Internal 🏠

#1158 TextField story & fix story in Chips
  src/components/Chips/Chips.tsx
  src/components/Chips/__stories__/assets/rotem.png
  src/components/Chips/__stories__/chips.stories.mdx
  src/components/TextField/__stories__/TextField.stories.mdx
Labels: PR: New Feature 🕹

#1159 Fix dropdown bug when passing a damaged value
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1160 Feature/sergeyro/link add text classname prop
  src/components/AlertBanner/AlertBannerLink/AlertBannerLink.scss
  src/components/AlertBanner/AlertBannerLink/AlertBannerLink.tsx
  src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.jest.js.snap
  src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.jest.js.snap
  src/components/Link/Link.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1164 add ability to show the tipseen with show delay
  src/components/Tipseen/Tipseen.tsx
  src/components/Tooltip/Tooltip.tsx
Labels: PR: Bugfix 🐛

#1165 Dummy change for checking release process
  src/components/Clickable/Clickable.tsx
Labels: PR: New Feature 🕹

#1168 Revert css modules part 1 migration
  src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
  src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
  src/components/Tabs/Tab/Tab.module.scss
  src/components/Tabs/Tab/Tab.scss
  src/components/Tabs/Tab/Tab.tsx
  src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/TabList.module.scss
  src/components/Tabs/TabList/TabList.scss
  src/components/Tabs/TabList/TabList.tsx
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanel/TabPanel.scss
  src/components/Tabs/TabPanel/TabPanel.tsx
  src/components/Tabs/TabPanel/__tests__/__snapshots__/tabPanel-snapshot-tests.jest.js.snap
  src/components/Tabs/TabPanels/TabPanels.module.scss
  src/components/Tabs/TabPanels/TabPanels.scss
  src/components/Tabs/TabPanels/TabPanels.tsx
  src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
  src/components/Tabs/TabsContext/TabsContext.scss
  src/components/Tabs/TabsContext/TabsContext.tsx
  src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
  src/components/Tabs/__stories__/tabs.stories.mdx
  src/components/TextWithHighlight/TextWithHighlight.module.scss
  src/components/TextWithHighlight/TextWithHighlight.scss
  src/components/TextWithHighlight/TextWithHighlight.tsx
  src/components/TextWithHighlight/__tests__/__snapshots__/textWithHighlight.jest.js.snap
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Toast/Toast.module.scss
  src/components/Toast/Toast.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/ToastLink/ToastLink.scss
  src/components/Toast/ToastLink/ToastLink.tsx
  src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
  src/components/Tooltip/Tooltip.scss
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
  src/components/VirtualizedGrid/VirtualizedGrid.scss
  src/components/VirtualizedGrid/VirtualizedGrid.tsx
  src/components/VirtualizedGrid/__tests__/__snapshots__/virtualizedGrid.jest.js.snap
  src/components/VirtualizedList/VirtualizedList.scss
  src/components/VirtualizedList/VirtualizedList.tsx
  src/components/VirtualizedList/__tests__/__snapshots__/virtualized-list-snapshot-tests.jest.js.snap
  src/tests/constants.ts
Labels: PR: Bugfix 🐛

#1169 Prerelease add trigger - workflow_dispatch
  .github/workflows/prerelease.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1170 Prerelease workflow: add workflow_dispatch
  .github/workflows/prerelease.yml
Labels: PR: unreviewed, PR: Internal 🏠

#1172 MenuItem: add iconWrapperClassName prop
  src/components/Menu/MenuItem/MenuItem.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1174 Support on attention box renderer and link
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.module.scss
  src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
  src/components/AttentionBox/__stories__/attentionBox.stories.mdx
  src/components/AttentionBox/__stories__/attentionBox.stories.scss
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
  src/components/AttentionBox/__tests__/attentionBox-snapshot-tests.jest.tsx
Labels: PR: Bugfix 🐛

#1175 Feature/sergeyro/modal close button aria label default value
  src/components/Modal/Modal.tsx
  src/components/Modal/__tests__/__snapshots__/modal-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#1180 ModalHeader: JsxElement in description
  src/components/Modal/ModalHeader/ModalHeader.tsx
Labels: PR: New Feature 🕹

#1182 Team (Yael & Sergey) photos update
  src/storybook/stand-alone-documentaion/welcome/assets/Sergey.png
  src/storybook/stand-alone-documentaion/welcome/assets/Yael.png
  src/storybook/stand-alone-documentaion/welcome/assets/index.js
  src/storybook/stand-alone-documentaion/welcome/contributors/contributors.jsx
Labels: PR: unreviewed, PR: Documentation 📖

#1184 Yael photo update
  src/storybook/stand-alone-documentaion/welcome/assets/Yael.png
Labels: PR: reviewed-approved, PR: Documentation 📖

#1183 change the build of css modules to calculate the hash according to co…
  package-lock.json
  package.json
  rollup.config.js
  src/components/Avatar/Avatar.scss
  src/components/Avatar/AvatarConstants.scss
  src/components/AvatarGroup/AvatarGroup.module.scss
  src/components/AvatarGroup/AvatarGroupCounter.module.scss
Labels: PR: New Feature 🕹

#1186 fix interactions test location
  package.json
  rollup.config.js
  scripts/prerelease.js
Labels: PR: Bugfix 🐛

#1190 Add titleClassName props to customize TipseenTitle
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/TipseenBasicContent.tsx
  src/components/Tipseen/TipseenContent.tsx
  src/components/Tipseen/TipseenWizard.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1191 Toggle add toggleSelectedClassName
  src/components/Toggle/MockToggle.tsx
  src/components/Toggle/Toggle.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1196 Feature/sergeyro/buttons tab index props
  src/components/Button/Button.tsx
  src/components/IconButton/IconButton.tsx
Labels: PR: unreviewed, PR: New Feature 🕹

#1188 Fix/sergeyro/heading overflow
  src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
  src/components/Heading/__stories__/Heading.stories.mdx
  src/components/Heading/__tests__/__snapshots__/heading.jest.js.snap
  src/components/Heading/__tests__/heading.jest.js
  src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
  src/styles/typography.scss
Labels: PR: unreviewed, PR: Bugfix 🐛
