Repository mondaycom/vibe, pull requests merged in 2023-09, with the labels that each got.

#1522 fix: <BreadcrumbsBar> type
  src/components/BreadcrumbsBar/BreadcrumbsBar.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1523 feat(Tipseen): allow withoutDialog for component
  src/components/Tipseen/Tipseen.tsx
Labels: PR: New Feature 🕹

#1525 Revert "chore: fail chromatic action check in case has visual changes (#1392)
  .github/workflows/chromatic.yml
Labels: PR: Internal 🏠

#1528 feat(Tipseen): add floating variation for Tipseen
  src/components/Tipseen/Tipseen.module.scss
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tooltip/Tooltip.tsx
Labels: PR: New Feature 🕹

#1511 fix(Dropdown): when used inside overflowed container with transform, consider container scroll
  src/components/Dropdown/Dropdown.styles.js
  src/storybook/patterns/dropdown-in-modals/ModalExampleContent.tsx
  src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.mdx
  src/utils/dom-utils.ts
Labels: PR: Bugfix 🐛

#1529 docs: Change <LegacyHeading> name in the story
  src/components/LegacyHeading/__stories__/LegacyHeading.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1524 feat(Text): remove paragraph prop (can be achieved with element="p")
  src/components/AttentionBox/AttentionBox.tsx
  src/components/Text/Text.tsx
  src/components/Text/__stories__/Text.stories.mdx
  src/components/Text/__tests__/__snapshots__/text-snapshot-tests.jest.js.snap
  src/components/Text/__tests__/text-snapshot-tests.jest.js
  src/components/Tipseen/Tipseen.tsx
Labels: PR: New Feature 🕹

#1534 fix: <MenuItem/> Tooltip shouldn't cover the icon
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
Labels: PR: unreviewed, PR: Bugfix 🐛

#1530 feat(Table): table leftovers phase 1
  src/components/Table/Table/__stories__/table.stories.mdx
  src/components/Table/Table/tableHelpers.ts
  src/components/Table/TableHeader/TableHeader.module.scss
  src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
  src/components/Table/TableHeaderCell/TableHeaderCell.tsx
Labels: PR: New Feature 🕹

#1535 feat: add a11y arias props for `List`, `ListItem`, and `Button`
  src/components/Button/Button.tsx
  src/components/List/List.tsx
  src/components/ListItem/ListItem.tsx
Labels: PR: New Feature 🕹

#1537 feat(Tipseen): in floating variation do not show tip, make docs for variation clearer
  src/components/Tipseen/Tipseen.tsx
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
  src/components/Tipseen/__tests__/tipseen-tests.jest.js
Labels: PR: New Feature 🕹

#1521 chore(browserslist): Use browserslist-config-monday on Vibe
  package-lock.json
  package.json
Labels: PR: Internal 🏠

#1538 <AttentionBox> withoutIcon remove padding
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/AttentionBox/AttentionBox.tsx
  src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#1540 fix(TipseenTitle): font size should be TEXT1 (16px)
  src/components/Tipseen/TipseenTitle.tsx
  src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
Labels: PR: Bugfix 🐛

#1541 fix(Table): export table-related components
  src/components/index.js
Labels: PR: Bugfix 🐛

#1543 <DropdownMenu> - disable animation when using menuPortalTarget - temp fix
  src/components/Dropdown/components/menu/menu.jsx
  src/components/Dropdown/components/menu/menu.module.scss
Labels: PR: unreviewed, PR: Bugfix 🐛

#1545 Exposed the ability to control the search icon for combobox
  src/components/Combobox/Combobox.tsx
  src/components/Combobox/__stories__/combobox.stories.mdx
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
Labels: PR: reviewed-approved, PR: New Feature 🕹

#1546 fix: <ListItem> children type change to ElementContent
  src/components/ListItem/ListItem.tsx
Labels: PR: unreviewed, PR: Bugfix 🐛

#1520 Added the ability for combobox categories to get classNames and inline color as props
  src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
  src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
  src/components/Combobox/__tests__/combobox-tests.jest.js
  src/components/Combobox/components/ComboboxCategory/ComboboxCategory.tsx
  src/components/Combobox/components/ComboboxConstants.ts
Labels: enhancement, PR: New Feature 🕹

#1549 fix: <Chips> text overflow Tooltip issue - replace internal Tooltip logic with Text overflow Tooltip logic
  src/components/Chips/Chips.module.scss
  src/components/Chips/Chips.tsx
  src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
  src/components/Chips/hooks/useChipOverflowTooltip.ts
  src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
Labels: PR: unreviewed, PR: Bugfix 🐛

#1542 feat(Table): table leftovers
  src/components/Table/Table/Table.module.scss
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/TableConsts.ts
  src/components/Table/Table/__stories__/helpers.js
  src/components/Table/Table/__stories__/table.stories.mdx
  src/components/Table/Table/__stories__/table.stories.scss
  src/components/Table/Table/__tests__/table.jest.tsx
  src/components/Table/Table/tableHelpers.ts
  src/components/Table/TableBody/TableBody.module.scss
  src/components/Table/TableBody/TableBody.tsx
  src/components/Table/TableCellSkeleton/TableCellSkeleton.module.scss
  src/components/Table/TableCellSkeleton/TableCellSkeleton.tsx
  src/components/Table/TableHeader/TableHeader.module.scss
  src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
  src/components/Table/TableHeaderCell/TableHeaderCell.tsx
  src/components/Table/TableRow/TableRow.module.scss
  src/tests/constants.ts
Labels: PR: New Feature 🕹

#1548 feat(Tipseen): add TipseenMedia component to act as a container for tipseen medias
  src/components/Tipseen/TipseenImage.module.scss
  src/components/Tipseen/TipseenImage.tsx
  src/components/Tipseen/TipseenMedia/TipseenMedia.module.scss
  src/components/Tipseen/TipseenMedia/TipseenMedia.tsx
  src/components/Tipseen/__stories__/assets/index.js
  src/components/Tipseen/__stories__/assets/video.mp4
  src/components/Tipseen/__stories__/tipseen.stories.mdx
  src/components/index.js
  src/tests/constants.ts
  webpack/published-ts-components.js
Labels: PR: New Feature 🕹

#1550 fix(TipseenMedia): fix import/export path
  webpack/published-ts-components.js
Labels: PR: Internal 🏠

#1555 feat(Table): add vibe component props to all table-related components make components VibeComponent type - with forwardRef
  src/components/Table/Table/Table.tsx
  src/components/Table/TableBody/TableBody.tsx
  src/components/Table/TableCell/TableCell.tsx
  src/components/Table/TableHeader/TableHeader.tsx
  src/components/Table/TableHeaderCell/TableHeaderCell.tsx
  src/components/Table/TableRow/TableRow.tsx
  src/tests/constants.ts
Labels: PR: New Feature 🕹

#1553 Infra/talko/flaky chromatic tests
  src/components/Chips/__stories__/assets/person1.png
  src/components/Dialog/__stories__/Dialog.stories.mdx
  src/components/Label/__stories__/label.stories.mdx
  src/components/Tooltip/__stories__/tooltip.stories.mdx
Labels: PR: Documentation 📖

#1557 docs: add missing up next links
  src/storybook/components/related-components/descriptions/clickable-description/clickable-description.jsx
  src/storybook/components/related-components/descriptions/colors-description/colors-description.jsx
  src/storybook/components/related-components/descriptions/shadow-description/shadow-description.jsx
  src/storybook/components/related-components/descriptions/spacing-description/spacing-description.jsx
  src/storybook/components/related-components/descriptions/typography-description/typography-description.jsx
Labels: PR: Documentation 📖

#1554 docs: <Dialog> - Dialog with tooltip story
  src/components/Dialog/__stories__/Dialog.stories.mdx
Labels: PR: unreviewed, PR: Documentation 📖

#1560 fix: remove preventDefault from useKeyboardButtonPressedFunc.ts
  src/hooks/useKeyboardButtonPressedFunc.ts
Labels: PR: unreviewed, PR: Bugfix 🐛

#1562 chore(rollup): export sourcemap with build
  rollup.config.js
Labels: PR: Internal 🏠
