Repository mondaycom/vibe, pull requests merged in 2024-01, with the labels that each got.

#1846 docs: RelatedComponents - table-description.tsx
  src/components/Accordion/Accordion/__stories__/accordion.mdx
  src/components/ExpandCollapse/__stories__/ExpandCollapse.mdx
  src/components/Modal/__stories__/modal.mdx
  src/components/Table/Table/__stories__/table.mdx
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/table-description.tsx
Labels: PR: Documentation 📖

#1861 feat(Table): add no border variant
  src/components/Table/Table/Table.module.scss
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/__stories__/table.mdx
  src/components/Table/Table/__stories__/table.stories.helpers.js
  src/components/Table/Table/__stories__/table.stories.js
  src/components/Table/Table/__stories__/table.stories.module.scss
Labels: PR: New Feature 🕹

#1865 docs: fix <Menu> link in catalog
  src/storybook/components/related-components/descriptions/menu-description.jsx
Labels: PR: Documentation 📖

#1871 feat(Table): add option to supply %, fr, px as width for table
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/__tests__/tableHelpers.jest.tsx
  src/components/Table/Table/tableHelpers.ts
Labels: PR: New Feature 🕹

#1867 feat(Label): add a disabled state to submenu button
  src/components/Menu/MenuItem/MenuItem.module.scss
  src/components/Menu/MenuItem/MenuItem.tsx
Labels: PR: New Feature 🕹

#1866 fix(Label): change padding according to design
  src/components/Label/Label.module.scss
  src/components/Label/__stories__/label.stories.js
  src/storybook/stand-alone-documentaion/catalog/catalog.stories.js
Labels: PR: Bugfix 🐛

#1874 fix(MenuItemButton): fix type for kind
  src/components/Menu/MenuItemButton/MenuItemButton.tsx
Labels: PR: Bugfix 🐛

#1875 docs: change sidebar organization
  src/components/Dialog/__stories__/Dialog.stories.js
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.js
Labels: PR: Documentation 📖

#1876 feat(EditableText): add isEditMode prop
  src/components/EditableTypography/EditableTypography.tsx
Labels: PR: New Feature 🕹

#1883 feat(EditableTypography): expose mode change event
  src/components/EditableTypography/EditableTypography.module.scss
  src/components/EditableTypography/EditableTypography.tsx
Labels: PR: Bugfix 🐛

#1884 docs: fix font weights in typography examples' mixin
  src/storybook/stand-alone-documentaion/typography/typography.mdx
Labels: PR: Documentation 📖

#1882 fix(TableCellSkeleton): circle and rectangle loading types are broken (have width 0)
  src/components/Table/TableCellSkeleton/TableCellSkeleton.tsx
Labels: PR: Bugfix 🐛

#1880 docs: fix typo in Label and and warning in OtherContributorsList
  src/components/Label/__stories__/label.mdx
  src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.tsx
Labels: PR: Documentation 📖

#1887 fix: replace primary-background-hover color in non-hover
  package-lock.json
  package.json
  src/components/AttentionBox/AttentionBox.module.scss
  src/components/AvatarGroup/AvatarGroupCounter.module.scss
  src/components/Counter/Counter.module.scss
  src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
  src/components/Loader/Loader.module.scss
  src/components/ProgressBars/LinearProgressBar/LinearProgressBar.module.scss
  src/components/Skeleton/Skeleton.module.scss
  src/components/Tabs/Tab/Tab.module.scss
Labels: PR: Bugfix 🐛

#1892 docs: add virtualized grid description and component
  src/storybook/components/related-components/component-description-map.tsx
  src/storybook/components/related-components/descriptions/virtualized-grid-description/virtualized-grid-description.jsx
  src/storybook/components/related-components/descriptions/virtualized-grid-description/virtualizedGrid.module.scss
Labels: PR: Documentation 📖

#1891 fix(TableVirtualizedBody): take height of header into consideration
  src/components/Table/TableVirtualizedBody/TableVirtualizedBody.module.scss
  src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
Labels: PR: Bugfix 🐛

#1890 feat(AttentionBoxLink): use link component
  src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.module.scss
  src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
  src/components/AttentionBox/__stories__/attentionBox.stories.js
  src/components/Typography/Typography.module.scss
Labels: PR: New Feature 🕹

#1893 feat(AvatarBadge): add an icon prop
  src/components/Avatar/AvatarBadge.tsx
Labels: PR: New Feature 🕹

#1895 chore: update Playground addon
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/storybook/stand-alone-documentaion/playground/Playground.stories.ts
  src/storybook/stand-alone-documentaion/playground/playground-helpers.ts
Labels: PR: Internal 🏠

#1899 chore: update Playground addon
  package-lock.json
  package.json
  src/storybook/stand-alone-documentaion/playground/Playground.stories.ts
  src/storybook/stand-alone-documentaion/playground/playground-helpers.ts
Labels: PR: Documentation 📖

#1900 chore(chromatic): add a command to run chromatic locally
  .gitignore
  package.json
Labels: PR: Internal 🏠

#1901 feat: add tooltip props
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/MenuButton/MenuButton.tsx
Labels: PR: New Feature 🕹

#1903 chore: add codeowners
  CODEOWNERS
Labels: PR: Internal 🏠

#1905 docs: Realated components fixes - editable text and menu button titles
  src/storybook/components/related-components/descriptions/editable-text-description.tsx
  src/storybook/components/related-components/descriptions/menu-button-description.jsx
Labels: PR: Documentation 📖

#1906 feat(Icons): add Translation icon
  package-lock.json
  package.json
  src/components/Icon/Icons/components/Translation.tsx
  src/components/Icon/Icons/index.ts
Labels: PR: Icon 💎

#1907 feat: add tooltip props to components
  src/components/EditableTypography/EditableTypography.tsx
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/MenuButton/MenuButton.tsx
Labels: PR: New Feature 🕹

#1908 feat(TableVirtualizedBody): pass onScroll event
  src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
Labels: PR: New Feature 🕹

#1909 fix(TableVirtualized): support row height
  src/components/Table/Table/Table.module.scss
  src/components/Table/Table/Table.tsx
  src/components/Table/Table/TableConsts.ts
  src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
Labels: PR: Bugfix 🐛

#1910 fix(EditableTypography): don't spread tooltipProps
  src/components/EditableTypography/EditableTypography.tsx
Labels: PR: Bugfix 🐛

#1915 feat(TabList): add opt-out for default padding
  src/components/Tabs/TabList/TabList.module.scss
  src/components/Tabs/TabList/TabList.tsx
  src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
  src/components/Tabs/TabList/__tests__/tabList-snapshot-tests.jest.js
Labels: PR: New Feature 🕹

#1916 feat: add email TextFieldTextType
  src/components/TextField/TextFieldConstants.ts
  src/components/TextField/__tests__/TextField.jest.js
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/textField-snapshot-tests.jest.js
Labels: PR: New Feature 🕹

#1918 feat: add tel TextFieldTextType
  src/components/TextField/TextFieldConstants.ts
  src/components/TextField/__tests__/TextField.jest.js
  src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
  src/components/TextField/__tests__/textField-snapshot-tests.jest.js
Labels: PR: New Feature 🕹

#1919 fix: fix animation for menu with editable typography
  src/components/EditableTypography/EditableTypography.tsx
Labels: PR: Bugfix 🐛

#1912 fix(MenuButton): fix dialog close behavior
  src/components/Menu/MenuItem/hooks/useMenuItemKeyboardEvents.ts
  src/components/MenuButton/MenuButton.tsx
Labels: PR: Bugfix 🐛

#1904 fix(MenuItem): split menu items does not open sub-menu when navigating directly between two split menus
  src/components/Menu/MenuItem/hooks/useMenuItemMouseEvents.ts
Labels: PR: Bugfix 🐛

#1914 fix(MenuItem): tooltip should on all item and not only on title
  src/components/Menu/Menu/Menu.module.scss
  src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
  src/components/Menu/Menu/__tests__/menu-interactions.js
  src/components/Menu/MenuItem/MenuItem.module.scss
  src/components/Menu/MenuItem/MenuItem.tsx
  src/components/Menu/MenuItem/__tests__/MenuItem.jest.js
  src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
  src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/splitButtonMenu-snapshot-tests.jest.tsx.snap
  src/tests/interactions-utils.ts
Labels: PR: Bugfix 🐛

#1852 feat: <ThemeProvider> add systemTheme prop - adds className to body
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/ThemeProviderConstants.ts
  src/components/ThemeProvider/ThemeProviderUtils.ts
  src/components/ThemeProvider/__stories__/ThemeProvider.mdx
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.js
  src/components/ThemeProvider/__tests__/themeProvider.interactions.ts
  src/services/themes.js
Labels: PR: New Feature 🕹

#1869 feat!: <ThemeProvider> add wrapping div (!), rename theme prop to themeConfig
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/ThemeProviderUtils.ts
  src/components/ThemeProvider/__stories__/ThemeProvider.mdx
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.helpers.tsx
  src/components/ThemeProvider/__stories__/ThemeProvider.stories.js
  src/components/ThemeProvider/__tests__/themeProvider-tests.jest.js
Labels: PR: New Feature 🕹
