Repository mondaycom/vibe, pull requests merged in 2024-10, with the labels that each got.

#2458 feat: SSR support fixes
  packages/core/src/components/Dialog/Dialog.tsx
  packages/core/src/components/Dropdown/Dropdown.tsx
  packages/core/src/components/Dropdown/__stories__/Dropdown.mdx
  packages/core/src/components/Dropdown/__stories__/Dropdown.stories.helpers.tsx
  packages/core/src/components/Dropdown/__stories__/Dropdown.stories.js
  packages/core/src/components/Dropdown/__tests__/Dropdown.snapshot.test.js
  packages/core/src/components/Dropdown/__tests__/driver.js
  packages/core/src/components/EditableInput/EditableInput.tsx
  packages/core/src/components/LegacyEditableHeading/LegacyEditableHeading.tsx
  packages/core/src/components/LegacyHeading/LegacyHeading.tsx
  packages/core/src/components/Menu/Menu/Menu.tsx
  packages/core/src/hooks/ssr/useIsomorphicLayoutEffect.ts
  packages/core/src/hooks/useMergeRef.ts
  packages/core/src/utils/ssr-utils.ts
Labels: PR: Bugfix 🐛

#2466 feat: add inputAriaLabel to Dropdown component
  packages/core/src/components/Dropdown/Dropdown.tsx
  packages/core/src/components/Dropdown/Dropdown.types.ts
  packages/core/src/components/Dropdown/DropdownConstants.ts
Labels: feature, Dropdown

#2484 fix: Fix ellipsis clamp lines for SSR [prerelease]
  packages/core/package.json
  packages/core/src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
  packages/core/src/components/Typography/Typography.tsx
  packages/core/src/components/Typography/TypographyHooks.tsx
  yarn.lock
Labels: bug

#2485 Add placeholder for custom svg icon for SSR [prerelease]
  packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
  packages/core/src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
  packages/core/src/components/Icon/Icon.tsx
  packages/core/src/components/Modal/__tests__/__snapshots__/Modal.snapshot.test.js.snap
  packages/core/src/components/Tipseen/__tests__/__snapshots__/Tipseen.test.tsx.snap
  packages/core/src/components/Typography/TypographyHooks.tsx
  packages/core/src/hooks/ssr/useIsMounted.ts
  packages/core/src/utils/ssr-utils.ts
Labels: bug
