Repository mondaycom/vibe, pull requests merged in 2024-09, with the labels that each got.

#2409 fix: alpha fixes
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/Dropdown/Dropdown.styles.js
  packages/core/src/components/Dropdown/Dropdown.tsx
  packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
  packages/core/types/packages.d.ts
Labels: vibe3

#2383 feat: layering floating components on modals
  packages/core/.storybook/preview-body.html
  packages/core/.storybook/preview-head.html
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
  packages/core/src/components/Dialog/Dialog.tsx
  packages/core/src/components/LayerProvider/LayerContext.ts
  packages/core/src/components/LayerProvider/LayerProvider.tsx
  packages/core/src/components/LayerProvider/index.ts
  packages/core/src/components/MenuButton/MenuButton.tsx
  packages/core/src/components/Modal/Modal.module.scss
  packages/core/src/components/Modal/Modal.tsx
  packages/core/src/components/Tooltip/Tooltip.module.scss
  packages/core/src/components/Tooltip/Tooltip.tsx
  packages/core/src/components/index.ts
  packages/storybook-blocks/.storybook/preview-head.html
Labels: breaking change, vibe3

#2381 docs: migration guide and docs
  CONTRIBUTING.md
  docs/vibe2-migration-guide.md
  packages/core/.storybook/main.ts
  packages/core/.storybook/preview.tsx
  packages/core/docs/vibe-3-changelog.md
  packages/core/package.json
  packages/core/plop/component/component-index.txt
  packages/core/plop/component/component-stories-mdx.txt
  packages/core/plop/component/component-stories-tsx.txt
  packages/core/plop/component/component-tests.txt
  packages/core/plop/component/component-ts.txt
  packages/core/plop/component/component-types.txt
  packages/core/plop/component/index.js
  packages/core/plop/general/component-stories-helpers-js.txt
  packages/core/plop/general/component-stories-scss.txt
  packages/core/plop/hooks/hook-story-js.txt
  packages/core/plop/hooks/hook-story-scss.txt
  packages/core/plop/hooks/hook-story.txt
  packages/core/plop/hooks/hook.txt
  packages/core/plop/hooks/index.js
  packages/core/plop/stories/index.js
  packages/core/plop/tests/index.js
  packages/core/plopfile.js
  packages/core/src/storybook/components/DiffCodeBlock.tsx
  packages/core/src/storybook/components/related-components/descriptions/typography-description/typography-description.jsx
  packages/core/src/storybook/stand-alone-documentaion/assets/layers.gif
  packages/core/src/storybook/stand-alone-documentaion/assets/package-split.png
  packages/core/src/storybook/stand-alone-documentaion/assets/props.gif
  packages/core/src/storybook/stand-alone-documentaion/catalog/EmptyState/Catalog.stories.EmptyState.tsx
  packages/core/src/storybook/stand-alone-documentaion/catalog/EmptyState/emptyStateExample.svg
  packages/core/src/storybook/stand-alone-documentaion/changelog.mdx
  packages/core/src/storybook/stand-alone-documentaion/changelog/changelog.mdx
  packages/core/src/storybook/stand-alone-documentaion/migration-guide.mdx
  packages/core/src/storybook/stand-alone-documentaion/typography/assets/index.ts
  packages/core/src/storybook/stand-alone-documentaion/typography/assets/migrationTable.png
  packages/core/src/storybook/stand-alone-documentaion/typography/typograpghy.stories.helpers.tsx
  packages/core/src/storybook/stand-alone-documentaion/typography/typography-migration-guide.mdx
  packages/core/src/storybook/stand-alone-documentaion/welcome/welcome.mdx
  packages/storybook-blocks/src/components/anchor-list-item/anchor-list-item.module.scss
  yarn.lock
Labels: vibe3

#2425 Codemod update prop name
  packages/codemod/src/utils/__tests__/prop-utils.test.ts
  packages/codemod/src/utils/prop-utils.ts
  packages/codemod/transformations/core/v2-to-v3/__tests__/AttentionBox-component-migration.test.ts
  packages/codemod/transformations/core/v2-to-v3/__tests__/menu-component-migration.test.ts
Labels: vibe3, codemod

#2427 chore(codemod): interactive cli
  packages/codemod/README.md
  packages/codemod/bin/vibe-codemod.js
  packages/codemod/bin/vibe-codemod.ts
  packages/codemod/package.json
  packages/codemod/src/utils/report-utils.ts
  packages/codemod/tsconfig.json
  packages/codemod/vitest.config.ts
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/storybook/stand-alone-documentaion/migration-guide.mdx
  yarn.lock
Labels: vibe3
