Repository mondaycom/vibe, pull requests merged in 2024-07, with the labels that each got.

#2199 chore(SplitButton): remove dataTestId props from nested elements
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/components/Menu/MenuItem/MenuItem.tsx
  packages/core/src/components/SplitButton/SplitButton.tsx
Labels: breaking change

#2210 docs: fix typos
  packages/core/src/components/AlertBanner/__stories__/AlertBanner.mdx
  packages/core/src/components/Checkbox/__stories__/Checkbox.mdx
  packages/core/src/storybook/stand-alone-documentaion/accessibility/accessibility.mdx
Labels: documentation

#2213 chore: init 'codemod' - a new package to store Vibe's codemods
  packages/codemod/.eslintrc.json
  packages/codemod/package.json
  packages/codemod/test/setup.ts
  packages/codemod/tsconfig.json
  packages/codemod/tsconfig.test.json
  packages/codemod/vitest.config.ts
Labels: vibe3, codemod

#2214 chore(AttentionBox): codemod for migration of AttentionBox from core - v2 to v3
  packages/codemod/package.json
  packages/codemod/src/consts/index.ts
  packages/codemod/src/consts/vibe-import-paths.ts
  packages/codemod/src/utils/component-jsx-utils.ts
  packages/codemod/src/utils/import-utils.ts
  packages/codemod/src/utils/index.ts
  packages/codemod/src/utils/prop-utils.ts
  packages/codemod/src/utils/report-utils.ts
  packages/codemod/src/utils/wrap-transformation.ts
  packages/codemod/transformations/core/v2-to-v3/__tests__/attention-box-component-migration.test.ts
  packages/codemod/transformations/core/v2-to-v3/attention-box-component-migration.ts
  packages/codemod/types/index.ts
  packages/codemod/types/paths.types.ts
  packages/codemod/types/transformation-context.types.ts
  packages/codemod/vitest.config.ts
  yarn.lock
Labels: vibe3, codemod

#2229 chore(Tipseen): remove deprecated props [breaking]
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/components/Tipseen/TipseenConstants.ts
  packages/core/src/components/Tipseen/TipseenContent.tsx
Labels: breaking change, vibe3

#2232 chore(TextField): remove requiredAsterisk prop
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/components/FieldLabel/FieldLabel.module.scss
  packages/core/src/components/FieldLabel/FieldLabel.tsx
  packages/core/src/components/TextField/TextField.tsx
  packages/core/src/components/TextField/__stories__/TextField.mdx
  packages/core/src/components/TextField/__stories__/TextField.stories.tsx
Labels: breaking change, vibe3

#2233 fix(DialogContentContainer): fix size medium spacing
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/components/ColorPicker/__tests__/__snapshots__/ColorPicker.test.tsx.snap
  packages/core/src/components/DialogContentContainer/DialogContentContainer.module.scss
  packages/core/src/components/DialogContentContainer/DialogContentContainer.tsx
  packages/core/src/components/DialogContentContainer/__tests__/__snapshots__/DialogContentContainer.test.tsx.snap
Labels: breaking change, vibe3

#2216 chore(Chips): codemod for migration of Chips from core - v2 to v3
  packages/codemod/src/utils/report-utils.ts
  packages/codemod/transformations/core/v2-to-v3/__tests__/chips-component-migration.test.ts
  packages/codemod/transformations/core/v2-to-v3/chips-component-migration.ts
Labels: vibe3, codemod

#2247 chore: remove Link.target static prop
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
  packages/core/src/components/Link/Link.tsx
  packages/core/src/components/Link/__tests__/Link.test.tsx
Labels: breaking change, vibe3

#2234 chore(AlertBanner): deprecate enums
  packages/core/src/components/AlertBanner/AlertBanner.tsx
  packages/core/src/components/AlertBanner/AlertBanner.types.ts
  packages/core/src/components/AlertBanner/AlertBannerConstants.ts
  packages/core/src/components/AlertBanner/__stories__/AlertBanner.mdx
  packages/core/src/components/AlertBanner/__stories__/AlertBanner.stories.tsx
  packages/core/src/components/AlertBanner/__tests__/AlertBanner.snapshot.test.tsx
  packages/core/src/components/AlertBanner/__tests__/__snapshots__/AlertBanner.snapshot.test.tsx.snap
  packages/core/src/components/AlertBanner/index.ts
Labels: breaking change, vibe3

#2235 chore(AttentionBox): deprecate enums
  packages/core/src/components/AttentionBox/AttentionBox.tsx
  packages/core/src/components/AttentionBox/AttentionBox.types.ts
  packages/core/src/components/AttentionBox/AttentionBoxConstants.ts
  packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.tsx
  packages/core/src/components/AttentionBox/__tests__/AttentionBox.snapshot.test.tsx
  packages/core/src/components/AttentionBox/index.ts
Labels: breaking change, vibe3

#2236 chore(Avatar): deprecate enums
  packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.tsx
  packages/core/src/components/Avatar/Avatar.tsx
  packages/core/src/components/Avatar/Avatar.types.ts
  packages/core/src/components/Avatar/AvatarBadge.tsx
  packages/core/src/components/Avatar/AvatarConstants.tsx
  packages/core/src/components/Avatar/AvatarContent.tsx
  packages/core/src/components/Avatar/__stories__/Avatar.mdx
  packages/core/src/components/Avatar/__stories__/Avatar.stories.tsx
  packages/core/src/components/Avatar/index.ts
  packages/core/src/components/AvatarGroup/AvatarGroup.tsx
  packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
  packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
  packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipContent.tsx
  packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.tsx
  packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx
  packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.js
  packages/core/src/components/AvatarGroup/__tests__/AvatarGroup.snapshot.test.js
  packages/core/src/components/Badge/__stories__/Badge.mdx
  packages/core/src/components/Badge/__stories__/Badge.stories.tsx
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.mdx
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.stories.tsx
  packages/core/src/components/Chips/Chips.tsx
  packages/core/src/components/Chips/__stories__/Chips.stories.tsx
  packages/core/src/components/Combobox/__stories__/Combobox.stories.tsx
  packages/core/src/components/Combobox/__stories__/OptionRenderer.jsx
  packages/core/src/components/Counter/__stories__/Counter.stories.tsx
  packages/core/src/components/Dropdown/__stories__/Dropdown.stories.js
  packages/core/src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
  packages/core/src/components/IconButton/__stories__/IconButton.stories.tsx
  packages/core/src/components/List/__stories__/List.stories.tsx
  packages/core/src/components/ListItemAvatar/ListItemAvatar.tsx
  packages/core/src/components/Skeleton/__stories__/Skeleton.stories.js
  packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
  packages/core/src/storybook/components/related-components/descriptions/avatar-description.jsx
  packages/core/src/storybook/components/related-components/descriptions/avatar-group-description.jsx
Labels: breaking change, vibe3

#2230 types(Button): make children required
  packages/core/docs/vibe-3-changelog.md
  packages/core/src/components/Button/Button.tsx
  packages/core/src/components/Steps/Steps.tsx
  packages/core/src/components/Steps/StepsCommand.tsx
  packages/core/src/components/Tipseen/TipseenWizard.tsx
Labels: breaking change, vibe3

#2237 chore(Divider): deprecate enums
  packages/core/src/components/Divider/Divider.tsx
  packages/core/src/components/Divider/Divider.types.ts
  packages/core/src/components/Divider/DividerConstants.ts
  packages/core/src/components/Divider/__stories__/Divider.stories.tsx
  packages/core/src/components/Divider/index.ts
  packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.tsx
Labels: breaking change, vibe3

#2270 chore(Counter): deprecate enums
  packages/core/src/components/AvatarGroup/AvatarGroup.tsx
  packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
  packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.js
  packages/core/src/components/Badge/Badge.tsx
  packages/core/src/components/Counter/Counter.tsx
  packages/core/src/components/Counter/Counter.types.ts
  packages/core/src/components/Counter/CounterConstants.ts
  packages/core/src/components/Counter/__stories__/Counter.stories.tsx
  packages/core/src/components/Counter/__tests__/Counter.snapshot.test.tsx
  packages/core/src/components/Counter/index.ts
  packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
Labels: breaking change, vibe3

#2264 chore(Toast): deprecate enums
  packages/core/src/components/Toast/Toast.tsx
  packages/core/src/components/Toast/Toast.types.ts
  packages/core/src/components/Toast/ToastConstants.ts
  packages/core/src/components/Toast/ToastHelpers.tsx
  packages/core/src/components/Toast/__stories__/Toast.mdx
  packages/core/src/components/Toast/__stories__/Toast.stories.tsx
  packages/core/src/components/Toast/__tests__/Toast.snapshot.test.tsx
  packages/core/src/components/Toast/__tests__/Toast.test.tsx
  packages/core/src/components/Toast/__tests__/__snapshots__/Toast.snapshot.test.tsx.snap
  packages/core/src/components/Toast/index.ts
  packages/core/src/storybook/components/related-components/descriptions/toast-description.jsx
Labels: breaking change, vibe3

#2275 chore(Link): deprecate enums
  packages/core/src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
  packages/core/src/components/Badge/__stories__/Badge.stories.tsx
  packages/core/src/components/Link/Link.tsx
  packages/core/src/components/Link/Link.types.ts
  packages/core/src/components/Link/LinkConsts.ts
  packages/core/src/components/Link/__stories__/Link.mdx
  packages/core/src/components/Link/__stories__/Link.stories.tsx
  packages/core/src/components/Link/__tests__/Link.snapshot.test.tsx
  packages/core/src/components/Link/__tests__/Link.test.tsx
  packages/core/src/components/Link/index.ts
  packages/core/src/storybook/components/related-components/descriptions/link-description.jsx
  packages/core/src/storybook/stand-alone-documentaion/typography/typography-migration-guide.mdx
  packages/core/src/storybook/stand-alone-documentaion/welcome/contributor/contributor.jsx
Labels: breaking change, vibe3

#2263 chore(List): deprecate enums
  packages/core/src/components/List/List.tsx
  packages/core/src/components/List/List.types.ts
  packages/core/src/components/List/ListConstants.ts
  packages/core/src/components/List/__stories__/List.stories.tsx
  packages/core/src/components/List/index.ts
  packages/core/src/components/List/utils/ListUtils.ts
  packages/core/src/components/ListItem/ListItem.tsx
  packages/core/src/components/ListItem/ListItem.types.ts
  packages/core/src/components/ListItem/ListItemConstants.ts
  packages/core/src/components/ListItem/__stories__/ListItem.stories.tsx
  packages/core/src/components/ListItem/__tests__/ListItem.test.tsx
  packages/core/src/components/ListItem/__tests__/__snapshots__/ListItem.test.tsx.snap
  packages/core/src/components/ListItem/index.ts
  packages/core/src/components/ListItemAvatar/ListItemAvatar.tsx
  packages/core/src/components/ListItemIcon/ListItemIcon.tsx
  packages/core/src/components/ListItemIcon/ListItemIcon.types.ts
  packages/core/src/components/ListItemIcon/ListItemIconConstants.ts
  packages/core/src/components/ListItemIcon/index.ts
Labels: breaking change, vibe3

#2273 chore(Label): deprecate enums
  packages/core/src/components/Label/Label.tsx
  packages/core/src/components/Label/Label.types.ts
  packages/core/src/components/Label/LabelConstants.ts
  packages/core/src/components/Label/__stories__/Label.mdx
  packages/core/src/components/Label/__stories__/Label.stories.tsx
  packages/core/src/components/Label/__tests__/Label.snapshot.test.tsx
  packages/core/src/components/Label/index.ts
  packages/core/src/components/Menu/MenuItem/MenuItem.tsx
Labels: breaking change, vibe3

#2261 chore(LinearProgressBar): deprecate enums
  packages/core/src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBar.types.ts
  packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.ts
  packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/__tests__/LinearProgressBar.snapshot.test.js
  packages/core/src/components/ProgressBars/index.ts
  packages/core/src/components/Tabs/Tab/__tests__/Tab.test.tsx
Labels: breaking change, vibe3

#2282 chore(Steps): deprecate enums
  packages/core/src/components/Steps/Steps.tsx
  packages/core/src/components/Steps/Steps.types.ts
  packages/core/src/components/Steps/StepsCommand.tsx
  packages/core/src/components/Steps/StepsConstants.ts
  packages/core/src/components/Steps/StepsDot.tsx
  packages/core/src/components/Steps/StepsGalleryHeader.tsx
  packages/core/src/components/Steps/StepsHeader.tsx
  packages/core/src/components/Steps/StepsNumbersHeader.tsx
  packages/core/src/components/Steps/__stories__/Steps.stories.helpers.tsx
  packages/core/src/components/Steps/__stories__/Steps.stories.tsx
  packages/core/src/components/Steps/__tests__/Steps.snapshot.test.js
  packages/core/src/components/Steps/index.ts
  packages/core/src/components/Tipseen/TipseenWizard.tsx
Labels: breaking change, vibe3

#2283 chore(BreadcrumbsBar): deprecate enums
  packages/core/src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/BreadcrumbItem.stories.tsx
  packages/core/src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/BreadcrumbItem.test.js
  packages/core/src/components/BreadcrumbsBar/BreadcrumbsBar.tsx
  packages/core/src/components/BreadcrumbsBar/Breadcrumbst.types.ts
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.mdx
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.stories.tsx
  packages/core/src/components/BreadcrumbsBar/index.ts
  packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.tsx
  packages/core/src/storybook/components/related-components/descriptions/breadcrumbs-description.jsx
Labels: breaking change, vibe3

#2286 chore(MultiStep): deprecate enums
  packages/core/src/components/MultiStepIndicator/MultiStep.types.ts
  packages/core/src/components/MultiStepIndicator/MultiStepConstants.ts
  packages/core/src/components/MultiStepIndicator/MultiStepIndicator.tsx
  packages/core/src/components/MultiStepIndicator/__stories__/MultiStepIndicator.mdx
  packages/core/src/components/MultiStepIndicator/__stories__/MultiStepIndicator.stories.helpers.tsx
  packages/core/src/components/MultiStepIndicator/__stories__/MultiStepIndicator.stories.tsx
  packages/core/src/components/MultiStepIndicator/__tests__/MultiStepIndicator.snapshot.test.tsx
  packages/core/src/components/MultiStepIndicator/__tests__/MultiStepIndicator.test.tsx
  packages/core/src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
  packages/core/src/components/MultiStepIndicator/index.ts
  packages/core/src/storybook/components/related-components/descriptions/multi-step-indicator-description.jsx
Labels: breaking change, vibe3

#2287 chore(Menu): deprecate enums
  packages/core/src/components/Menu/MenuTitle/MenuTitle.tsx
  packages/core/src/components/Menu/MenuTitle/MenuTitle.type.ts
  packages/core/src/components/Menu/MenuTitle/MenuTitleConstants.ts
  packages/core/src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.tsx
  packages/core/src/components/Menu/index.ts
Labels: breaking change, vibe3

#2262 chore(Icon): deprecate enums
  packages/core/src/components/AttentionBox/AttentionBox.tsx
  packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.tsx
  packages/core/src/components/AttentionBox/__tests__/AttentionBox.snapshot.test.tsx
  packages/core/src/components/Button/Button.tsx
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Chips/Chips.tsx
  packages/core/src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx
  packages/core/src/components/DatePicker/DateNavigationItem/DateNavigationItem.tsx
  packages/core/src/components/DatePicker/DatePickerHeader/DatePickerHeader.tsx
  packages/core/src/components/Dropdown/components/ClearIndicator/ClearIndicator.jsx
  packages/core/src/components/Dropdown/components/DropdownIndicator/DropdownIndicator.jsx
  packages/core/src/components/ExpandCollapse/ExpandCollapse.tsx
  packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.tsx
  packages/core/src/components/FieldLabel/FieldLabel.tsx
  packages/core/src/components/Icon/Icon.tsx
  packages/core/src/components/Icon/Icon.types.ts
  packages/core/src/components/Icon/IconConstants.ts
  packages/core/src/components/Icon/__stories__/Icon.stories.tsx
  packages/core/src/components/Icon/index.ts
  packages/core/src/components/IconButton/IconButton.tsx
  packages/core/src/components/Link/Link.tsx
  packages/core/src/components/Menu/MenuItem/MenuItem.tsx
  packages/core/src/components/Menu/MenuItem/__stories__/MenuItem.stories.tsx
  packages/core/src/components/Menu/MenuItem/components/MenuItemIcon/MenuItemIcon.tsx
  packages/core/src/components/Menu/MenuItem/components/MenuItemIcon/MenuItemIcon.types.ts
  packages/core/src/components/MenuButton/__stories__/MenuButton.stories.tsx
  packages/core/src/components/Modal/ModalHeader/ModalHeader.tsx
  packages/core/src/components/MultiStepIndicator/MultiStepIndicator.tsx
  packages/core/src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
  packages/core/src/components/Search/Search.tsx
  packages/core/src/components/Slider/Slider.tsx
  packages/core/src/components/Slider/SliderConstants.ts
  packages/core/src/components/Slider/SliderContext.tsx
  packages/core/src/components/Slider/SliderInfixHooks.tsx
  packages/core/src/components/SplitButton/__stories__/SplitButton.stories.tsx
  packages/core/src/components/Tabs/Tab/Tab.tsx
  packages/core/src/components/Tabs/Tab/__tests__/Tab.snapshot.test.tsx
  packages/core/src/components/Tabs/Tab/__tests__/Tab.test.js
  packages/core/src/components/Tabs/Tab/__tests__/__snapshots__/Tab.snapshot.test.tsx.snap
  packages/core/src/components/TextField/TextField.tsx
  packages/core/src/components/Toast/ToastHelpers.tsx
  packages/core/src/storybook/components/related-components/descriptions/divider.jsx
  packages/core/src/storybook/components/related-components/descriptions/expand-collapse-description/expand-collapse-description.jsx
  packages/core/src/storybook/components/related-components/descriptions/menu-button-description.jsx
Labels: breaking change, vibe3

#2291 chore(MenuButton): deprecate enums
  packages/core/src/components/MenuButton/MenuButton.module.scss
  packages/core/src/components/MenuButton/MenuButton.tsx
  packages/core/src/components/MenuButton/MenuButton.types.ts
  packages/core/src/components/MenuButton/MenuButtonConstants.ts
  packages/core/src/components/MenuButton/__stories__/MenuButton.stories.tsx
  packages/core/src/components/MenuButton/__tests__/MenuButton.test.js
  packages/core/src/components/MenuButton/__tests__/__snapshots__/MenuButton.test.js.snap
  packages/core/src/components/MenuButton/index.ts
  packages/core/src/components/ResponsiveList/ResponsiveList.tsx
  packages/core/src/components/ResponsiveList/ResponsiveList.types.ts
  packages/core/src/components/ResponsiveList/__tests__/__snapshots__/ResponsiveList.test.js.snap
  packages/core/src/components/Table/TableRowMenu/TableRowMenu.tsx
Labels: breaking change, vibe3
