Repository mondaycom/vibe, pull requests merged in 2025-06, with the labels that each got.

#2934 feat: Add steps component to testkit
  packages/testkit/components/Steps.ts
  packages/testkit/components/index.ts
Labels: feature

#2945 docs(Badge): cleanup stories
  packages/core/src/components/Badge/__stories__/Badge.stories.tsx
Labels: Review effort 2/5

#2949 docs(Toggle): cleanup stories
  packages/core/src/components/Toggle/__stories__/Toggle.mdx
  packages/core/src/components/Toggle/__stories__/Toggle.stories.scss
  packages/core/src/components/Toggle/__stories__/Toggle.stories.tsx
Labels: Review effort 2/5

#2951 docs: update Cursor rules for storybook's dos and donts
  .cursor/rules/storybook-stories.mdc
Labels: Review effort 1/5

#2956 docs(VirtualizedGrid): cleanup stories
  packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.tsx
Labels: Review effort 1/5

#2957 docs(VirtualizedList): cleanup stories
  packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.module.scss
  packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.stories.tsx
Labels: Review effort 2/5
