Repository mondaycom/vibe, pull requests merged in 2025-09, with the labels that each got.

#3080 fix(Chips): warning color missing hover state
  packages/core/src/types/Colors.ts
Labels: Review effort 1/5

#3082 ci: do not fail pre-release if not running with a PR open
  .github/workflows/prerelease.yml
Labels: Review effort 2/5

#3084 feat: add getVibeComponentAccessibility tool to retrieve a11y requirements
  packages/core/src/storybook/stand-alone-documentaion/mcp/mcp.mdx
  packages/mcp/README.md
  packages/mcp/package.json
  packages/mcp/scripts/extract-accessibility.js
  packages/mcp/src/index.ts
  packages/mcp/src/server/tools/get-vibe-component-accessibility.ts
Labels: Review effort 3/5

#3085 docs: added accessibility sections
  packages/core/src/components/AlertBanner/__stories__/AlertBanner.mdx
  packages/core/src/components/AttentionBox/__stories__/AttentionBox.mdx
  packages/core/src/components/Avatar/__stories__/Avatar.mdx
  packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.mdx
  packages/core/src/components/Button/__stories__/Button.mdx
  packages/core/src/components/ButtonGroup/__stories__/ButtonGroup.mdx
  packages/core/src/components/IconButton/__stories__/IconButton.mdx
  packages/core/src/components/Link/__stories__/Link.mdx
  packages/core/src/components/Menu/Menu/__stories__/Menu.mdx
  packages/core/src/components/Menu/MenuItem/__stories__/MenuItem.mdx
  packages/core/src/components/MenuButton/__stories__/MenuButton.mdx
  packages/core/src/components/Tabs/__stories__/Tabs.mdx
  packages/core/src/components/Toast/__stories__/Toast.mdx
  packages/core/src/components/Tooltip/__stories__/Tooltip.mdx
  packages/core/src/components/Tooltip/__stories__/Tooltip.stories.tsx
Labels: Review effort 2/5

#3090 feat(Dropdown): add loading state
  packages/core/src/components/DropdownNew/Dropdown.types.ts
  packages/core/src/components/DropdownNew/components/Trigger/TriggerActions.tsx
  packages/core/src/components/DropdownNew/context/DropdownContext.types.ts
  packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx
Labels: Review effort 2/5

#3089 chore: remove compat from es-toolkit functions
  packages/core/src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
  packages/core/src/components/Combobox/Combobox.tsx
  packages/core/src/components/DatePicker/date-picker-utils.ts
  packages/core/src/components/Dialog/Dialog.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
  packages/core/src/components/Slider/SelectionIndicator.tsx
  packages/core/src/components/Steps/StepsGalleryHeader.tsx
  packages/core/src/components/Tooltip/Tooltip.tsx
  packages/core/src/hooks/useDebounceEvent/index.ts
  packages/core/src/hooks/useElementsOverflowingIndex.ts
  packages/core/src/hooks/useResizeObserver.ts
  packages/core/src/hooks/useStyle.ts
  packages/core/src/hooks/useThrottledCallback.ts
  packages/core/src/utils/dom-utils.ts
  packages/core/src/utils/function-utils.ts
Labels: Review effort 2/5

#3104 fix(DropdownNew): Searchable controlled multi dropdown item selection
  packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
Labels: Review effort 2/5

#3112 feat(RadioButton): add ariaLabel & ariaDescribedBy
  packages/core/src/components/RadioButton/RadioButton.tsx
Labels: Review effort 2/5

#3114 feat(DropdownNew): a11y improvements
  packages/core/src/components/DropdownNew/Dropdown.types.ts
  packages/core/src/components/DropdownNew/__stories__/Dropdown.mdx
  packages/core/src/components/DropdownNew/__stories__/Dropdown.stories.tsx
  packages/core/src/components/DropdownNew/components/Menu/Menu.tsx
  packages/core/src/components/DropdownNew/components/Trigger/TriggerActions.tsx
  packages/core/src/components/DropdownNew/context/DropdownContext.types.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownMultiSelect.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownSelect.ts
  packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx
Labels: Review effort 3/5

#3109 fix(DropdownNew): onInputChange return null instead of empty string
  packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
Labels: Review effort 2/5

#3116 fix(Dropdown): use Select component as named export
  packages/core/package.json
  packages/core/src/components/Dropdown/Dropdown.tsx
  yarn.lock
Labels: Review effort 2/5

#3117 fix: Revert Dropdown use Select component as named export
  packages/core/package.json
  packages/core/src/components/Dropdown/Dropdown.tsx
  yarn.lock
Labels: Review effort 2/5

#3122 fix(Dialog): add LayerProvider
  packages/core/src/components/Dialog/Dialog.tsx
Labels: Review effort 2/5

#3095 feat(Info): new component
  .cursor/rules/storybook-stories.mdc
  packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
  packages/core/src/components/DialogContentContainer/DialogContentContainer.tsx
  packages/core/src/components/IconButton/__stories__/IconButton.mdx
  packages/core/src/components/IconButton/__stories__/IconButton.stories.helpers.tsx
  packages/core/src/components/Info/Info.tsx
  packages/core/src/components/Info/Info.types.ts
  packages/core/src/components/Info/__stories__/Info.mdx
  packages/core/src/components/Info/__stories__/Info.stories.module.scss
  packages/core/src/components/Info/__stories__/Info.stories.tsx
  packages/core/src/components/Info/__stories__/assets/do1.png
  packages/core/src/components/Info/__stories__/assets/do2.png
  packages/core/src/components/Info/__stories__/assets/dont1.png
  packages/core/src/components/Info/__stories__/assets/dont2.png
  packages/core/src/components/Info/__stories__/assets/usecaseboard.png
  packages/core/src/components/Info/__stories__/assets/usecasecolumn.png
  packages/core/src/components/Info/__tests__/Info.test.tsx
  packages/core/src/components/Info/components/InfoDialogContent/InfoDialogContent.module.scss
  packages/core/src/components/Info/components/InfoDialogContent/InfoDialogContent.tsx
  packages/core/src/components/Info/components/InfoDialogContent/InfoDialogContent.types.ts
  packages/core/src/components/Info/components/InfoDialogContent/__tests__/InfoDialogContent.test.tsx
  packages/core/src/components/Info/components/InfoLink/InfoLink.module.scss
  packages/core/src/components/Info/components/InfoLink/InfoLink.tsx
  packages/core/src/components/Info/components/InfoLink/__tests__/InfoLink.test.tsx
  packages/core/src/components/Info/components/index.ts
  packages/core/src/components/Info/index.ts
  packages/core/src/components/NumberField/__stories__/NumberField.stories.tsx
  packages/core/src/components/index.ts
  packages/core/src/tests/constants.ts
Labels: Review effort 3/5

#3108 feat(DropdownNew): fix types
  packages/core/src/components/DropdownNew/Dropdown.types.ts
Labels: Review effort 2/5
