Repository mondaycom/vibe, pull requests merged in 2025-08, with the labels that each got.

#3024 fix(DatePicker): add default value for onPickDate prop
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/DatePicker/__tests__/DatePicker.test.tsx
Labels: Review effort 2/5

#3027 docs: add placeholder stories to EditableHeading, EditableText
  packages/core/src/components/EditableHeading/__stories__/EditableHeading.mdx
  packages/core/src/components/EditableHeading/__stories__/EditableHeading.stories.tsx
  packages/core/src/components/EditableText/__stories__/EditableText.mdx
  packages/core/src/components/EditableText/__stories__/EditableText.stories.tsx
Labels: Review effort 1/5

#2985 docs(BreadcrumbsBar): update story
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.mdx
  packages/core/src/components/BreadcrumbsBar/__stories__/assets/do1.png
  packages/core/src/components/BreadcrumbsBar/__stories__/assets/dont1.png
Labels: Review effort 1/5

#3031 feat(Tabs): add support for Home and End key navigation
  packages/core/src/hooks/useFullKeyboardListeners.ts
  packages/core/src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.ts
Labels: Review effort 3/5

#3035 feat(mcp): implement token fetching with retry logic and categorize tokens
  packages/mcp/src/server/tools/token-metadata-service.ts
Labels: Review effort 3/5, Possible security concern

#3040 docs: enhance accessibility in stories by adding IDs and aria-labels
  packages/core/src/components/Accordion/Accordion/__stories__/Accordion.stories.tsx
  packages/core/src/components/AlertBanner/__stories__/AlertBanner.stories.tsx
  packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.tsx
  packages/core/src/components/Avatar/__stories__/Avatar.stories.tsx
  packages/core/src/components/Badge/__stories__/Badge.stories.tsx
  packages/core/src/components/Button/__stories__/Button.stories.tsx
  packages/core/src/components/ButtonGroup/__stories__/ButtonGroup.stories.tsx
  packages/core/src/components/Checkbox/__stories__/Checkbox.stories.tsx
  packages/core/src/components/Chips/__stories__/Chips.stories.tsx
  packages/core/src/components/ColorPicker/__stories__/ColorPicker.stories.tsx
  packages/core/src/components/Counter/__stories__/Counter.stories.tsx
  packages/core/src/components/DatePicker/__stories__/DatePicker.stories.tsx
  packages/core/src/components/Dialog/__stories__/Dialog.stories.tsx
  packages/core/src/components/DropdownNew/__stories__/Dropdown.stories.tsx
  packages/core/src/components/EditableHeading/__stories__/EditableHeading.stories.tsx
  packages/core/src/components/EditableText/__stories__/EditableText.stories.tsx
  packages/core/src/components/Icon/__stories__/Icon.stories.tsx
  packages/core/src/components/IconButton/__stories__/IconButton.stories.tsx
  packages/core/src/components/Label/__stories__/Label.stories.tsx
  packages/core/src/components/Link/__stories__/Link.stories.tsx
  packages/core/src/components/Loader/__stories__/Loader.stories.tsx
  packages/core/src/components/MenuButton/__stories__/MenuButton.stories.tsx
  packages/core/src/components/MultiStepIndicator/__stories__/MultiStepIndicator.stories.tsx
  packages/core/src/components/NumberField/__stories__/NumberField.stories.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.tsx
  packages/core/src/components/RadioButton/__stories__/RadioButton.stories.tsx
  packages/core/src/components/Search/__stories__/Search.stories.tsx
  packages/core/src/components/Skeleton/__stories__/Skeleton.stories.tsx
  packages/core/src/components/Slider/__stories__/Slider.stories.tsx
  packages/core/src/components/SplitButton/__stories__/SplitButton.stories.tsx
  packages/core/src/components/Steps/__stories__/Steps.stories.tsx
  packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
  packages/core/src/components/Tabs/__stories__/Tabs.stories.tsx
  packages/core/src/components/TextArea/__stories__/TextArea.stories.tsx
  packages/core/src/components/TextField/__stories__/TextField.stories.tsx
  packages/core/src/components/Tipseen/__stories__/Tipseen.stories.tsx
  packages/core/src/components/Toast/__stories__/Toast.stories.tsx
  packages/core/src/components/Toggle/__stories__/Toggle.stories.tsx
  packages/core/src/components/Tooltip/__stories__/Tooltip.stories.tsx
Labels: Review effort 4/5

#3041 fix(Label): fix line kind when using content colors
  packages/core/src/components/Label/Label.tsx
Labels: Review effort 2/5

#3042 test: add snapshot tests for hooks exports
  packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
  packages/core/src/__tests__/exports.test.ts
Labels: Review effort 1/5

#3043 docs: fix import paths
  packages/core/src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.mdx
  packages/core/src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.mdx
  packages/core/src/hooks/useAfterFirstRender/__stories__/useAfterFirstRender.mdx
  packages/core/src/hooks/useClickOutside/__stories__/useClickOutside.mdx
  packages/core/src/hooks/useClickableProps/__stories__/useClickableProps.mdx
  packages/core/src/hooks/useDebounceEvent/__stories__/useDebounceEvent.mdx
  packages/core/src/hooks/useDisableScroll/__stories__/useDisableScroll.mdx
  packages/core/src/hooks/useEventListener/__stories__/useEventListener.mdx
  packages/core/src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.mdx
  packages/core/src/hooks/useHover/__stories__/useHover.mdx
  packages/core/src/hooks/useIsOverflowing/__stories__/useIsOverflowing.mdx
  packages/core/src/hooks/useKeyEvent/__stories__/useKeyEvent.mdx
  packages/core/src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.mdx
  packages/core/src/hooks/useMediaQuery/__stories__/useMediaQuery.mdx
  packages/core/src/hooks/usePrevious/__stories__/usePrevious.mdx
  packages/core/src/hooks/useSetFocus/__stories__/useSetFocus.mdx
  packages/core/src/hooks/useSwitch/__stories__/useSwitch.mdx
  packages/core/src/hooks/useTimeout/__stories__/useTimeout.mdx
  packages/core/src/hooks/useVibeMediaQuery/__stories__/useVibeMediaQuery.mdx
Labels: Review effort 2/5

#3049 ci(bundle-check): update minimum change threshold to 1KB
  scripts/bundle-check/compare-bundles.js
Labels: Review effort 2/5

#3048 feat(Toggle): add noSpacing prop to remove horizontal spacing
  packages/core/src/components/Toggle/MockToggle.module.scss
  packages/core/src/components/Toggle/MockToggle.tsx
  packages/core/src/components/Toggle/Toggle.tsx
Labels: Review effort 2/5

#3055 ci(release): add Slack notification for release start in workflows
  .github/workflows/release-v2.yml
  .github/workflows/release.yml
Labels: Review effort 2/5

#3032 feat(Table): use custom scrollbar
  packages/core/src/components/Table/Table/Table.module.scss
  packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.module.scss
  packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
Labels: Review effort 2/5

#3056 docs: update link in Storybook for auto-add MCP to Cursor
  packages/core/src/storybook/stand-alone-documentaion/mcp/mcp.mdx
  packages/mcp/README.md
Labels: Review effort 1/5

#3044 docs: update storybook-addon-playground to 2.0.0 to improve storybook playground
  packages/core/.storybook/main.ts
  packages/core/package.json
  yarn.lock
Labels: Review effort 2/5

#3060 ci: fix send slack notification
  .github/workflows/release-v2.yml
  .github/workflows/release.yml
Labels: Review effort 2/5

#3063 feat(Link): add `style` prop for inline styling
  packages/core/src/components/Link/Link.tsx
Labels: Review effort 1/5

#3062 chore: add data-vibe to components
  packages/core/src/components/Accordion/Accordion/__tests__/__snapshots__/Accordion.snapshot.test.tsx.snap
  packages/core/src/components/Accordion/AccordionItem/__tests__/__snapshots__/AccordionItem.snapshot.test.tsx.snap
  packages/core/src/components/AlertBanner/AlertBanner.tsx
  packages/core/src/components/AlertBanner/__tests__/__snapshots__/AlertBanner.snapshot.test.tsx.snap
  packages/core/src/components/AttentionBox/AttentionBox.tsx
  packages/core/src/components/AttentionBox/__tests__/__snapshots__/AttentionBox.snapshot.test.tsx.snap
  packages/core/src/components/Avatar/Avatar.tsx
  packages/core/src/components/Avatar/__tests__/__snapshots__/Avatar.snapshot.test.tsx.snap
  packages/core/src/components/AvatarGroup/AvatarGroup.tsx
  packages/core/src/components/AvatarGroup/__tests__/__snapshots__/AvatarGroup.snapshot.test.jsx.snap
  packages/core/src/components/Badge/Badge.tsx
  packages/core/src/components/Badge/__tests__/__snapshots__/Badge.snapshot.test.tsx.snap
  packages/core/src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/BreadcrumbItem.snapshot.test.jsx.snap
  packages/core/src/components/BreadcrumbsBar/BreadcrumbsBar.tsx
  packages/core/src/components/BreadcrumbsBar/__tests__/__snapshots__/BreadcrumbsBar.snapshot.test.jsx.snap
  packages/core/src/components/Checkbox/Checkbox.tsx
  packages/core/src/components/Checkbox/__tests__/__snapshots__/Checkbox.snapshot.test.tsx.snap
  packages/core/src/components/Chips/Chips.tsx
  packages/core/src/components/Chips/__tests__/__snapshots__/Chips.snapshot.test.tsx.snap
  packages/core/src/components/ColorPicker/ColorPicker.tsx
  packages/core/src/components/ColorPicker/__tests__/__snapshots__/ColorPicker.test.tsx.snap
  packages/core/src/components/Combobox/Combobox.tsx
  packages/core/src/components/Combobox/__tests__/__snapshots__/Combobox.snapshot.test.tsx.snap
  packages/core/src/components/Counter/Counter.tsx
  packages/core/src/components/Counter/__tests__/__snapshots__/Counter.snapshot.test.tsx.snap
  packages/core/src/components/DatePicker/DatePicker.tsx
  packages/core/src/components/Divider/Divider.tsx
  packages/core/src/components/Divider/__tests__/__snapshots__/Divider.test.tsx.snap
  packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.jsx.snap
  packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.tsx
  packages/core/src/components/EditableHeading/EditableHeading.tsx
  packages/core/src/components/EmptyState/EmptyState.tsx
  packages/core/src/components/ExpandCollapse/ExpandCollapse.tsx
  packages/core/src/components/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.test.tsx.snap
  packages/core/src/components/Label/Label.tsx
  packages/core/src/components/Label/__tests__/__snapshots__/Label.snapshot.test.tsx.snap
  packages/core/src/components/Link/Link.tsx
  packages/core/src/components/Link/__tests__/__snapshots__/Link.snapshot.test.tsx.snap
  packages/core/src/components/ListItemAvatar/__tests__/__snapshots__/ListItemAvatar.test.tsx.snap
  packages/core/src/components/Menu/Menu/Menu.tsx
  packages/core/src/components/Menu/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
  packages/core/src/components/Menu/MenuItem/__tests__/__snapshots__/MenuItem.snapshot.test.tsx.snap
  packages/core/src/components/Modal/Modal/Modal.tsx
  packages/core/src/components/MultiStepIndicator/__tests__/__snapshots__/MultiStepIndicator.snapshot.test.tsx.snap
  packages/core/src/components/NumberField/NumberField.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/__tests__/__snapshots__/LinearProgressBar.snapshot.test.tsx.snap
  packages/core/src/components/RadioButton/RadioButton.tsx
  packages/core/src/components/RadioButton/__tests__/__snapshots__/RadioButton.snapshot.test.tsx.snap
  packages/core/src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/SplitButtonMenu.snapshot.test.tsx.snap
  packages/core/src/components/Steps/Steps.tsx
  packages/core/src/components/Steps/__tests__/__snapshots__/Steps.snapshot.test.tsx.snap
  packages/core/src/components/Switch/Switch.tsx
  packages/core/src/components/Table/Table/Table.tsx
  packages/core/src/components/Toast/__tests__/__snapshots__/Toast.snapshot.test.tsx.snap
  packages/core/src/components/Toggle/__tests__/__snapshots__/Toggle.snapshot.test.tsx.snap
  packages/core/src/tests/constants.ts
Labels: Review effort 2/5

#3070 fix(DropdownBase): update active state to include isOpen condition
  packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.tsx
Labels: Review effort 2/5

#3071 fix(Dropdown): fix size and focus
  packages/core/src/components/DropdownNew/Dropdown.types.ts
  packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.module.scss
  packages/core/src/components/DropdownNew/components/Trigger/Trigger.module.scss
  packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx
Labels: Review effort 2/5

#3073 fix(Dropdown): padding on trigger actions
  packages/core/src/components/DropdownNew/components/Trigger/Trigger.module.scss
Labels: Review effort 2/5
