Repository mondaycom/vibe, pull requests merged in 2025-07, with the labels that each got.

#2965 fix(icons): update DropdownChevronDown and DropdownChevronUp
  packages/core/src/components/Accordion/Accordion/__tests__/__snapshots__/Accordion.snapshot.test.tsx.snap
  packages/core/src/components/Accordion/AccordionItem/__tests__/__snapshots__/AccordionItem.snapshot.test.tsx.snap
  packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.jsx.snap
  packages/core/src/components/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.test.tsx.snap
  packages/core/src/components/SplitButton/__tests__/__snapshots__/SplitButton.snapshot.test.tsx.snap
  packages/icons/src/react/DropdownChevronDown.tsx
  packages/icons/src/react/DropdownChevronUp.tsx
  packages/icons/src/svg/DropdownChevronDown.svg
  packages/icons/src/svg/DropdownChevronUp.svg
Labels: Review effort 2/5

#2936 fix: update steps component to testkit
  packages/testkit/__tests__/button.test.js
  packages/testkit/components/Steps.ts
  packages/testkit/components/index.ts
Labels: Review effort 3/5

#2967 docs(Steps): cleanup stories
  packages/core/src/components/Steps/__stories__/Steps.stories.scss
  packages/core/src/components/Steps/__stories__/Steps.stories.tsx
Labels: Review effort 2/5

#2968 docs(ThemeProvider): cleanup stories
  packages/core/src/components/ThemeProvider/__stories__/ThemeProvider.stories.helpers.tsx
  packages/core/src/components/ThemeProvider/__stories__/ThemeProvider.stories.module.scss
Labels: Review effort 2/5

#2975 docs(BreadcrumbsBar): refactor stories and styles for improved layout and readability
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.mdx
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.stories.module.scss
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.stories.scss
  packages/core/src/components/BreadcrumbsBar/__stories__/BreadcrumbsBar.stories.tsx
Labels: Review effort 2/5

#2970 docs(Slider): cleanup stories
  packages/core/src/components/Slider/__stories__/Slider.stories.scss
  packages/core/src/components/Slider/__stories__/Slider.stories.tsx
Labels: Review effort 2/5

#2972 docs(DatePicker): cleanup stories
  packages/core/src/components/DatePicker/__stories__/DatePicker.stories.module.scss
  packages/core/src/components/DatePicker/__stories__/DatePicker.stories.tsx
Labels: Review effort 1/5

#2973 docs(Combobox): cleanup stories
  packages/core/src/components/Combobox/__stories__/Combobox.stories.scss
  packages/core/src/components/Combobox/__stories__/Combobox.stories.tsx
  packages/core/src/components/Combobox/__stories__/OptionRenderer.jsx
Labels: Review effort 2/5

#2977 docs(SplitButton): refactor stories and styles for improved layout and readability
  packages/core/src/components/SplitButton/__stories__/SplitButton.stories.scss
  packages/core/src/components/SplitButton/__stories__/SplitButton.stories.tsx
Labels: Review effort 2/5

#2978 docs(Skeleton): refactor stories and styles for improved layout and readability
  packages/core/src/components/Skeleton/__stories__/Skeleton.mdx
  packages/core/src/components/Skeleton/__stories__/Skeleton.stories.scss
  packages/core/src/components/Skeleton/__stories__/Skeleton.stories.tsx
  packages/core/src/components/Skeleton/__stories__/assets/person.png
  packages/core/src/components/Skeleton/__tests__/Skeleton.snapshot.test.jsx
Labels: Review effort 2/5

#2960 feat: Add expand collapse component
  packages/testkit/components/ExpandCollapse.ts
  packages/testkit/components/Menu.ts
  packages/testkit/components/index.ts
Labels: Review effort 3/5

#2982 docs(Table): cleanup stories
  packages/core/src/components/Table/Table/__stories__/Table.mdx
  packages/core/src/components/Table/Table/__stories__/Table.stories.module.scss
  packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
Labels: Review effort 2/5

#2963 chore: changes for React 19
  packages/core/package.json
  packages/core/src/components/AlertBanner/AlertBannerButton/AlertBannerButton.tsx
  packages/core/src/components/Button/Button.tsx
  packages/core/src/components/ButtonGroup/__stories__/assets/Desktop.js
  packages/core/src/components/Counter/Counter.tsx
  packages/core/src/components/Dialog/DialogContent/DialogContent.tsx
  packages/core/src/components/SplitButton/SplitButton.tsx
  packages/core/src/components/Toast/Toast.tsx
  packages/core/src/components/Toast/ToastButton/ToastButton.tsx
  packages/core/src/hooks/useActiveDescendantListFocus/__stories__/hooksDummyComponents/UseActiveDescendantListFocus.jsx
  packages/core/src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.tsx
  packages/core/src/storybook/components/related-components/related-components-decorator.jsx
Labels: Review effort 3/5

#2948 fix: fix @vibe/core/tokens import ts error
  packages/core/package.json
  packages/core/rollup.config.js
  packages/core/types/tokens.d.ts
Labels: Review effort 2/5

#2988 docs(ExpandCollapse): cleanup stories
  packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.module.scss
  packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.tsx
Labels: Review effort 2/5

#2986 docs(Dialog): cleanup stories
  packages/core/src/components/Dialog/__stories__/Dialog.stories.scss
  packages/core/src/components/Dialog/__stories__/Dialog.stories.tsx
  packages/core/src/components/Dialog/__stories__/helpers.tsx
  packages/core/src/storybook/components/related-components/descriptions/dialog-description/dialog-description.tsx
Labels: Review effort 2/5

#2954 chore: refactor stylelint configuration for core and style packages to unify config
  .stylelintrc.json
  packages/core/.stylelintrc.json
  packages/style/.stylelintignore
  packages/style/.stylelintrc.json
  packages/style/src/mixins/_common.scss
  packages/style/src/themes/black-theme.scss
  packages/style/src/themes/dark-theme.scss
  packages/style/src/themes/hacker-theme.scss
  packages/style/src/themes/light-theme.scss
Labels: Review effort 2/5

#2896 feat(Dropdown): New dropdown component
  packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
  packages/core/src/components/BaseList/BaseList.module.scss
  packages/core/src/components/BaseList/BaseList.tsx
  packages/core/src/components/BaseListItem/BaseListItem.module.scss
  packages/core/src/components/BaseListItem/BaseListItem.tsx
  packages/core/src/components/BaseListItem/BaseListItem.types.ts
  packages/core/src/components/BaseListItem/__tests__/BaseListItem.test.tsx
  packages/core/src/components/DropdownNew/Dropdown.tsx
  packages/core/src/components/DropdownNew/Dropdown.types.ts
  packages/core/src/components/DropdownNew/__stories__/Dropdown.mdx
  packages/core/src/components/DropdownNew/__stories__/Dropdown.stories.tsx
  packages/core/src/components/DropdownNew/__stories__/assets/person1.png
  packages/core/src/components/DropdownNew/__stories__/assets/person2.png
  packages/core/src/components/DropdownNew/__stories__/assets/person3.png
  packages/core/src/components/DropdownNew/__tests__/Dropdown.test.tsx
  packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.module.scss
  packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.tsx
  packages/core/src/components/DropdownNew/components/DropdownPopup/DropdownPopup.tsx
  packages/core/src/components/DropdownNew/components/Menu/Menu.tsx
  packages/core/src/components/DropdownNew/components/MultiSelectedValues/MultiSelectedValues.tsx
  packages/core/src/components/DropdownNew/components/Trigger/DropdownChip.tsx
  packages/core/src/components/DropdownNew/components/Trigger/DropdownInput.tsx
  packages/core/src/components/DropdownNew/components/Trigger/MultiSelectTrigger.tsx
  packages/core/src/components/DropdownNew/components/Trigger/SingleSelectTrigger.tsx
  packages/core/src/components/DropdownNew/components/Trigger/Trigger.module.scss
  packages/core/src/components/DropdownNew/components/Trigger/TriggerActions.tsx
  packages/core/src/components/DropdownNew/context/DropdownContext.ts
  packages/core/src/components/DropdownNew/context/DropdownContext.types.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownMultiSelect.ts
  packages/core/src/components/DropdownNew/hooks/useDropdownSelect.ts
  packages/core/src/components/DropdownNew/index.ts
  packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
  packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx
  packages/core/src/components/next.ts
  packages/core/src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.mdx
  packages/core/src/storybook/stand-alone-documentaion/dropdown-migration-guide.mdx
Labels: Review effort 5/5

#2992 fix(Table): fix loading state handling in TableVirtualizedBody
  packages/core/src/components/Table/Table/__tests__/Table.test.tsx
  packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
Labels: Review effort 3/5

#2994 docs: MultiStepIndicator stories cleanup
  packages/core/src/components/MultiStepIndicator/__stories__/MultiStepIndicator.stories.scss
  packages/core/src/components/MultiStepIndicator/__stories__/MultiStepIndicator.stories.tsx
Labels: Review effort 2/5

#2997 docs(LinearProgressBar): refactor stories and styles for improved layout and readability
  packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.helpers.tsx
  packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.scss
  packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.tsx
Labels: Review effort 2/5

#2984 feat(testkit): refactoring testkit components
  packages/testkit/components/BaseElement.ts
  packages/testkit/components/Button.ts
  packages/testkit/components/ButtonGroup.ts
  packages/testkit/components/Checkbox.ts
  packages/testkit/components/ColorPicker.ts
  packages/testkit/components/Combobox.ts
  packages/testkit/components/Dropdown.ts
  packages/testkit/components/ExpandCollapse.ts
  packages/testkit/components/IconButton.ts
  packages/testkit/components/Link.ts
  packages/testkit/components/List.ts
  packages/testkit/components/ListItem.ts
  packages/testkit/components/Loader.ts
  packages/testkit/components/Menu.ts
  packages/testkit/components/MenuButton.ts
  packages/testkit/components/MenuItem.ts
  packages/testkit/components/Modal.ts
  packages/testkit/components/RadioButton.ts
  packages/testkit/components/Search.ts
  packages/testkit/components/SplitButton.ts
  packages/testkit/components/Steps.ts
  packages/testkit/components/Tab.ts
  packages/testkit/components/TabList.ts
  packages/testkit/components/TextArea.ts
  packages/testkit/components/TextField.ts
  packages/testkit/components/Toast.ts
  packages/testkit/components/Toggle.ts
  packages/testkit/components/index.ts
  packages/testkit/tsconfig.json
  packages/testkit/utils/enums.ts
Labels: enhancement, Review effort 4/5

#3003 docs(counter): cleanup stories
  packages/core/src/components/Counter/__stories__/Counter.stories.scss
  packages/core/src/components/Counter/__stories__/Counter.stories.tsx
Labels: Review effort 2/5

#3010 fix: add missing deps
  packages/style/package.json
Labels: Review effort 2/5

#3009 docs(Dropdown): align the dropdown stories to new design
  packages/core/src/components/DropdownNew/__stories__/Dropdown.mdx
  packages/core/src/components/DropdownNew/__stories__/Dropdown.stories.tsx
  packages/core/src/components/DropdownNew/__stories__/assets/do1.png
  packages/core/src/components/DropdownNew/__stories__/assets/dont1.png
Labels: Review effort 2/5

#3012 fix(BaseList): update background color to use secondary background token
  packages/core/src/components/BaseList/BaseList.module.scss
Labels: Review effort 1/5

#3015 docs: add vite config
  packages/core/vite.config.ts
  packages/core/vitest.config.ts
Labels: Review effort 1/5

#3014 docs: fix story props
  packages/core/src/components/Dialog/__stories__/Dialog.stories.tsx
  packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.tsx
  packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
  packages/core/src/components/Tabs/__stories__/Tabs.stories.tsx
Labels: Review effort 2/5

#3017 docs: change figma link
  packages/core/src/storybook/stand-alone-documentaion/welcome/hero/Hero.tsx
Labels: Review effort 1/5

#3018 fix(testkit): improvements + fix for unit tests
  packages/testkit/__tests__/Button.test.ts
  packages/testkit/__tests__/ButtonGroup.test.ts
  packages/testkit/__tests__/Checkbox.test.ts
  packages/testkit/__tests__/ColorPicker.test.ts
  packages/testkit/__tests__/Combobox.test.ts
  packages/testkit/__tests__/Dropdown.test.ts
  packages/testkit/__tests__/ExpandCollapse.test.ts
  packages/testkit/__tests__/IconButton.test.ts
  packages/testkit/__tests__/Link.test.ts
  packages/testkit/__tests__/List.test.ts
  packages/testkit/__tests__/ListItem.test.ts
  packages/testkit/__tests__/Loader.test.ts
  packages/testkit/__tests__/Menu.test.ts
  packages/testkit/__tests__/MenuButton.test.ts
  packages/testkit/__tests__/MenuItem.test.ts
  packages/testkit/__tests__/Modal.test.ts
  packages/testkit/__tests__/RadioButton.test.ts
  packages/testkit/__tests__/Search.test.ts
  packages/testkit/__tests__/SplitButton.test.ts
  packages/testkit/__tests__/Steps.test.ts
  packages/testkit/__tests__/TabList.test.ts
  packages/testkit/__tests__/Text.test.ts
  packages/testkit/__tests__/TextArea.test.ts
  packages/testkit/__tests__/TextField.test.ts
  packages/testkit/__tests__/Toast.test.ts
  packages/testkit/__tests__/Toggle.test.ts
  packages/testkit/components/TextArea.ts
  packages/testkit/scripts/run-changed-tests.js
Labels: enhancement, Review effort 3/5

#3021 docs: remove experimental from mcp
  packages/mcp/README.md
Labels: Review effort 1/5
